// frontend/slices/ai-router-svelte/components/ChatFab.svelte
<script lang="ts">
  import {
    assistantMessage,
    greetingMessage,
    routePrompt,
    userMessage,
    type AiRouterMessage,
    type AiRouterRoute,
    type RouteTier,
  } from "../../ai-router/lib/core";

  type Props = {
    route?: AiRouterRoute;
    feature?: string;
    tier?: RouteTier;
    greeting?: string;
    title?: string;
    placeholder?: string;
  };

  let {
    route,
    feature = "chat-fab",
    tier = "mid",
    greeting = "Hi — how can I help you?",
    title = "Chat",
    placeholder = "Type a message…",
  }: Props = $props();

  let open = $state(false);
  let history = $state.raw<AiRouterMessage[]>([]);
  let input = $state("");
  let pending = $state(false);
  let messages = $derived([greetingMessage(greeting), ...history]);

  async function send(event: SubmitEvent) {
    event.preventDefault();
    const prompt = input.trim();
    if (!prompt || pending) return;
    const stamp = Date.now();
    history = [...history, userMessage(`u-${stamp}`, prompt)];
    input = "";
    pending = true;

    try {
      const result = await routePrompt(route, { feature, tier, prompt });
      history = [...history, assistantMessage(`a-${stamp}`, result)];
    } catch (error) {
      history = [
        ...history,
        {
          id: `err-${stamp}`,
          role: "assistant",
          content: `(error) ${error instanceof Error ? error.message : "unknown"}`,
        },
      ];
    } finally {
      pending = false;
    }
  }
</script>

{#if !open}
  <button
    type="button"
    class="fixed bottom-4 right-4 z-50 grid size-12 place-items-center rounded-full bg-foreground text-background shadow-lg"
    aria-label="Open chat"
    onclick={() => (open = true)}
  >
    <span aria-hidden="true">✦</span>
  </button>
{:else}
  <section class="fixed bottom-4 right-4 z-50 flex h-[28rem] w-[20rem] flex-col overflow-hidden rounded-xl border border-border bg-background shadow-xl sm:w-[24rem]" aria-label={title}>
    <header class="flex items-center justify-between border-b border-border px-4 py-2">
      <div class="flex items-center gap-2">
        <span aria-hidden="true">✦</span>
        <span class="text-sm font-medium">{title}</span>
        <span class="rounded bg-muted px-1.5 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">{tier}</span>
      </div>
      <button type="button" class="grid size-7 place-items-center rounded hover:bg-muted" aria-label="Close chat" onclick={() => (open = false)}>×</button>
    </header>

    <div class="flex-1 space-y-3 overflow-y-auto p-3" aria-live="polite">
      {#each messages as message (message.id)}
        <div
          class={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${message.role === "user" ? "ml-auto bg-foreground text-background" : "bg-muted text-foreground"}`}
        >
          {message.content}
        </div>
      {/each}
      {#if pending}
        <div class="max-w-[85%] rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">…</div>
      {/if}
    </div>

    <form class="flex gap-2 border-t border-border p-2" onsubmit={send}>
      <label class="sr-only" for="ai-router-message">Message</label>
      <input
        id="ai-router-message"
        class="min-w-0 flex-1 rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
        value={input}
        oninput={(event) => (input = event.currentTarget.value)}
        placeholder={placeholder}
        disabled={pending}
      />
      <button
        type="submit"
        class="rounded-md bg-foreground px-3 py-2 text-sm text-background disabled:cursor-not-allowed disabled:opacity-50"
        disabled={pending || !input.trim()}
        aria-label="Send"
      >
        ↑
      </button>
    </form>
  </section>
{/if}

// frontend/slices/ai-router/components/chat-fab.tsx
"use client";

// Floating chat button + popover panel.
// Wires to api.features.ai.actions.callModel({ feature, prompt, tier }).
//
// Usage in your app/layout.tsx:
//   import { ChatFab } from "@/features/ai-router/components/chat-fab";
//   <ChatFab feature="support" tier="mid" />

import { useState, useRef, useEffect } from "react";
import { Bot, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type Tier = "nano" | "mid" | "flagship";
type Message = { id: string; role: "user" | "assistant"; content: string };

export function ChatFab({
  tier = "mid",
  greeting = "Hi — how can I help you?",
  title = "Chat",
  placeholder = "Type a message…",
}: {
  feature?: string;
  tier?: Tier;
  /** First assistant message (English default — override for i18n). */
  greeting?: string;
  /** Panel header label. */
  title?: string;
  /** Composer input placeholder. */
  placeholder?: string;
}) {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    { id: "greet", role: "assistant", content: greeting },
  ]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (open && scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, open]);

  async function send() {
    const prompt = input.trim();
    if (!prompt || pending) return;
    const userMsg: Message = { id: `u-${Date.now()}`, role: "user", content: prompt };
    setMessages((m) => [...m, userMsg]);
    setInput("");
    setPending(true);

    try {
      // Replace with: const text = await convex.action(api.features.ai.actions.callModel, { feature, prompt, tier });
      // Stub response below — wire your action when ready.
      const text = await stubReply(prompt);
      setMessages((m) => [...m, { id: `a-${Date.now()}`, role: "assistant", content: text }]);
    } catch (err) {
      setMessages((m) => [
        ...m,
        {
          id: `err-${Date.now()}`,
          role: "assistant",
          content: `(error) ${err instanceof Error ? err.message : "unknown"}`,
        },
      ]);
    } finally {
      setPending(false);
    }
  }

  if (!open) {
    return (
      <Button
        size="lg"
        onClick={() => setOpen(true)}
        aria-label="Open chat"
        className="fixed bottom-4 right-4 z-50 h-12 w-12 rounded-full p-0 shadow-lg"
      >
        <Bot className="size-5" />
      </Button>
    );
  }

  return (
    <Card className="fixed bottom-4 right-4 z-50 flex h-[28rem] w-[20rem] flex-col overflow-hidden border-border/60 shadow-xl sm:w-[24rem]">
      <header className="flex items-center justify-between border-b border-border/60 px-4 py-2">
        <div className="flex items-center gap-2">
          <Bot className="size-4 text-foreground/70" />
          <span className="text-sm font-medium">{title}</span>
          <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">
            {tier}
          </span>
        </div>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setOpen(false)}
          aria-label="Close chat"
          className="size-6 rounded text-muted-foreground hover:bg-accent/40 hover:text-foreground"
        >
          <X className="size-4" />
        </Button>
      </header>
      <CardContent ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto p-3">
        {messages.map((m) => (
          <div
            key={m.id}
            className={cn(
              "max-w-[85%] rounded-lg px-3 py-2 text-sm",
              m.role === "user"
                ? "ml-auto bg-foreground text-background"
                : "bg-muted text-foreground",
            )}
          >
            {m.content}
          </div>
        ))}
        {pending && (
          <div className="max-w-[85%] rounded-lg bg-muted px-3 py-2 text-sm text-muted-foreground">
            …
          </div>
        )}
      </CardContent>
      <footer className="flex gap-2 border-t border-border/60 p-2">
        <Input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && send()}
          placeholder={placeholder}
          className="flex-1 text-sm"
          disabled={pending}
        />
        <Button size="sm" onClick={send} disabled={pending || !input.trim()} aria-label="Send">
          <Send className="size-4" />
        </Button>
      </footer>
    </Card>
  );
}

async function stubReply(prompt: string): Promise<string> {
  await new Promise((r) => setTimeout(r, 400));
  return `(stub) Received: "${prompt.slice(0, 80)}${prompt.length > 80 ? "…" : ""}". Wire ChatFab to api.features.ai.actions.callModel for real responses.`;
}
