// frontend/slices/html-studio-svelte/app.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import StudioToolbar from "./components/StudioToolbar.svelte";
  import SavedPages from "./components/SavedPages.svelte";
  import StudioPane from "./components/StudioPane.svelte";
  import {
    DEVICE_NEXT,
    SPLIT_MIN,
    STARTER,
    htmlStudioApi,
    payloadSlug,
    shareUrl,
    type Device,
    type PageRow,
    type View,
    type Visibility,
  } from "@/features/html-studio/lib/core";

  let { payload = undefined }: { payload?: unknown } = $props();
  let html = $state(STARTER);
  let preview = $state(STARTER);
  let title = $state("Untitled");
  let slug = $state<string | null>(null);
  let visibility = $state<Visibility>("public");
  let rows = $state<PageRow[]>([]);
  let saving = $state(false);
  let listOpen = $state(false);
  let view = $state<View>("split");
  let device = $state<Device>("full");
  let bodyWidth = $state(0);
  let error = $state("");

  let narrow = $derived(bodyWidth > 0 && bodyWidth < SPLIT_MIN);
  let effectiveView = $derived<View>(narrow && view === "split" ? "preview" : view);
  let showEditor = $derived(effectiveView === "code" || effectiveView === "split");
  let showPreview = $derived(effectiveView === "preview" || effectiveView === "split");

  $effect(() => {
    const source = html;
    const timer = setTimeout(() => (preview = source), 250);
    return () => clearTimeout(timer);
  });

  async function refreshList() {
    if (!htmlStudioApi.hasList) return;
    rows = await htmlStudioApi.list();
  }

  async function openPage(nextSlug: string) {
    const page = await htmlStudioApi.load(nextSlug);
    if (!page) return;
    html = page.html;
    preview = page.html;
    title = page.title;
    slug = page.slug;
    visibility = page.visibility;
    listOpen = false;
  }

  async function save() {
    if (!htmlStudioApi.canSave || saving) return;
    saving = true;
    error = "";
    try {
      const result = await htmlStudioApi.save({ slug: slug ?? undefined, title, html, visibility });
      slug = result.slug;
      await refreshList();
      await copyLink(result.slug);
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Unable to save page.";
    } finally {
      saving = false;
    }
  }

  function newPage() {
    slug = null;
    title = "Untitled";
    html = STARTER;
    preview = STARTER;
    visibility = "public";
  }

  async function removePage(nextSlug: string) {
    await htmlStudioApi.remove(nextSlug);
    if (nextSlug === slug) newPage();
    await refreshList();
  }

  async function copyLink(nextSlug: string | null = slug) {
    if (!nextSlug || typeof navigator === "undefined") return;
    try {
      await navigator.clipboard.writeText(shareUrl(nextSlug));
    } catch {
      // Clipboard can be denied in embedded previews; publishing still succeeds.
    }
  }

  onMount(() => {
    void refreshList();
    const initialSlug = payloadSlug(payload);
    if (initialSlug) void openPage(initialSlug);
  });
</script>

<div class="relative flex h-full flex-col bg-background text-foreground">
  <StudioToolbar
    bind:title
    bind:view
    bind:visibility
    {narrow}
    {saving}
    canSave={htmlStudioApi.canSave}
    hasList={htmlStudioApi.hasList}
    {listOpen}
    rowCount={rows.length}
    {slug}
    onNew={newPage}
    onToggleList={() => { listOpen = !listOpen; void refreshList(); }}
    onSave={() => void save()}
    onCopy={() => void copyLink()}
  />

  {#if slug}
    <button type="button" class="flex shrink-0 items-center gap-2 border-b border-border bg-muted/40 px-3 py-1 text-left text-[11px] text-muted-foreground" onclick={() => void copyLink()}>
      <span class="truncate font-mono">{shareUrl(slug)}</span>
      {#if visibility === "private"}<span class="rounded bg-muted px-1 text-[10px]">private</span>{/if}
    </button>
  {/if}

  {#if error}
    <p class="border-b border-destructive/30 bg-destructive/10 px-3 py-2 text-xs text-destructive">{error}</p>
  {/if}

  <div class="flex min-h-0 flex-1">
    {#if listOpen && htmlStudioApi.hasList}
      <SavedPages {rows} {slug} onOpen={(value) => void openPage(value)} onRemove={(value) => void removePage(value)} />
    {/if}
    <div class="flex min-h-0 min-w-0 flex-1" bind:clientWidth={bodyWidth}>
      <StudioPane
        bind:html
        {preview}
        {showEditor}
        {showPreview}
        {device}
        onCycleDevice={() => (device = DEVICE_NEXT[device])}
      />
    </div>
  </div>
</div>

// frontend/slices/html-studio/app.tsx
"use client";
/* HTML Studio — a tiny web-page studio. Type HTML / CSS / JS, see it render
   live in a SANDBOXED iframe (opaque origin — lib/util.ts HTML_SANDBOX), then
   Save to get a shareable /p/<slug>. The backend (save / load / list / remove)
   is INJECTED via the host seam (lib/host.ts); unwired it runs on an in-memory
   mock so the editor + live preview + saved list are interactive with zero
   backend. View toggle (Code / Split / Preview) + device-width preview kept. */
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { useHtmlStudioApi } from "./lib/host";
import type { AppProps, PageRow, Visibility } from "./lib/host";
import { DEVICE_ICON, DEVICE_NEXT, SPLIT_MIN, STARTER, shareUrl, payloadSlug } from "./lib/util";
import type { Device, View } from "./lib/util";
import { Toolbar } from "./components/toolbar";
import { Editor, PreviewPane } from "./components/panes";
import { SavedList, ShareStrip } from "./components/saved-list";

// Default export so an os-shell can lazy-load this as a window app.
export default function HtmlStudio({ payload }: AppProps = {}) {
  const api = useHtmlStudioApi();
  const [html, setHtml] = useState(STARTER);
  const [title, setTitle] = useState("Untitled");
  const [slug, setSlug] = useState<string | null>(() => payloadSlug(payload));
  const [visibility, setVisibility] = useState<Visibility>("public");
  const [preview, setPreview] = useState(STARTER);
  const [rows, setRows] = useState<PageRow[]>([]);
  const [saving, setSaving] = useState(false);
  const [listOpen, setListOpen] = useState(false);
  const [view, setView] = useState<View>("split");
  const [device, setDevice] = useState<Device>("full");

  // Container-responsive layout (the window resizes freely).
  const bodyRef = useRef<HTMLDivElement>(null);
  const [w, setW] = useState(0);
  useLayoutEffect(() => {
    const el = bodyRef.current;
    if (!el) return;
    setW(el.getBoundingClientRect().width);
    if (typeof ResizeObserver === "undefined") return;
    const ro = new ResizeObserver((entries) => setW(entries[0].contentRect.width));
    ro.observe(el);
    return () => ro.disconnect();
  }, []);
  const narrow = w > 0 && w < SPLIT_MIN;
  const v: View = narrow && view === "split" ? "preview" : view;
  const showEditor = v === "code" || v === "split";
  const showPreview = v === "preview" || v === "split";

  // Debounced live preview.
  useEffect(() => {
    const id = setTimeout(() => setPreview(html), 250);
    return () => clearTimeout(id);
  }, [html]);

  const refreshList = useCallback(() => {
    if (!api.hasList) return;
    api.list().then(setRows).catch(() => {});
  }, [api]);

  const openPage = useCallback(
    (s: string) => {
      api
        .load(s)
        .then((p) => {
          if (!p) return;
          setHtml(p.html);
          setPreview(p.html);
          setTitle(p.title);
          setSlug(p.slug);
          setVisibility(p.visibility);
          setListOpen(false);
        })
        .catch(() => {});
    },
    [api],
  );

  // Initial: load the saved list and, if launched with a slug, that page.
  useEffect(() => {
    refreshList();
    const s = payloadSlug(payload);
    if (s) openPage(s);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const copyLink = useCallback(
    async (s: string | null = slug) => {
      if (!s) return;
      try {
        await navigator.clipboard.writeText(shareUrl(s));
      } catch {
        /* clipboard blocked — non-fatal */
      }
    },
    [slug],
  );

  async function save() {
    if (!api.canSave || saving) return;
    setSaving(true);
    try {
      const res = await api.save({ slug: slug ?? undefined, title, html, visibility });
      setSlug(res.slug);
      refreshList();
      void copyLink(res.slug);
    } finally {
      setSaving(false);
    }
  }

  function newPage() {
    setSlug(null);
    setTitle("Untitled");
    setHtml(STARTER);
    setPreview(STARTER);
    setVisibility("public");
  }

  async function removePage(s: string) {
    await api.remove(s);
    if (s === slug) newPage();
    refreshList();
  }

  const DeviceIcon = DEVICE_ICON[device];
  const isPrivate = visibility === "private";

  return (
    <div className="relative flex h-full flex-col bg-background text-foreground">
      <Toolbar
        title={title}
        onTitle={setTitle}
        view={v}
        narrow={narrow}
        onView={setView}
        isPrivate={isPrivate}
        onToggleVisibility={() => setVisibility((x) => (x === "public" ? "private" : "public"))}
        onNewPage={newPage}
        listOpen={listOpen}
        rowCount={rows.length}
        onToggleList={() => {
          setListOpen((o) => !o);
          refreshList();
        }}
        onSave={save}
        saving={saving}
        canSave={api.canSave}
        hasList={api.hasList}
        onCopyLink={() => void copyLink()}
        slug={slug}
      />

      {slug && <ShareStrip slug={slug} isPrivate={isPrivate} onCopy={() => void copyLink()} />}

      <div className="flex min-h-0 flex-1">
        {listOpen && api.hasList && (
          <SavedList rows={rows} slug={slug} onOpen={openPage} onRemove={removePage} />
        )}
        <div ref={bodyRef} className="flex min-h-0 min-w-0 flex-1">
          {showEditor && <Editor html={html} onChange={setHtml} showPreview={showPreview} />}
          {showPreview && (
            <PreviewPane
              preview={preview}
              showEditor={showEditor}
              device={device}
              deviceIcon={DeviceIcon}
              onCycleDevice={() => setDevice(DEVICE_NEXT[device])}
            />
          )}
        </div>
      </div>
    </div>
  );
}
