// frontend/slices/sections-svelte/sections/PricingSection.svelte
<script lang="ts">
  import { cfgArray, cfgString, isPricingTier, parseConfigObject, type PricingTier } from "../../sections/sections/config";
  import type { LandingSection } from "../../sections/types";
  type Props = { section: LandingSection; tiers: PricingTier[]; featuredBadge?: string; eyebrow?: string; class?: string };
  let { section, tiers, featuredBadge = "Paling populer", eyebrow = "Harga", class: className = "" }: Props = $props();
  let cfg = $derived(parseConfigObject(section.config));
  let list = $derived(cfgArray(cfg, "tiers", isPricingTier) ?? tiers);
  let eyebrowText = $derived(cfgString(cfg, "eyebrow") ?? eyebrow);
</script>
{#if list.length}
<div class={`mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20 ${className}`.trim()}>
  <div class="text-center"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">{eyebrowText}</p><h2 class="mt-2 text-2xl font-semibold tracking-tight">{section.title}</h2>{#if section.subtitle}<p class="mt-2 text-sm text-muted-foreground">{section.subtitle}</p>{/if}</div>
  <div class="mx-auto mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{#each list as tier (tier.name)}<article class={`relative flex h-full flex-col gap-4 rounded-xl border bg-card/50 p-6 ${tier.featured ? "ring-1 ring-foreground/20 shadow-md" : "border-border/60"}`}>{#if tier.featured}<span class="absolute -top-3 left-5 rounded-full bg-primary px-2 py-1 text-xs text-primary-foreground">{featuredBadge}</span>{/if}<div><p class="text-sm font-medium uppercase tracking-wider text-muted-foreground">{tier.name}</p><p class="mt-2"><span class="text-3xl font-semibold">{tier.price}</span>{#if tier.period}<span class="text-sm text-muted-foreground"> {tier.period}</span>{/if}</p>{#if tier.blurb}<p class="mt-2 text-sm text-muted-foreground">{tier.blurb}</p>{/if}</div><ul class="flex-1 space-y-2 text-sm">{#each tier.features as feature (feature)}<li class="flex gap-2"><span>✓</span><span class="text-muted-foreground">{feature}</span></li>{/each}</ul>{#if tier.ctaHref}<a class={`rounded-md px-4 py-2 text-center text-sm font-medium ${tier.featured ? "bg-primary text-primary-foreground" : "border"}`} href={tier.ctaHref}>{tier.ctaLabel ?? "Pilih paket"} →</a>{/if}</article>{/each}</div>
</div>
{/if}

// frontend/slices/pricing-page/views/PricingSection.tsx
import { PricingTierCard } from "../components/PricingTier";
import { PricingFAQ } from "../components/PricingFAQ";
import { cn } from "@/lib/utils";

export type PricingTier = {
  id: string;
  name: string;
  price: string;
  period?: string;
  blurb?: string;
  bullets: string[];
  cta?: { label: string; href: string };
  featured?: boolean;
  badge?: string;
};

export type PricingFAQItem = { q: string; a: string };

export type PricingSectionProps = {
  eyebrow?: string;
  title: string;
  subtitle?: string;
  tiers: PricingTier[];
  columns?: 2 | 3 | 4;
  faq?: PricingFAQItem[];
  faqTitle?: string;
  className?: string;
  /** Override the "featured" visual style. */
  featuredVariant?: "ring" | "scale" | "tint";
};

const colClass: Record<2 | 3 | 4, string> = {
  2: "md:grid-cols-2",
  3: "md:grid-cols-2 lg:grid-cols-3",
  4: "md:grid-cols-2 lg:grid-cols-4",
};

function clampCols(n: number): 2 | 3 | 4 {
  if (n <= 2) return 2;
  if (n === 3) return 3;
  return 4;
}

export function PricingSection({
  eyebrow,
  title,
  subtitle,
  tiers,
  columns,
  faq,
  faqTitle,
  className,
  featuredVariant = "ring",
}: PricingSectionProps) {
  const cols = columns ?? clampCols(tiers.length);
  return (
    <section className={cn("w-full px-4 py-16 md:py-24", className)}>
      <div className="mx-auto max-w-6xl">
        <header className="mx-auto max-w-2xl text-center">
          {eyebrow ? (
            <span className="inline-block rounded-full border px-3 py-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
              {eyebrow}
            </span>
          ) : null}
          <h2 className="mt-4 text-3xl font-bold tracking-tight md:text-4xl lg:text-5xl">
            {title}
          </h2>
          {subtitle ? (
            <p className="mt-4 text-base text-muted-foreground md:text-lg">
              {subtitle}
            </p>
          ) : null}
        </header>

        <div
          className={cn(
            "mt-12 grid grid-cols-1 gap-6 md:mt-16",
            colClass[cols],
          )}
        >
          {tiers.map((tier) => (
            <PricingTierCard
              key={tier.id}
              name={tier.name}
              price={tier.price}
              period={tier.period}
              blurb={tier.blurb}
              bullets={tier.bullets}
              cta={tier.cta}
              featured={tier.featured}
              badge={tier.badge}
              featuredVariant={featuredVariant}
            />
          ))}
        </div>

        {faq && faq.length > 0 ? (
          <div className="mt-20">
            <PricingFAQ items={faq} title={faqTitle} />
          </div>
        ) : null}
      </div>
    </section>
  );
}
