// frontend/slices/image-editor/components/tool-rail.tsx
"use client";

import {
  MousePointer2,
  BoxSelect,
  Brush,
  Eraser,
  Pipette,
  Hand,
  Type,
  Square,
  Circle,
  type LucideIcon,
} from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { useEditor } from "../lib/store";
import { createLayer } from "../lib/model";
import type { Tool } from "../lib/types";
import { ColorSwatches } from "./panels/color-swatches";

// Vertical tool rail. Top group = persistent tool MODES (move/brush/eraser/
// hand). Bottom group = quick "add layer" actions (text / rect / ellipse) that
// drop a new layer centered on the canvas and switch to Move to position it.
export function ToolRail({ orientation = "vertical" }: { orientation?: "vertical" | "horizontal" }) {
  const { tool, setTool, doc, addLayer, fg } = useEditor();
  const horizontal = orientation === "horizontal";
  const tipSide = horizontal ? "top" : "right";

  const modes: { id: Tool; icon: LucideIcon; key: string; label: string }[] = [
    { id: "move", icon: MousePointer2, key: "V", label: "Move" },
    { id: "select", icon: BoxSelect, key: "M", label: "Select" },
    { id: "brush", icon: Brush, key: "B", label: "Brush" },
    { id: "eraser", icon: Eraser, key: "E", label: "Eraser" },
    { id: "eyedropper", icon: Pipette, key: "I", label: "Eyedropper" },
    { id: "hand", icon: Hand, key: "H", label: "Pan" },
  ];

  const center = (w: number, h: number) => ({
    x: Math.round((doc.width - w) / 2),
    y: Math.round((doc.height - h) / 2),
    width: w,
    height: h,
    rotation: 0,
    scaleX: 1,
    scaleY: 1,
  });

  const adds: { icon: LucideIcon; key: string; label: string; run: () => void }[] = [
    { icon: Type, key: "T", label: "Add text", run: () => { addLayer(createLayer("text", { fill: fg, t: center(400, 80) })); setTool("move"); } },
    { icon: Square, key: "R", label: "Add rectangle", run: () => { addLayer(createLayer("shape", { shape: "rect", fillColor: fg, t: center(320, 220) })); setTool("move"); } },
    { icon: Circle, key: "O", label: "Add ellipse", run: () => { addLayer(createLayer("shape", { shape: "ellipse", fillColor: fg, t: center(260, 260) })); setTool("move"); } },
  ];

  const Btn = ({ icon: Icon, label, active, onClick }: { icon: LucideIcon; label: string; active?: boolean; onClick: () => void }) => (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          aria-label={label}
          aria-pressed={active}
          onClick={onClick}
          className={cn(
            "grid size-9 place-items-center rounded-lg transition-colors",
            active ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-accent hover:text-foreground",
          )}
        >
          <Icon className="size-[18px]" />
        </button>
      </TooltipTrigger>
      <TooltipContent side={tipSide}>{label}</TooltipContent>
    </Tooltip>
  );

  return (
    <div
      className={cn(
        "flex shrink-0 items-center gap-1.5 border-border bg-card",
        horizontal
          ? "h-12 w-full flex-row overflow-x-auto border-t px-2"
          : "w-12 flex-col border-r py-2.5",
      )}
    >
      {modes.map((m) => (
        <Btn key={m.id} icon={m.icon} label={`${m.label} (${m.key})`} active={tool === m.id} onClick={() => setTool(m.id)} />
      ))}
      <div className={cn("bg-border", horizontal ? "mx-1 h-6 w-px" : "my-1 h-px w-6")} />
      {adds.map((a) => (
        <Btn key={a.label} icon={a.icon} label={`${a.label} (${a.key})`} onClick={a.run} />
      ))}
      <div className={cn(horizontal ? "ml-auto" : "mt-auto")}>
        <ColorSwatches />
      </div>
    </div>
  );
}

// frontend/slices/image-editor-svelte/components/ToolRail.svelte
<script lang="ts">
  import type { BrowserEditorCore, EditorSnapshot } from "@/features/image-editor/lib/editor-core";
  import { createLayer } from "@/features/image-editor/lib/model";
  import type { Tool } from "@/features/image-editor/lib/types";
  let { editor, snapshot } = $props<{ editor: BrowserEditorCore; snapshot: EditorSnapshot }>();
  const tools:{tool:Tool;label:string;glyph:string}[]=[
    {tool:"move",label:"Move",glyph:"↖"},{tool:"brush",label:"Brush",glyph:"✎"},{tool:"eraser",label:"Eraser",glyph:"⌫"},{tool:"hand",label:"Hand",glyph:"✋"},{tool:"eyedropper",label:"Eyedropper",glyph:"◉"}
  ];
  const center=(w:number,h:number)=>({x:(snapshot.doc.width-w)/2,y:(snapshot.doc.height-h)/2,width:w,height:h,rotation:0,scaleX:1,scaleY:1});
  function add(kind:"text"|"shape"|"paint"|"adjustment",shape?:"rect"|"ellipse"){
    const extra=kind==="text"?{fill:snapshot.fg,t:center(400,90)}:kind==="shape"?{shape,fillColor:snapshot.fg,t:center(shape==="ellipse"?260:320,shape==="ellipse"?260:220)}:kind==="paint"?{t:center(snapshot.doc.width,snapshot.doc.height)}:{};
    editor.addLayer(createLayer(kind,extra)); editor.setTool("move");
  }
</script>
<aside class="flex w-14 shrink-0 flex-col items-center gap-1 border-r bg-muted/20 py-2">
  {#each tools as item (item.tool)}<button class={`grid size-9 place-items-center rounded text-base ${snapshot.tool===item.tool?"bg-primary text-primary-foreground":"hover:bg-muted"}`} title={item.label} aria-label={item.label} aria-pressed={snapshot.tool===item.tool} onclick={()=>editor.setTool(item.tool)}>{item.glyph}</button>{/each}
  <div class="my-1 h-px w-8 bg-border"></div>
  <button class="grid size-9 place-items-center rounded hover:bg-muted" title="Add text" aria-label="Add text" onclick={()=>add("text")}>T</button>
  <button class="grid size-9 place-items-center rounded hover:bg-muted" title="Add rectangle" aria-label="Add rectangle" onclick={()=>add("shape","rect")}>□</button>
  <button class="grid size-9 place-items-center rounded hover:bg-muted" title="Add ellipse" aria-label="Add ellipse" onclick={()=>add("shape","ellipse")}>○</button>
  <button class="grid size-9 place-items-center rounded hover:bg-muted" title="Add paint layer" aria-label="Add paint layer" onclick={()=>add("paint")}>🎨</button>
  <button class="grid size-9 place-items-center rounded hover:bg-muted" title="Add adjustment layer" aria-label="Add adjustment layer" onclick={()=>add("adjustment")}>☼</button>
  <div class="mt-auto flex flex-col items-center gap-1">
    <button class="size-8 rounded border" style={`background:${snapshot.fg}`} title="Foreground" aria-label="Foreground color" onclick={()=>{const c=window.prompt("Foreground color",snapshot.fg);if(c)editor.setFg(c);}}></button>
    <button class="size-6 rounded border" style={`background:${snapshot.bg}`} title="Background" aria-label="Background color" onclick={()=>{const c=window.prompt("Background color",snapshot.bg);if(c)editor.setBg(c);}}></button>
    <button class="text-[10px]" onclick={editor.swapColors}>Swap</button>
  </div>
</aside>
