// frontend/slices/command-menu-svelte/components/SearchModal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import {
    resolveSearchLabels,
    searchView,
    type SearchBindingsBase,
    type SearchHitBase,
    type SearchModalLabels,
  } from "../../command-menu/lib/core";

  let {
    open = $bindable(false),
    onOpenChange,
    labels,
    bindings,
    renderIcon,
  } = $props<{
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    labels?: SearchModalLabels;
    bindings: SearchBindingsBase;
    renderIcon?: Snippet<[SearchHitBase, "page" | "database"]>;
  }>();

  let inputElement = $state<HTMLInputElement>();
  let query = $state("");
  let text = $derived(resolveSearchLabels(labels));
  let view = $derived(searchView(query, bindings));

  function setOpen(value: boolean) {
    open = value;
    onOpenChange?.(value);
  }

  function setQuery(value: string) {
    query = value;
    bindings.onQueryChange(value);
  }

  function select(hit: SearchHitBase, kind: "page" | "database") {
    if (kind === "page") bindings.onSelectPage(hit);
    else bindings.onSelectDatabase(hit);
    setOpen(false);
  }

  $effect(() => {
    if (!open) {
      if (query) query = "";
      return;
    }
    queueMicrotask(() => inputElement?.focus());
  });
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-start justify-center bg-background/70 p-4 pt-[14vh] backdrop-blur-sm" role="presentation" onclick={(event) => event.currentTarget === event.target && setOpen(false)}>
    <div class="w-full max-w-xl overflow-hidden rounded-xl border bg-popover shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="command-search-title" aria-describedby="command-search-description">
      <h2 id="command-search-title" class="sr-only">{text.searchTitle}</h2>
      <p id="command-search-description" class="sr-only">{text.searchDescription}</p>
      <div class="flex items-center gap-2 border-b px-4 py-3">
        <span aria-hidden="true">⌕</span>
        <input
          bind:this={inputElement}
          value={query}
          oninput={(event) => setQuery(event.currentTarget.value)}
          onkeydown={(event) => event.key === "Escape" && setOpen(false)}
          placeholder={text.searchPlaceholder}
          class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        />
        {#if bindings.isLoading}<span class="animate-pulse text-xs text-muted-foreground">…</span>{/if}
        <kbd class="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">{text.escapeHint}</kbd>
      </div>

      <div class="max-h-[420px] overflow-y-auto p-2">
        {#if view.showNoResults}
          <div class="px-3 py-8 text-center text-sm text-muted-foreground">{text.noResults(query)}</div>
        {/if}

        {#if view.recent.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.recentHeading}</div>
          {#each view.recent as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "page")}>
              {#if renderIcon}{@render renderIcon(hit, "page")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if bindings.pages.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.pagesHeading}</div>
          {#each bindings.pages as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "page")}>
              {#if renderIcon}{@render renderIcon(hit, "page")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if bindings.databases.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.databasesHeading}</div>
          {#each bindings.databases as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "database")}>
              {#if renderIcon}{@render renderIcon(hit, "database")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if view.showEmptyHint}
          <div class="px-3 py-8 text-center text-sm text-muted-foreground">{text.emptyHint}</div>
        {/if}
      </div>
    </div>
  </div>
{/if}

// template-base/frontend/slices/notion/slices/command-palette/components/SearchModal.tsx
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Dialog, DialogContent } from "@notion/shared/ui/dialog";
import { useStore } from "@notion/shared/lib/store";
import { useSearch } from "@notion/slices/search";
import { Search, FileText, Clock, Database as DatabaseIcon, Loader2 } from "lucide-react";

interface Props {
  open: boolean;
  onOpenChange: (o: boolean) => void;
}

export function SearchModal({ open, onOpenChange }: Props) {
  const { pages, recents } = useStore();
  const [q, setQ] = useState("");
  const navigate = useNavigate();
  const { isLoading, result } = useSearch(q);
  const recent = !q ? recents.map(id => pages.find(p => p.id === id)).filter(Boolean).slice(0, 5) : [];
  const totalHits = result.pages.length + result.databases.length;

  useEffect(() => { if (!open) setQ(""); }, [open]);

  const goPage = (id: string) => { navigate(`/p/${id}`); onOpenChange(false); };
  const goDb = (id: string) => {
    // Database opens via its host page (full-page DB mode handles render).
    const host = pages.find((p) => p.blocks.some((b) => b.type === "database" && b.databaseId === id));
    if (host) navigate(`/p/${host.id}`);
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="p-0 overflow-hidden max-w-xl gap-0 top-[20%] translate-y-0">
        <div className="flex items-center gap-3 px-4 py-3 border-b border-border">
          <Search className="h-4 w-4 text-muted-foreground" />
          <input
            autoFocus
            value={q}
            onChange={e => setQ(e.target.value)}
            placeholder="Search pages and databases…"
            className="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
          />
          {isLoading && <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />}
          <kbd className="text-[10px] text-muted-foreground border border-border rounded px-1.5 py-0.5">ESC</kbd>
        </div>
        <div className="max-h-[420px] overflow-y-auto p-2">
          {q && !isLoading && totalHits === 0 && (
            <div className="px-3 py-8 text-center text-sm text-muted-foreground">No results for "{q}"</div>
          )}
          {!q && recent.length > 0 && (
            <>
              <SectionHeader icon={<Clock className="h-3 w-3" />}>Recent</SectionHeader>
              {recent.map(p => p && (
                <Row key={p.id} icon={p.icon} title={p.title || "Untitled"} subtitle={preview(p.blocks[0]?.text)} onClick={() => goPage(p.id)} />
              ))}
            </>
          )}
          {result.pages.length > 0 && (
            <>
              <SectionHeader icon={<FileText className="h-3 w-3" />}>Pages</SectionHeader>
              {result.pages.map(p => (
                <Row key={p.id} icon={p.icon} title={p.title || "Untitled"} onClick={() => goPage(p.id)} />
              ))}
            </>
          )}
          {result.databases.length > 0 && (
            <>
              <SectionHeader icon={<DatabaseIcon className="h-3 w-3" />}>Databases</SectionHeader>
              {result.databases.map(d => (
                <Row key={d.id} icon={d.icon} title={d.name || "Untitled"} onClick={() => goDb(d.id)} kind="db" />
              ))}
            </>
          )}
          {!q && recent.length === 0 && (
            <div className="px-3 py-8 text-center text-sm text-muted-foreground">Start typing to search your workspace</div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

function preview(text?: string) {
  if (!text) return "";
  return text.length > 80 ? text.slice(0, 80) + "…" : text;
}

function SectionHeader({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div className="px-3 py-1.5 text-[11px] uppercase tracking-wider text-muted-foreground font-semibold flex items-center gap-1.5">
      {icon} {children}
    </div>
  );
}

function Row({ icon, title, subtitle, onClick, kind = "page" }: { icon: string; title: string; subtitle?: string; onClick: () => void; kind?: "page" | "db" }) {
  const Icon = kind === "db" ? DatabaseIcon : FileText;
  return (
    <button onClick={onClick} className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent transition">
      <span className="text-lg leading-none">{icon}</span>
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-medium">{title}</div>
        {subtitle && <div className="truncate text-xs text-muted-foreground">{subtitle}</div>}
      </div>
      <Icon className="h-3.5 w-3.5 text-muted-foreground" />
    </button>
  );
}
