// frontend/slices/reel-editor/components/ai-panel.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { AI_SUGGESTIONS } from "../lib/ai-edit";

export type AiMessage = { role: "user" | "ai"; text: string };

// AI edit panel: chat-style log + suggestion chips + one-line command input.
export function AiPanel({
  log,
  hasSel,
  onSend,
}: {
  log: AiMessage[];
  hasSel: boolean;
  onSend: (text: string) => void;
}) {
  const [value, setValue] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [log]);

  const send = (raw: string) => {
    const s = raw.trim();
    if (!s) return;
    onSend(s);
    setValue("");
  };

  return (
    <div className="flex h-full min-h-0 flex-col gap-2.5">
      <div className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wide text-muted-foreground">
        <Sparkles className="size-3.5 text-primary" /> AI Assistant
      </div>
      <p className="text-[10.5px] text-muted-foreground">
        {hasSel ? "Acting on the selected clip." : "Select a clip for clip-level edits."}
      </p>

      <div ref={scrollRef} className="flex min-h-0 flex-1 flex-col gap-1.5 overflow-y-auto pr-0.5">
        {log.map((m, i) => (
          <div
            key={i}
            className={cn(
              "max-w-[94%] rounded-xl px-2.5 py-1.5 text-xs leading-snug",
              m.role === "user"
                ? "self-end bg-primary text-primary-foreground"
                : "self-start bg-secondary text-foreground",
            )}
          >
            {m.text}
          </div>
        ))}
      </div>

      <div className="flex flex-wrap gap-1.5">
        {AI_SUGGESTIONS.map((s) => (
          <Button
            key={s}
            type="button"
            variant="ghost"
            onClick={() => send(s)}
            className="h-auto rounded-full border border-border bg-secondary px-2 py-1 text-[10.5px] font-normal text-muted-foreground hover:bg-secondary hover:text-foreground"
          >
            {s}
          </Button>
        ))}
      </div>

      <div className="flex gap-1.5">
        <Input
          value={value}
          placeholder="Describe an edit…"
          onChange={(e) => setValue(e.target.value)}
          onKeyDown={(e) => {
            e.stopPropagation();
            if (e.key === "Enter") send(value);
          }}
        />
        <Button size="sm" onClick={() => send(value)}>
          Go
        </Button>
      </div>
    </div>
  );
}

// frontend/slices/reel-editor-svelte/components/AiPanel.svelte
<script lang="ts">
  import { AI_SUGGESTIONS } from "@/features/reel-editor/lib/ai-edit";
  import type { AiMessage } from "@/features/reel-editor/lib/ai-core";
  let { log, hasSelection, onSend } = $props<{ log: AiMessage[]; hasSelection: boolean; onSend: (text: string) => void }>();
  let value = $state("");
  function send(raw: string) { const text = raw.trim(); if (!text) return; onSend(text); value = ""; }
</script>
<div class="flex h-full min-h-0 flex-col gap-2 p-3">
  <strong class="text-xs uppercase tracking-wide text-muted-foreground">✦ AI Assistant</strong>
  <p class="text-[10px] text-muted-foreground">{hasSelection ? "Acting on the selected clip." : "Select a clip for clip-level edits."}</p>
  <div class="flex min-h-0 flex-1 flex-col gap-1.5 overflow-y-auto">
    {#each log as message, i (i)}
      <div class={`max-w-[94%] rounded-xl px-2.5 py-1.5 text-xs ${message.role === "user" ? "self-end bg-primary text-primary-foreground" : "self-start bg-secondary"}`}>{message.text}</div>
    {/each}
  </div>
  <div class="flex flex-wrap gap-1">{#each AI_SUGGESTIONS as suggestion}<button class="rounded-full border px-2 py-1 text-[10px]" onclick={() => send(suggestion)}>{suggestion}</button>{/each}</div>
  <div class="flex gap-1.5"><input class="min-w-0 flex-1 rounded border bg-background px-2 py-1 text-xs" bind:value={value} placeholder="Describe an edit…" onkeydown={(e) => e.key === "Enter" && send(value)} /><button class="rounded bg-primary px-3 text-xs text-primary-foreground" onclick={() => send(value)}>Go</button></div>
</div>
