// frontend/slices/reel-editor/components/preview-stage.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { type Composition } from "../lib/mock-timeline";
import type { MediaCache } from "../lib/media-cache";
import { drawFrame } from "../lib/draw";

// Real-time preview. A single <canvas> at the comp's native resolution is the
// SAME draw path the exporter uses (drawFrame), so the preview is a faithful
// proof of the render. Real videos are kept in sync with the playhead via the
// shared MediaCache; CSS scales the fixed-resolution canvas into the stage box.
export function PreviewStage({
  comp,
  frame,
  playing,
  monitor,
  cache,
  align = "center",
}: {
  comp: Composition;
  frame: number;
  playing: boolean;
  monitor: boolean;
  cache: MediaCache;
  align?: "center" | "left";
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [tick, setTick] = useState(0);
  const portrait = comp.h > comp.w;

  // Redraw whenever a tracked media element decodes a new frame (load/seek).
  useEffect(() => cache.onFrame(() => setTick((t) => t + 1)), [cache]);

  // Draw on every playhead/comp/playstate change (and media-frame tick).
  useEffect(() => {
    const ctx = canvasRef.current?.getContext("2d");
    if (!ctx) return;
    cache.ensure(comp);
    cache.syncPlayback(comp, frame, playing, monitor);
    drawFrame(ctx, comp, frame, cache);
  }, [comp, frame, playing, monitor, tick, cache]);

  const hasActive = comp.clips.some(
    (c) => c.kind !== "audio" && frame >= c.start && frame < c.start + c.len,
  );

  return (
    <div className={cn("grid min-h-0 flex-1 items-center p-4", align === "left" ? "justify-items-start" : "justify-items-center")}>
      <div
        className="relative overflow-hidden rounded-lg bg-black shadow-2xl"
        style={
          portrait
            ? { height: "100%", aspectRatio: `${comp.w}/${comp.h}`, maxWidth: "100%" }
            : { width: "100%", aspectRatio: `${comp.w}/${comp.h}`, maxHeight: "100%", maxWidth: "42rem" }
        }
      >
        <canvas
          ref={canvasRef}
          width={comp.w}
          height={comp.h}
          className="absolute inset-0 h-full w-full"
        />
        {!hasActive && (
          <div className="absolute inset-0 grid place-items-center text-sm text-white/30">
            No clip at playhead
          </div>
        )}
      </div>
    </div>
  );
}

// frontend/slices/reel-editor-svelte/components/PreviewStage.svelte
<script lang="ts">
  import type { Clip, Composition } from "@/features/reel-editor/lib/mock-timeline";
  import type { MediaCache } from "@/features/reel-editor/lib/media-cache";
  import { drawFrame } from "@/features/reel-editor/lib/draw";

  let { comp, frame, playing, monitor, cache } = $props<{
    comp: Composition;
    frame: number;
    playing: boolean;
    monitor: boolean;
    cache: MediaCache;
  }>();
  let canvas = $state<HTMLCanvasElement>();
  let tick = $state(0);
  let hasActive = $derived(comp.clips.some((clip: Clip) => clip.kind !== "audio" && frame >= clip.start && frame < clip.start + clip.len));

  $effect(() => {
    const current = canvas;
    comp; frame; playing; monitor; tick;
    if (!current) return;
    const ctx = current.getContext("2d");
    if (!ctx) return;
    cache.ensure(comp);
    cache.syncPlayback(comp, frame, playing, monitor);
    drawFrame(ctx, comp, frame, cache);
  });

  $effect(() => cache.onFrame(() => tick += 1));
</script>

<div class="grid min-h-0 flex-1 place-items-center overflow-hidden bg-black/5 p-3">
  <div class="relative max-h-full max-w-full overflow-hidden rounded-lg bg-black shadow-2xl" style={`aspect-ratio:${comp.w}/${comp.h};${comp.h > comp.w ? "height:100%" : "width:100%;max-width:48rem"}`}>
    <canvas bind:this={canvas} width={comp.w} height={comp.h} class="absolute inset-0 h-full w-full"></canvas>
    {#if !hasActive}<div class="absolute inset-0 grid place-items-center text-sm text-white/35">No clip at playhead</div>{/if}
  </div>
</div>
