// frontend/slices/create-your-mcp-svelte/views/McpSetupPanel.svelte
<script lang="ts">
  import { copyToClipboard, type SetupField } from "../../create-your-mcp/views/mcp-admin-helpers";

  let { fields }: { fields: SetupField[] } = $props();
  let open = $state(true);
</script>

<section class="rounded-lg border-2 border-foreground bg-card">
  <button
    type="button"
    class="flex w-full items-center justify-between border-b-2 border-foreground px-5 py-3 text-left hover:bg-foreground hover:text-background"
    aria-expanded={open}
    onclick={() => (open = !open)}
  >
    <span class="text-sm font-bold uppercase tracking-widest">
      Setup an AI client (ChatGPT / Claude / Cursor)
    </span>
    <span class="text-xs">{open ? "▼ Hide" : "▶ Show"}</span>
  </button>

  {#if open}
    <div class="space-y-3 p-5">
      <p class="text-xs text-muted-foreground">
        Paste these values into your AI client's connector form. Authentication = OAuth.
      </p>
      <dl class="grid gap-2 sm:grid-cols-[200px_1fr]">
        {#each fields as field (field.label)}
          <dt class="py-1.5 text-xs uppercase tracking-widest text-muted-foreground">
            {field.label}
          </dt>
          <dd class="flex items-center justify-between gap-2 rounded-md border border-foreground/20 bg-background px-3 py-1.5">
            <code class="break-all font-mono text-xs">{field.value}</code>
            {#if field.kind === "copyable"}
              <button
                type="button"
                class="shrink-0 border border-foreground/40 px-2 py-0.5 text-[10px] uppercase tracking-widest hover:bg-foreground hover:text-background"
                onclick={() => void copyToClipboard(field.value)}
              >Copy</button>
            {/if}
          </dd>
        {/each}
      </dl>
      <div class="space-y-1 border-t border-foreground/20 pt-3 text-xs text-muted-foreground">
        <p>Discovery JSON: <code>/.well-known/oauth-authorization-server</code></p>
        <p>Tokens default to 1-year TTL. Revoke cuts access on the next call.</p>
      </div>
    </div>
  {/if}
</section>

// migration/superspace/frontend/slices/create-your-mcp/views/McpSetupPanel.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { copyToClipboard, type SetupField } from "./mcp-admin-helpers";

export function McpSetupPanel({ fields }: { fields: SetupField[] }) {
  const [setupOpen, setSetupOpen] = useState(true);

  return (
    <section className="border-2 border-foreground rounded-lg bg-card">
      <Button
        type="button"
        variant="ghost"
        onClick={() => setSetupOpen((v) => !v)}
        className="h-auto w-full justify-between rounded-none px-5 py-3 border-b-2 border-foreground hover:bg-foreground hover:text-background"
        aria-expanded={setupOpen}
      >
        <span className="text-sm uppercase tracking-widest font-bold">
          Setup an AI client (ChatGPT / Claude / Cursor)
        </span>
        <span className="text-xs">{setupOpen ? "▼ Hide" : "▶ Show"}</span>
      </Button>
      {setupOpen && (
        <div className="p-5 space-y-3">
          <p className="text-xs text-muted-foreground">
            Paste the values below into your AI client's connector form
            (e.g. ChatGPT Settings → Connectors → New). Authentication = OAuth.
          </p>
          <dl className="grid gap-2 sm:grid-cols-[200px_1fr]">
            {fields.map((f) => (
              <div key={f.label} className="contents">
                <dt className="text-xs uppercase tracking-widest text-muted-foreground py-1.5">
                  {f.label}
                </dt>
                <dd className="flex items-center justify-between gap-2 border border-foreground/20 rounded-md bg-background px-3 py-1.5">
                  <code className="text-xs font-mono break-all">{f.value}</code>
                  {f.kind === "copyable" && (
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => copyToClipboard(f.value)}
                      className="h-auto shrink-0 px-2 py-0.5 text-[10px] uppercase tracking-widest border-foreground/40 hover:bg-foreground hover:text-background"
                    >
                      Copy
                    </Button>
                  )}
                </dd>
              </div>
            ))}
          </dl>
          <div className="pt-3 border-t border-foreground/20 text-xs text-muted-foreground space-y-1">
            <p>
              Discovery JSON (optional auto-fill):{" "}
              <code>/.well-known/oauth-authorization-server</code>
            </p>
            <p>
              Tokens default to 1-year TTL. Revoke cuts access immediately on
              the next call.
            </p>
          </div>
        </div>
      )}
    </section>
  );
}
