// frontend/slices/settings-svelte/variants/appearance/components/AppearancePanel.svelte
<script lang="ts">
  import type {
    AppearanceAdapter,
    SegSetting,
  } from "@/features/settings/variants/appearance/lib/types";
  import AccentSwatches from "./AccentSwatches.svelte";
  import Segmented from "./Segmented.svelte";
  import SettingsRow from "./SettingsRow.svelte";
  import SettingsSection from "./SettingsSection.svelte";

  let { appearance: a } = $props<{ appearance: AppearanceAdapter }>();
</script>

{#snippet segRow(label: string, seg: SegSetting)}
  <SettingsRow {label}>
    <Segmented options={seg.options} value={seg.value} onChange={seg.onChange} />
  </SettingsRow>
{/snippet}

<div class="space-y-5">
  <SettingsSection icon="◐" title="Appearance">
    {#if a.style}{@render segRow("Style", a.style)}{/if}
    {#if a.theme}{@render segRow("Mode", a.theme)}{/if}
    {#if a.accent}
      <SettingsRow label="Accent">
        <AccentSwatches value={a.accent.value} options={a.accent.options} onSelect={a.accent.onChange} />
      </SettingsRow>
    {/if}
    {#if a.wallpaper}{@render segRow("Wallpaper", a.wallpaper)}{/if}
    {#if a.reduceTransparency}
      <SettingsRow label="Reduce transparency">
        <input
          type="checkbox"
          checked={a.reduceTransparency.value}
          onchange={(event) => a.reduceTransparency?.onChange(event.currentTarget.checked)}
          class="size-4 accent-[var(--primary)]"
        />
      </SettingsRow>
    {/if}
  </SettingsSection>

  {#if a.shellDesktop || a.shellMobile}
    <SettingsSection icon="▦" title="Shell">
      {#if a.shellDesktop}{@render segRow("Desktop layout", a.shellDesktop)}{/if}
      {#if a.shellMobile}{@render segRow("Mobile layout", a.shellMobile)}{/if}
    </SettingsSection>
  {/if}

  {#if a.device}
    <SettingsSection icon="▣" title="Display">
      {@render segRow("Device", a.device)}
    </SettingsSection>
  {/if}
</div>

// frontend/slices/settings/variants/appearance/components/appearance-panel.tsx
"use client";

import { Layers, Monitor, Palette } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { Segmented } from "./segmented";
import { SettingsSection } from "./section";
import { SettingsRow } from "./row";
import { AccentSwatches } from "./accent-swatches";
import type { AppearanceAdapter, SegSetting } from "../lib/types";

function SegRow({ label, seg }: { label: string; seg: SegSetting }) {
  return (
    <SettingsRow label={label}>
      <Segmented options={seg.options} value={seg.value} onChange={seg.onChange} className="w-full flex-wrap sm:w-auto" />
    </SettingsRow>
  );
}

// Generic shell appearance UI — Appearance group + an optional Display group for
// the device override. Everything it shows comes from the injected adapter, so the
// panel itself is brand-free and lift-ready.
export function AppearancePanel({ appearance: a }: { appearance: AppearanceAdapter }) {
  return (
    <>
      <SettingsSection icon={<Palette />} title="Appearance">
        {a.style && <SegRow label="Style" seg={a.style} />}
        {a.theme && <SegRow label="Mode" seg={a.theme} />}
        {a.accent && (
          <SettingsRow label="Accent">
            <AccentSwatches value={a.accent.value} options={a.accent.options} onSelect={a.accent.onChange} />
          </SettingsRow>
        )}
        {a.wallpaper && <SegRow label="Wallpaper" seg={a.wallpaper} />}
        {a.reduceTransparency && (
          <SettingsRow label="Reduce transparency">
            <Switch checked={a.reduceTransparency.value} onCheckedChange={a.reduceTransparency.onChange} />
          </SettingsRow>
        )}
      </SettingsSection>

      {(a.shellDesktop || a.shellMobile) && (
        <SettingsSection icon={<Layers />} title="Shell">
          {a.shellDesktop && <SegRow label="Desktop layout" seg={a.shellDesktop} />}
          {a.shellMobile && <SegRow label="Mobile layout" seg={a.shellMobile} />}
        </SettingsSection>
      )}

      {a.device && (
        <SettingsSection icon={<Monitor />} title="Display">
          <SegRow label="Device" seg={a.device} />
        </SettingsSection>
      )}
    </>
  );
}
