// frontend/slices/glass-desktop-svelte/components/WidgetCanvas.svelte
<script lang="ts">
  import { GRID, SIZE_CELLS } from "../../glass-desktop/config/constants";
  import { resolveWidgetSize } from "../../glass-desktop/lib/layout-core";
  import { widgetCatalog } from "../../glass-desktop/lib/widget-catalog";
  import { cellToPx } from "../../glass-desktop/utils/grid";
  import type { WidgetInstance, WidgetSize } from "../../glass-desktop/types";
  import WidgetCard from "./WidgetCard.svelte";
  let { space, instances, editing = false, onMove, onRemove, onResize }: { space: 0|1; instances: WidgetInstance[]; editing?: boolean; onMove: (id:string,col:number,row:number)=>void; onRemove:(id:string)=>void; onResize:(id:string,size:WidgetSize)=>void } = $props();
  let visible = $derived(instances.filter((item) => item.space === space));
  let maxBottom = $derived(visible.reduce((max, item) => Math.max(max, item.row + SIZE_CELLS[resolveWidgetSize(item)].r), 1));
  let drag = $state<{id:string;x:number;y:number;col:number;row:number;pointer:number}|null>(null);
  function start(event: PointerEvent, item: WidgetInstance) { if (!editing || (event.target as HTMLElement).closest("button")) return; const el=event.currentTarget as HTMLElement; el.setPointerCapture(event.pointerId); drag={id:item.instanceId,x:event.clientX,y:event.clientY,col:item.col,row:item.row,pointer:event.pointerId}; }
  function finish(event: PointerEvent) { if (!drag || event.pointerId !== drag.pointer) return; const stepX=GRID.cellW+GRID.gap, stepY=GRID.cellH+GRID.gap; onMove(drag.id, drag.col+Math.round((event.clientX-drag.x)/stepX), drag.row+Math.round((event.clientY-drag.y)/stepY)); drag=null; }
  function keyMove(event: KeyboardEvent, item: WidgetInstance) { if (!editing) return; const delta: Record<string,[number,number]> = { ArrowLeft:[-1,0], ArrowRight:[1,0], ArrowUp:[0,-1], ArrowDown:[0,1] }; const d=delta[event.key]; if (!d) return; event.preventDefault(); onMove(item.instanceId,item.col+d[0],item.row+d[1]); }
</script>
<div class="scroll"><div class="canvas" style:width={`${GRID.cols*GRID.cellW+(GRID.cols-1)*GRID.gap}px`} style:min-height={`${Math.max(maxBottom*(GRID.cellH+GRID.gap)-GRID.gap,GRID.cellH)}px`}>
{#each visible as item (item.instanceId)}
  {@const descriptor = widgetCatalog[item.widgetId]}
  {@const size = resolveWidgetSize(item)}
  {@const cells = SIZE_CELLS[size]}
  {@const rect = cellToPx(item.col,item.row,cells.c,cells.r)}
  {#if descriptor}<div class:editing class="item" role="button" tabindex={editing ? 0 : -1} aria-label={`Move ${descriptor.title}`} data-instance={item.instanceId} style:left={`${rect.left}px`} style:top={`${rect.top}px`} style:width={`${rect.width}px`} style:height={`${rect.height}px`} onpointerdown={(e)=>start(e,item)} onpointerup={finish} onpointercancel={() => (drag=null)} onkeydown={(e)=>keyMove(e,item)}><WidgetCard instance={item} {descriptor} pill={cells.r===1} {editing} {onRemove} {onResize}/></div>{/if}
{/each}
</div></div>
<style>
  .scroll{height:100%;overflow:auto;padding:1rem 3rem 4rem}.canvas{position:relative;margin:0 auto}.item{position:absolute;transition:left var(--duration-settle) var(--ease-settle),top var(--duration-settle) var(--ease-settle);touch-action:none}.item.editing{cursor:grab}.item.editing:active{cursor:grabbing;z-index:20;filter:brightness(1.06)}@media(max-width:760px){.scroll{padding-inline:1rem}}
</style>

// frontend/slices/glass-desktop/components/engine/widget-canvas.tsx
"use client";

// glass-desktop — WidgetCanvas (Build Plan §T7). Renders ONE space: resolves each
// instance against the widget registry, dense-packs it onto the 8-col grid, and
// wraps it in the glass shell + a per-widget error boundary. Unknown widgetId ->
// a "missing widget" tile, never a crash. Drag is delegated to useDragWidget; in
// edit mode each widget gains remove (×) + resize affordances backed by useLayout.
import { useCallback, useRef } from "react";
import { widgetRegistry } from "@/features/glass-desktop/lib/widget-registry";
import { GRID, SIZE_CELLS, Z } from "@/features/glass-desktop/config/constants";
import { resolveWidgetSize } from "@/features/glass-desktop/lib/layout-core";
import { cellToPx, packLayout, type Pinned } from "@/features/glass-desktop/utils/grid";
import { WidgetShell } from "@/features/glass-desktop/components/engine/widget-shell";
import { WidgetErrorBoundary } from "@/features/glass-desktop/components/engine/widget-error-boundary";
import { useDragWidget } from "@/features/glass-desktop/hooks/use-drag-widget";
import type { WidgetInstance, WidgetSize } from "@/features/glass-desktop/types";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const SIZE_CYCLE: WidgetSize[] = ["SP", "S", "WP", "W", "L"];



export interface WidgetCanvasProps {
  space: 0 | 1;
  instances: WidgetInstance[];
  editMode?: boolean;
  onMove: (instanceId: string, col: number, row: number) => void;
  onRemove: (instanceId: string) => void;
  onResize: (instanceId: string, size: WidgetSize) => void;
}

export function WidgetCanvas({ space, instances, editMode = false, onMove, onRemove, onResize }: WidgetCanvasProps) {
  const ghostRef = useRef<HTMLDivElement | null>(null);

  const sized = instances
    .filter((i) => i.space === space)
    .map((inst) => {
      const def = widgetRegistry[inst.widgetId];
      const size = resolveWidgetSize(inst);
      return { inst, def, size, cells: SIZE_CELLS[size] };
    });

  // Dense-pack, keeping any already-valid position pinned (utils/grid is the SSOT).
  const pinned: Pinned = {};
  for (const s of sized) {
    const { col, row } = s.inst;
    if (Number.isInteger(col) && col >= 0 && Number.isInteger(row) && row >= 0 && col + s.cells.c <= GRID.cols) {
      pinned[s.inst.instanceId] = { col, row };
    }
  }
  const items = sized.map((s) => ({ id: s.inst.instanceId, c: s.cells.c, r: s.cells.r }));
  const placements = packLayout(items, GRID.cols, pinned);

  // Stable sizeOf for the drag hook (reads latest spans without re-subscribing).
  const spanRef = useRef(new Map<string, { c: number; r: number }>());
  spanRef.current = new Map(sized.map((s) => [s.inst.instanceId, s.cells]));
  const sizeOf = useCallback((id: string) => spanRef.current.get(id) ?? { c: 1, r: 2 }, []);
  const drag = useDragWidget({ enabled: editMode, sizeOf, onDrop: onMove, ghostRef });

  let maxBottom = 1;
  for (const s of sized) maxBottom = Math.max(maxBottom, placements[s.inst.instanceId].row + s.cells.r);
  const width = GRID.cols * GRID.cellW + (GRID.cols - 1) * GRID.gap;
  const height = maxBottom * (GRID.cellH + GRID.gap) - GRID.gap;

  return (
    <div className="relative mx-auto" style={{ width, minHeight: Math.max(height, GRID.cellH) }}>
      {/* Single snap-target ghost, positioned imperatively by the drag hook. */}
      <div
        ref={ghostRef}
        aria-hidden
        style={{
          position: "absolute",
          display: "none",
          pointerEvents: "none",
          zIndex: Z.drag - 1,
          border: "1.5px dashed var(--color-hairline-hover)",
          background: "var(--color-glass-lo)",
        }}
      />
      {sized.map(({ inst, def, size, cells }) => {
        const p = placements[inst.instanceId];
        const rect = cellToPx(p.col, p.row, cells.c, cells.r);
        const pill = cells.r === 1;
        const Widget = def?.component;
        return (
          <div
            key={inst.instanceId}
            data-instance={inst.instanceId}
            onPointerDown={editMode ? (e) => drag.onPointerDown(inst.instanceId, e) : undefined}
            className={cn(
              "absolute",
              editMode && "cursor-grab",
              "motion-safe:transition-[left,top]",
              "motion-safe:[transition-duration:var(--duration-settle)]",
              "motion-safe:[transition-timing-function:var(--ease-settle)]",
            )}
            style={{
              left: rect.left,
              top: rect.top,
              width: rect.width,
              height: rect.height,
              zIndex: Z.widget,
              touchAction: editMode ? "none" : undefined,
            }}
          >
            <WidgetErrorBoundary instanceId={inst.instanceId}>
              <WidgetShell title={def?.title ?? "Missing widget"} pill={pill} className="h-full w-full">
                {Widget ? (
                  <Widget instanceId={inst.instanceId} {...def?.defaultProps} {...inst.props} />
                ) : (
                  <div className="flex h-full flex-col items-center justify-center gap-1 text-center">
                    <span className="text-xs font-medium uppercase tracking-wide" style={{ color: "var(--color-ink-mid)" }}>
                      Missing widget
                    </span>
                    <span
                      className="max-w-full truncate text-[11px]"
                      style={{ color: "var(--color-ink-low)", fontFamily: "var(--font-numeric)" }}
                      title={inst.widgetId}
                    >
                      {inst.widgetId}
                    </span>
                  </div>
                )}
                {editMode ? (
                  <div className="absolute right-1.5 top-1.5 z-10 flex gap-1">
                    <Button
                      type="button"
                      size="icon"
                      variant="ghost"
                      aria-label={`Resize ${def?.title ?? inst.widgetId}`}
                      className="size-6 rounded-full [background:var(--color-glass-solid)]"
                      onClick={() => onResize(inst.instanceId, SIZE_CYCLE[(SIZE_CYCLE.indexOf(size) + 1) % SIZE_CYCLE.length])}
                    >
                      <span aria-hidden style={{ color: "var(--color-ink-mid)" }}>
                        ⤢
                      </span>
                    </Button>
                    <Button
                      type="button"
                      size="icon"
                      variant="ghost"
                      aria-label={`Remove ${def?.title ?? inst.widgetId}`}
                      className="size-6 rounded-full [background:var(--color-glass-solid)]"
                      onClick={() => onRemove(inst.instanceId)}
                    >
                      <span aria-hidden style={{ color: "var(--color-accent-coral)" }}>
                        ×
                      </span>
                    </Button>
                  </div>
                ) : null}
              </WidgetShell>
            </WidgetErrorBoundary>
          </div>
        );
      })}
    </div>
  );
}
