// frontend/slices/convex-auth-svelte/components/AuthCard.svelte
<script lang="ts">
  import { createMockAuthFlow } from "../../convex-auth/lib/flow-core";
  import { DEFAULT_LABELS } from "../../convex-auth/lib/labels";
  import MagicLinkForm from "./MagicLinkForm.svelte";
  import PasswordBlock from "./PasswordBlock.svelte";
  import PhoneForm from "./PhoneForm.svelte";
  import type { AuthCardProps, AuthMethod, AuthResult, SignInLabels } from "../types";

  let {
    methods = ["password", "google"],
    defaultPasswordMode = "signin",
    title,
    description,
    labels: overrides,
    footer,
    class: className = "",
    forgotPasswordHref = "/forgot-password",
    flow,
    onGithub = async () => ({ ok: true }),
    onPhoneSend = async () => ({ ok: true }),
    onPhoneVerify = async () => ({ ok: true }),
    onSuccess,
  }: AuthCardProps = $props();

  const mock = createMockAuthFlow();
  let auth = $derived({ ...mock, ...flow });
  let labels = $derived<SignInLabels>({ ...DEFAULT_LABELS, ...overrides });
  let error = $state("");
  let oauthPending = $state<AuthMethod | null>(null);
  let has = (method: AuthMethod) => methods.includes(method);
  let oauth = $derived(has("google") || has("github"));
  let fieldMethod = $derived(has("password") || has("magic-link") || has("phone"));

  async function handle(result: AuthResult, method: AuthMethod) {
    if (result.ok) {
      error = "";
      await onSuccess?.(method);
    } else {
      error = result.error || labels.genericError;
    }
  }

  async function runOauth(method: "google" | "github") {
    oauthPending = method;
    try {
      const result = method === "google" ? await auth.signInWithGoogle() : await onGithub();
      await handle(result, method);
    } finally {
      oauthPending = null;
    }
  }
</script>

<section class={`rounded-xl border bg-card text-card-foreground shadow-sm ${className}`.trim()}>
  <header class="space-y-1.5 p-6 pb-4">
    <h2 class="text-2xl font-semibold leading-none tracking-tight">{title ?? labels.title}</h2>
    <p class="text-sm text-muted-foreground">{description ?? labels.description}</p>
  </header>
  <div class="space-y-4 px-6 pb-6">
    {#if error}<div role="alert" class="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</div>{/if}
    {#if oauth}
      <div class="space-y-2">
        {#if has("google")}<button type="button" class="h-10 w-full rounded-md border bg-background px-4 text-sm font-medium hover:bg-muted disabled:opacity-50" disabled={oauthPending !== null} onclick={() => runOauth("google")}>{oauthPending === "google" ? labels.googleButtonLoading : labels.googleButton}</button>{/if}
        {#if has("github")}<button type="button" class="h-10 w-full rounded-md border bg-background px-4 text-sm font-medium hover:bg-muted disabled:opacity-50" disabled={oauthPending !== null} onclick={() => runOauth("github")}>{oauthPending === "github" ? "Redirecting to GitHub…" : "Continue with GitHub"}</button>{/if}
      </div>
    {/if}
    {#if oauth && fieldMethod}<div class="relative flex items-center py-1"><span class="h-px flex-1 bg-border"></span><span class="px-2 text-xs uppercase text-muted-foreground">{labels.divider}</span><span class="h-px flex-1 bg-border"></span></div>{/if}
    {#if has("password")}<PasswordBlock labels={labels} flow={auth} {forgotPasswordHref} {defaultPasswordMode} onResult={(result) => handle(result, "password")} />{/if}
    {#if has("magic-link")}<MagicLinkForm labels={labels} send={auth.sendMagicLink} onResult={(result) => handle(result, "magic-link")} />{/if}
    {#if has("phone")}<PhoneForm onSend={onPhoneSend} onVerify={onPhoneVerify} onResult={(result) => handle(result, "phone")} />{/if}
    {#if has("anonymous")}<button type="button" class="h-10 w-full rounded-md border bg-background px-4 text-sm font-medium hover:bg-muted" onclick={async () => handle(await auth.signInAnonymous(), "anonymous")}>{labels.anonymousButton}</button>{/if}
  </div>
  {#if footer}<footer class="px-6 pb-6 text-center text-sm text-muted-foreground">{@render footer()}</footer>{/if}
</section>

// frontend/slices/convex-auth/components/AuthCard.tsx
"use client";

/**
 * AuthCard — presentational, props-driven sign-in card.
 *
 * One component, many surfaces: pick which sign-in methods render via the
 * `methods` prop (order = render order), then call it as many times as you
 * like with different props. Pure presentation — every method takes an
 * async handler returning `AuthResult`; handlers default to a mock that
 * resolves `{ ok: true }` so the card is fully interactive in previews and
 * Storybook with zero wiring. In a real app, pass handlers wired to
 * `useAuthFlow()` (or render the full-page `<SignInPage>` instead).
 *
 * Layout: OAuth buttons (google/github) on top → divider → one field
 * method (password tabs / magic-link / phone OTP) → optional anonymous.
 */

import { useState, type ReactNode } from "react";

import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Card, CardContent, CardDescription, CardHeader, CardTitle,
} from "@/components/ui/card";

import { GoogleButton, MagicLinkForm, AnonymousButton } from "./auth-buttons";
import {
  Divider, GithubButton, PasswordBlock, PhoneForm,
  type PasswordMode, type PasswordSubmit,
} from "./auth-card-blocks";
import { DEFAULT_LABELS } from "../lib/labels";
import type { AuthMethod, AuthResult, SignInLabels } from "../types";
export type { AuthMethod } from "../types";


const ok: () => Promise<AuthResult> = async () => ({ ok: true });

export interface AuthCardProps {
  /** Methods to render, in order. Default: `["password", "google"]`. */
  methods?: ReadonlyArray<AuthMethod>;
  /** Password block initial tab. */
  defaultPasswordMode?: PasswordMode;
  title?: string;
  description?: string;
  labels?: Partial<SignInLabels>;
  footer?: ReactNode;
  className?: string;
  /** Forgot-password link target; `null` hides it. */
  forgotPasswordHref?: string | null;
  // Handlers — all optional; default to a mock that resolves ok.
  onGoogle?: () => Promise<AuthResult>;
  onGithub?: () => Promise<AuthResult>;
  onMagicLink?: (email: string) => Promise<AuthResult>;
  onPassword?: PasswordSubmit;
  onPhoneSend?: (phone: string) => Promise<AuthResult>;
  onPhoneVerify?: (phone: string, code: string) => Promise<AuthResult>;
  onAnonymous?: () => Promise<AuthResult>;
  /** Fired after any successful method. */
  onSuccess?: (method: AuthMethod) => void;
}

export function AuthCard({
  methods = ["password", "google"],
  defaultPasswordMode = "signin",
  title, description, labels: overrides, footer, className,
  forgotPasswordHref = "/forgot-password",
  onGoogle = ok, onGithub = ok, onMagicLink, onPassword,
  onPhoneSend, onPhoneVerify, onAnonymous = ok, onSuccess,
}: AuthCardProps) {
  const labels: SignInLabels = { ...DEFAULT_LABELS, ...overrides };
  const [error, setError] = useState("");
  const has = (m: AuthMethod) => methods.includes(m);

  const handle = (r: AuthResult, m: AuthMethod) => {
    if (r.ok) { setError(""); onSuccess?.(m); } else setError(r.error || labels.genericError);
  };

  const oauth = has("google") || has("github");
  const fieldMethod = has("password") || has("magic-link") || has("phone");

  return (
    <Card className={className}>
      <CardHeader>
        <CardTitle>{title ?? labels.title}</CardTitle>
        <CardDescription>{description ?? labels.description}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {error ? (
          <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>
        ) : null}

        {oauth ? (
          <div className="space-y-2">
            {has("google") ? (
              <GoogleButton flow={onGoogle} labels={labels} onResult={(r) => handle(r, "google")} />
            ) : null}
            {has("github") ? (
              <GithubButton flow={onGithub} onResult={(r) => handle(r, "github")} />
            ) : null}
          </div>
        ) : null}

        {oauth && fieldMethod ? <Divider text={labels.divider} /> : null}

        {has("password") ? (
          <PasswordBlock
            labels={labels}
            forgotPasswordHref={forgotPasswordHref}
            defaultMode={defaultPasswordMode}
            onSubmit={onPassword ?? ok}
            onResult={(r) => handle(r, "password")}
          />
        ) : null}

        {has("magic-link") ? (
          <MagicLinkForm
            send={onMagicLink ?? (async () => ({ ok: true }))}
            labels={labels}
            onResult={(r) => handle(r, "magic-link")}
          />
        ) : null}

        {has("phone") ? (
          <PhoneForm
            onSend={onPhoneSend ?? (async () => ({ ok: true }))}
            onVerify={onPhoneVerify ?? (async () => ({ ok: true }))}
            onResult={(r) => handle(r, "phone")}
          />
        ) : null}

        {has("anonymous") ? (
          <div className={fieldMethod ? "border-t pt-4" : undefined}>
            <AnonymousButton flow={onAnonymous} labels={labels} onResult={(r) => handle(r, "anonymous")} />
          </div>
        ) : null}
      </CardContent>

      {footer ? (
        <div className="px-6 pb-6 text-center text-sm text-muted-foreground">{footer}</div>
      ) : null}
    </Card>
  );
}
