// frontend/slices/sections/views/LandingView.tsx
"use client";

import * as React from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { LandingFieldsForm } from "../components/LandingFieldsForm";
import { useLandingStore } from "../landing-context";
import { blankSection, LANDING_KIND_LABEL, moveLandingSection, sortedLandingSections, visibleLandingCount } from "../lib/core";
import type { LandingSection } from "../types";

export function LandingView() {
  const store = useLandingStore();
  const items = sortedLandingSections(store.items);
  const [openId, setOpenId] = React.useState<string | null>(null);
  const entity = items.find((item) => item.id === openId) ?? null;
  const [draft, setDraft] = React.useState<LandingSection | null>(null);
  React.useEffect(() => setDraft(entity ? structuredClone(entity) : null), [entity]);

  const positions = React.useMemo(() => Array.from({ length: Math.max(1, items.length) }, (_, i) => i + 1), [items.length]);
  function createNew() {
    const next = blankSection(items.at(-1)?.order ?? 0);
    store.create(next);
    setOpenId(next.id);
  }
  function patch(key: keyof LandingSection, value: unknown) {
    setDraft((current) => current ? ({ ...current, [key]: value } as LandingSection) : current);
  }
  function save() {
    if (!draft) return;
    const { id, ...next } = draft;
    store.update(id, next);
    setOpenId(null);
  }

  return <div className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3">
      <div><h1 className="text-xl font-semibold tracking-tight sm:text-2xl">Landing sections</h1><p className="text-xs text-muted-foreground">{visibleLandingCount(items)}/{items.length} sections visible</p></div>
      <div className="flex gap-2"><Button asChild size="sm" variant="outline"><a href={store.publicBase}>View public</a></Button><Button size="sm" onClick={createNew}>New section</Button></div>
    </div>
    <div className="overflow-x-auto rounded-lg border bg-card">
      <Table>
        <TableHeader><TableRow><TableHead>Title</TableHead><TableHead className="hidden md:table-cell">Kind</TableHead><TableHead className="hidden md:table-cell">#</TableHead><TableHead>Visible</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader>
        <TableBody>
          {items.map((item, index) => <TableRow key={item.id} className="cursor-pointer" onClick={() => setOpenId(item.id)}>
            <TableCell><div className="font-medium">{item.title}</div><div className="max-w-sm truncate text-xs text-muted-foreground">{item.subtitle}</div></TableCell>
            <TableCell className="hidden md:table-cell"><Badge variant="outline">{LANDING_KIND_LABEL[item.kind]}</Badge></TableCell>
            <TableCell className="hidden font-mono text-xs md:table-cell">{String(item.order).padStart(2, "0")}</TableCell>
            <TableCell><Badge variant={item.enabled ? "default" : "outline"}>{item.enabled ? "on" : "off"}</Badge></TableCell>
            <TableCell onClick={(event) => event.stopPropagation()}><div className="flex justify-end gap-1"><Button size="icon" variant="outline" disabled={index === 0} onClick={() => moveLandingSection(store, item.id, -1)}>↑</Button><Button size="icon" variant="outline" disabled={index === items.length - 1} onClick={() => moveLandingSection(store, item.id, 1)}>↓</Button><Button size="sm" variant="ghost" onClick={() => setOpenId(item.id)}>Edit</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => store.remove(item.id)}>Delete</Button></div></TableCell>
          </TableRow>)}
          {items.length === 0 ? <TableRow><TableCell colSpan={5} className="py-8 text-center text-xs text-muted-foreground">No landing sections yet.</TableCell></TableRow> : null}
        </TableBody>
      </Table>
    </div>

    <Dialog open={Boolean(openId)} onOpenChange={(open) => { if (!open) setOpenId(null); }}>
      <DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader><DialogTitle>Edit section</DialogTitle><DialogDescription>Content, ordering, visibility, images, and renderer config.</DialogDescription></DialogHeader>
        {draft ? <LandingFieldsForm value={draft} onChange={patch} positions={positions} /> : null}
        <DialogFooter>{draft ? <Button variant="outline" className="mr-auto text-destructive" onClick={() => { store.remove(draft.id); setOpenId(null); }}>Delete</Button> : null}<Button variant="outline" onClick={() => setOpenId(null)}>Cancel</Button><Button onClick={save}>Save</Button></DialogFooter>
      </DialogContent>
    </Dialog>
  </div>;
}

// frontend/slices/sections-svelte/components/LandingView.svelte
<script lang="ts">
  import {
    blankSection,
    LANDING_KIND_LABEL,
    moveLandingSection,
    sortedLandingSections,
    visibleLandingCount,
    type LandingStore,
  } from "../../sections/lib/core";
  import { useLandingStore } from "../lib/context";

  type Props = { store?: LandingStore; onEdit?: (id: string) => void };
  let { store, onEdit }: Props = $props();
  let contextual: (() => LandingStore) | undefined;
  try { contextual = useLandingStore(); } catch { contextual = undefined; }
  let resolved = $derived(store ?? contextual?.());
  let items = $derived(resolved ? sortedLandingSections(resolved.items) : []);
  let visible = $derived(visibleLandingCount(items));

  function requireStore(): LandingStore {
    if (!resolved) throw new Error("LandingView requires a store prop or LandingProvider.");
    return resolved;
  }

  function createSection() {
    const current = requireStore();
    const next = blankSection(items.at(-1)?.order ?? 0);
    current.create(next);
    onEdit?.(next.id);
  }
</script>

{#if resolved}
  <section class="space-y-4">
    <header class="flex flex-wrap items-end justify-between gap-3">
      <div>
        <p class="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Landing</p>
        <h2 class="text-xl font-semibold tracking-tight">Landing sections</h2>
        <p class="mt-1 text-sm text-muted-foreground">{visible}/{items.length} sections visible</p>
      </div>
      <div class="flex gap-2">
        <a class="rounded-md border px-3 py-2 text-sm font-medium hover:bg-muted" href={resolved.publicBase}>View public</a>
        <button class="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground" type="button" onclick={createSection}>New section</button>
      </div>
    </header>

    <div class="overflow-x-auto rounded-lg border">
      <table class="w-full min-w-[680px] text-sm">
        <thead class="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground">
          <tr><th class="p-3">Title</th><th class="p-3">Kind</th><th class="p-3">#</th><th class="p-3">Visible</th><th class="p-3 text-right">Actions</th></tr>
        </thead>
        <tbody>
          {#each items as item, index (item.id)}
            <tr class="border-t">
              <td class="p-3"><div class="font-medium">{item.title}</div><div class="max-w-sm truncate text-xs text-muted-foreground">{item.subtitle ?? ""}</div></td>
              <td class="p-3"><span class="rounded-full border px-2 py-1 text-xs">{LANDING_KIND_LABEL[item.kind]}</span></td>
              <td class="p-3 font-mono text-xs">{String(item.order).padStart(2, "0")}</td>
              <td class="p-3"><button type="button" class="rounded-full border px-2 py-1 text-xs" onclick={() => resolved?.update(item.id, { enabled: !item.enabled })}>{item.enabled ? "on" : "off"}</button></td>
              <td class="p-3"><div class="flex justify-end gap-1">
                <button type="button" aria-label={`Move ${item.title} up`} disabled={index === 0} class="rounded border px-2 py-1 disabled:opacity-30" onclick={() => moveLandingSection(requireStore(), item.id, -1)}>↑</button>
                <button type="button" aria-label={`Move ${item.title} down`} disabled={index === items.length - 1} class="rounded border px-2 py-1 disabled:opacity-30" onclick={() => moveLandingSection(requireStore(), item.id, 1)}>↓</button>
                {#if onEdit}<button type="button" class="rounded border px-2 py-1" onclick={() => onEdit?.(item.id)}>Edit</button>{:else}<a class="rounded border px-2 py-1" href={`${resolved.adminBase}/landing/${item.id}`}>Edit</a>{/if}
                <button type="button" class="rounded border px-2 py-1 text-destructive" onclick={() => resolved?.remove(item.id)}>Delete</button>
              </div></td>
            </tr>
          {:else}
            <tr><td class="p-8 text-center text-muted-foreground" colspan="5">No landing sections yet.</td></tr>
          {/each}
        </tbody>
      </table>
    </div>
  </section>
{/if}
