// frontend/slices/app-store/components/create-app.tsx
"use client";

import { useMemo, useState } from "react";
import { Check, Rocket } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Segmented } from "./segmented";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { GLYPH_KEYS } from "../lib/glyph";
import { APP_GRADIENTS, APP_RUNTIMES, DEFAULT_ENTRY, appManifestJson, slugifyAppName, type AppRuntime } from "../lib/create-core";
import { createApp } from "../lib/apps-store";
import { usePublishInspector } from "../lib/host";
import { cn } from "@/lib/utils";
import { IconPreview } from "./icon-preview";
import { GlyphPicker } from "./glyph-picker";

// Create App — author a new os-rr app and persist it via Convex. On create the
// app is installed; the shell's dynamic registry shows it in the dock instantly.
export default function CreateApp() {
  const [name, setName] = useState("");
  const [runtime, setRuntime] = useState<AppRuntime>("html");
  const [entry, setEntry] = useState(DEFAULT_ENTRY.html);
  const [gradient, setGradient] = useState<string>(APP_GRADIENTS[0]);
  const [glyph, setGlyph] = useState<string>(GLYPH_KEYS[0]);
  const [created, setCreated] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const slug = useMemo(() => slugifyAppName(name) || "untitled", [name]);
  const manifest = useMemo(
    () => appManifestJson({ name, runtime, entry, glyph, gradient }),
    [name, runtime, entry, glyph, gradient],
  );

  const pickRuntime = (r: AppRuntime) => {
    setRuntime(r);
    setEntry(DEFAULT_ENTRY[r]);
  };

  // Surface the draft to the shell AI Inspector.
  usePublishInspector(
    "create-app",
    {
      subject: name.trim() || "New app",
      props: [
        { label: "Name", value: name.trim() || "—" },
        { label: "Slug", value: slug },
        { label: "Runtime", value: runtime },
        { label: "Entry", value: entry },
      ],
      context: `Creating app ${name.trim() || "untitled"} (${runtime})`,
      suggestions: ["Suggest a name", "What runtime should I use?", "Write a description"],
    },
    [name, slug, runtime, entry],
  );

  const handleCreate = async () => {
    if (created) return;
    setError(null);
    try {
      createApp({ appId: slug, title: name, glyph, gradient, runtime, entry });
      setCreated(true);
      setTimeout(() => {
        setName("");
        pickRuntime("html");
        setGradient(APP_GRADIENTS[0]);
        setGlyph(GLYPH_KEYS[0]);
        setCreated(false);
      }, 1800);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Gagal membuat app");
    }
  };

  return (
    <ScrollArea className="h-full">
      <div className="mx-auto max-w-md space-y-5 p-5">
        <header className="flex items-center gap-3">
          <IconPreview glyph={glyph} gradient={gradient} />
          <div className="min-w-0">
            <h2 className="truncate text-sm font-semibold">{name.trim() || "New app"}</h2>
            <p className="truncate font-mono text-[11px] text-muted-foreground">/apps/{slug}</p>
          </div>
        </header>

        <Separator />

        <Field label="Name">
          <Input aria-label="Name" value={name} onChange={(e) => setName(e.target.value)} placeholder="My App" autoFocus />
        </Field>

        <Field label="Runtime">
          <Segmented options={APP_RUNTIMES} value={runtime} onChange={pickRuntime} className="w-full" />
        </Field>

        <Field label="Entry point">
          <Input aria-label="Entry point" value={entry} onChange={(e) => setEntry(e.target.value)} className="font-mono text-xs" />
        </Field>

        <Field label="Glyph">
          <GlyphPicker value={glyph} onChange={setGlyph} />
        </Field>

        <Field label="Accent">
          <div className="flex gap-2">
            {APP_GRADIENTS.map((g) => (
              <Button
                key={g}
                type="button"
                variant="ghost"
                size="icon"
                aria-label="accent"
                onClick={() => setGradient(g)}
                style={{ background: g }}
                className={cn(
                  "size-7 rounded-full p-0 ring-offset-2 ring-offset-background transition",
                  gradient === g ? "ring-2 ring-primary" : "ring-1 ring-border hover:ring-foreground/40",
                )}
              />
            ))}
          </div>
        </Field>

        <Field label="manifest.json">
          <pre className="overflow-x-auto rounded-md border border-border bg-secondary/50 p-3 font-mono text-[11px] leading-relaxed text-muted-foreground">
            {manifest}
          </pre>
        </Field>

        <Button className="w-full" disabled={created} onClick={handleCreate}>
          {created ? (
            <>
              <Check className="size-4" /> Created
            </>
          ) : (
            <>
              <Rocket className="size-4" /> Create app
            </>
          )}
        </Button>

        {error && <p className="text-center text-xs text-destructive">{error}</p>}

        {created && (
          <div className="flex justify-center">
            <Badge variant="secondary">
              <Check className="size-3" /> Added to dock
            </Badge>
          </div>
        )}
      </div>
    </ScrollArea>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <label className="text-xs font-medium text-muted-foreground">{label}</label>
      {children}
    </div>
  );
}

// frontend/slices/app-store-svelte/components/CreateApp.svelte
<script lang="ts">
  import {
    APP_GRADIENTS,
    APP_RUNTIMES,
    DEFAULT_ENTRY,
    appManifestJson,
    slugifyAppName,
    type AppRuntime,
  } from "../../app-store/lib/create-core";
  import { createApp } from "../../app-store/lib/apps-core";
  import { GLYPH_KEYS, glyphSymbol } from "../../app-store/lib/glyph-core";

  let name = $state("");
  let runtime = $state<AppRuntime>("html");
  let entry = $state(DEFAULT_ENTRY.html);
  let gradient = $state<string>(APP_GRADIENTS[0]);
  let glyph = $state<string>(GLYPH_KEYS[0]);
  let created = $state(false);
  let error = $state("");
  let slug = $derived(slugifyAppName(name) || "untitled");
  let manifest = $derived(appManifestJson({ name, runtime, entry, glyph, gradient }));

  function pickRuntime(next: AppRuntime) {
    runtime = next;
    entry = DEFAULT_ENTRY[next];
  }

  function submit() {
    if (created) return;
    error = "";
    try {
      createApp({ appId: slug, title: name.trim() || "New app", glyph, gradient, runtime, entry });
      created = true;
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Gagal membuat app";
    }
  }
</script>

<div class="h-full overflow-auto">
  <div class="mx-auto max-w-md space-y-5 p-5">
    <header class="flex items-center gap-3">
      <div class="grid size-12 place-items-center rounded-xl text-sm font-semibold text-white" style:background={gradient}>{glyphSymbol(glyph)}</div>
      <div class="min-w-0"><h2 class="truncate text-sm font-semibold">{name.trim() || "New app"}</h2><p class="truncate font-mono text-[11px] text-muted-foreground">/apps/{slug}</p></div>
    </header>

    <label class="block space-y-1.5"><span class="text-xs font-medium text-muted-foreground">Name</span><input class="h-9 w-full rounded-md border border-input bg-background px-3 text-sm" bind:value={name} placeholder="My App" /></label>

    <fieldset class="space-y-1.5"><legend class="text-xs font-medium text-muted-foreground">Runtime</legend><div class="grid grid-cols-4 gap-1">{#each APP_RUNTIMES as option}<button type="button" class="rounded-md border px-2 py-1.5 text-xs {runtime === option.value ? 'bg-foreground text-background' : 'bg-background'}" onclick={() => pickRuntime(option.value)}>{option.label}</button>{/each}</div></fieldset>

    <label class="block space-y-1.5"><span class="text-xs font-medium text-muted-foreground">Entry point</span><input class="h-9 w-full rounded-md border border-input bg-background px-3 font-mono text-xs" bind:value={entry} /></label>

    <fieldset class="space-y-1.5"><legend class="text-xs font-medium text-muted-foreground">Glyph</legend><div class="grid grid-cols-4 gap-2">{#each GLYPH_KEYS as key}<button type="button" class="rounded-md border p-2 text-xs {glyph === key ? 'ring-2 ring-foreground' : ''}" onclick={() => (glyph = key)}><span class="mr-1">{glyphSymbol(key)}</span>{key}</button>{/each}</div></fieldset>

    <fieldset class="space-y-1.5"><legend class="text-xs font-medium text-muted-foreground">Accent</legend><div class="flex gap-2">{#each APP_GRADIENTS as color}<button type="button" aria-label="accent" class="size-7 rounded-full border {gradient === color ? 'ring-2 ring-foreground ring-offset-2' : ''}" style:background={color} onclick={() => (gradient = color)}></button>{/each}</div></fieldset>

    <div class="space-y-1.5"><p class="text-xs font-medium text-muted-foreground">manifest.json</p><pre class="overflow-x-auto rounded-md border bg-secondary/40 p-3 font-mono text-[11px] leading-relaxed text-muted-foreground">{manifest}</pre></div>

    <button class="w-full rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background disabled:opacity-50" disabled={created} onclick={submit}>{created ? "✓ Created" : "Create app"}</button>
    {#if error}<p class="text-center text-xs text-destructive" role="alert">{error}</p>{/if}
    {#if created}<p class="text-center text-xs text-muted-foreground" role="status">Added to the local app registry.</p>{/if}
  </div>
</div>
