// frontend/slices/settings-svelte/variants/account/components/sections/PreferencesSection.svelte
<script lang="ts">
  import {
    SETTINGS_DENSITIES,
    SETTINGS_LANGUAGES,
    SETTINGS_THEMES,
  } from "@/features/settings/variants/account/lib/core";
  import type {
    DensityPref,
    SettingsPreferences,
    ThemePref,
  } from "@/features/settings/variants/account/lib/adapter";

  let {
    value,
    saving = false,
    onSave,
  } = $props<{
    value: SettingsPreferences;
    saving?: boolean;
    onSave: (preferences: SettingsPreferences) => void | Promise<void>;
  }>();

  let draft = $state<SettingsPreferences>({ theme: "system", language: "en", density: "comfortable" });
  let dirty = $derived(JSON.stringify(draft) !== JSON.stringify(value));

  $effect(() => {
    draft = { ...value };
  });

  function patch(next: Partial<SettingsPreferences>) {
    draft = { ...draft, ...next };
  }
</script>

<section class="rounded-xl border bg-card text-card-foreground shadow-sm">
  <header class="space-y-1.5 border-b px-5 py-4">
    <h2 class="font-semibold">Preferences</h2>
    <p class="text-sm text-muted-foreground">Appearance and locale for this account.</p>
  </header>
  <div class="space-y-5 p-5">
    <label class="block space-y-1.5 text-sm">
      <span class="font-medium">Theme</span>
      <select
        value={draft.theme}
        onchange={(event) => patch({ theme: event.currentTarget.value as ThemePref })}
        class="h-10 w-full rounded-md border bg-background px-3 text-sm sm:w-60"
      >
        {#each SETTINGS_THEMES as theme}
          <option value={theme}>{theme[0].toUpperCase() + theme.slice(1)}</option>
        {/each}
      </select>
    </label>

    <label class="block space-y-1.5 text-sm">
      <span class="font-medium">Language</span>
      <select
        value={draft.language}
        onchange={(event) => patch({ language: event.currentTarget.value })}
        class="h-10 w-full rounded-md border bg-background px-3 text-sm sm:w-60"
      >
        {#each SETTINGS_LANGUAGES as language}
          <option value={language.value}>{language.label}</option>
        {/each}
      </select>
    </label>

    <div class="space-y-1.5 text-sm">
      <span class="font-medium">Density</span>
      <div class="inline-flex rounded-md border p-0.5">
        {#each SETTINGS_DENSITIES as density}
          <button
            type="button"
            onclick={() => patch({ density: density as DensityPref })}
            class={`rounded px-3 py-1 text-xs capitalize ${draft.density === density ? "bg-accent font-medium text-accent-foreground" : "text-muted-foreground hover:text-foreground"}`}
          >
            {density}
          </button>
        {/each}
      </div>
    </div>

    <div class="flex justify-end">
      <button
        type="button"
        disabled={saving || !dirty}
        onclick={() => onSave(draft)}
        class="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {saving ? "Saving…" : "Save changes"}
      </button>
    </div>
  </div>
</section>

// frontend/slices/settings-page/components/sections/PreferencesSection.tsx
"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type {
  DensityPref,
  SettingsPreferences,
  ThemePref,
} from "../../lib/adapter";

const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "id", label: "Bahasa Indonesia" },
  { value: "es", label: "Español" },
  { value: "fr", label: "Français" },
  { value: "de", label: "Deutsch" },
  { value: "ja", label: "日本語" },
];

const DENSITIES: DensityPref[] = ["comfortable", "compact"];

const AUTOLOCK: { label: string; value: number | null }[] = [
  { label: "Off", value: null },
  { label: "1 min", value: 1 },
  { label: "5 min", value: 5 },
  { label: "15 min", value: 15 },
];

export interface PreferencesSectionProps {
  value: SettingsPreferences;
  saving?: boolean;
  onSave: (prefs: SettingsPreferences) => void | Promise<void>;
}

export function PreferencesSection({ value, saving, onSave }: PreferencesSectionProps) {
  const [draft, setDraft] = React.useState<SettingsPreferences>(value);
  React.useEffect(() => setDraft(value), [value]);

  const dirty = JSON.stringify(draft) !== JSON.stringify(value);
  const set = (patch: Partial<SettingsPreferences>) =>
    setDraft((d) => ({ ...d, ...patch }));

  return (
    <Card>
      <CardHeader>
        <CardTitle>Preferences</CardTitle>
        <CardDescription>Appearance and locale for this account.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-1.5">
          <Label>Theme</Label>
          <Select value={draft.theme} onValueChange={(v) => set({ theme: v as ThemePref })}>
            <SelectTrigger className="w-full sm:w-60">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="light">Light</SelectItem>
              <SelectItem value="dark">Dark</SelectItem>
              <SelectItem value="system">System</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-1.5">
          <Label>Language</Label>
          <Select value={draft.language} onValueChange={(v) => set({ language: v })}>
            <SelectTrigger className="w-full sm:w-60">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {LANGUAGES.map((l) => (
                <SelectItem key={l.value} value={l.value}>
                  {l.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-1.5">
          <Label>Density</Label>
          <div className="inline-flex rounded-md border border-input p-0.5">
            {DENSITIES.map((d) => (
              <Button
                key={d}
                type="button"
                variant="ghost"
                onClick={() => set({ density: d })}
                className={cn(
                  "h-auto rounded px-3 py-1 text-xs capitalize",
                  draft.density === d
                    ? "bg-accent font-medium"
                    : "text-muted-foreground hover:text-foreground",
                )}
              >
                {d}
              </Button>
            ))}
          </div>
        </div>

        <div className="space-y-1.5">
          <Label>Auto-lock</Label>
          <div className="inline-flex rounded-md border border-input p-0.5">
            {AUTOLOCK.map((o) => (
              <Button
                key={o.label}
                type="button"
                variant="ghost"
                onClick={() => set({ autoLockMinutes: o.value })}
                className={cn(
                  "h-auto rounded px-3 py-1 text-xs",
                  (draft.autoLockMinutes ?? null) === o.value
                    ? "bg-accent font-medium"
                    : "text-muted-foreground hover:text-foreground",
                )}
              >
                {o.label}
              </Button>
            ))}
          </div>
        </div>

        <div className="flex justify-end">
          <Button disabled={saving || !dirty} onClick={() => onSave(draft)}>
            {saving ? "Saving…" : "Save changes"}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
