// frontend/slices/library-svelte/views/LibraryIndex.svelte
<script lang="ts">
  import {
    ALL_KINDS,
    collectLibraryTools,
    filterLibraryItems,
    resolveKindLabels,
    resolveLibraryCopy,
    type LibraryKindFilter,
  } from "@/features/library/lib/core";
  import type {
    KindLabelMap,
    LibraryCopy,
    LibraryRow,
  } from "@/features/library/lib/types";

  let {
    items,
    copy: copyOverride,
    kindLabels: kindLabelsOverride,
  }: {
    items: LibraryRow[];
    copy?: Partial<LibraryCopy>;
    kindLabels?: KindLabelMap;
  } = $props();

  let kind = $state<LibraryKindFilter>("all");
  let tool = $state("");
  let copy = $derived(resolveLibraryCopy(copyOverride));
  let kindLabels = $derived(resolveKindLabels(kindLabelsOverride));
  let allTools = $derived(collectLibraryTools(items));
  let filtered = $derived(filterLibraryItems(items, kind, tool));

  function chip(active: boolean): string {
    return `h-auto rounded-md border-2 px-3 py-1 text-[11px] font-medium uppercase tracking-wider transition-colors ${active ? "border-current bg-foreground text-background" : "border-current/40 hover:border-current"}`;
  }
</script>

<section class="py-12 lg:py-20">
  <div class="container mx-auto space-y-8 px-4 lg:px-8">
    <header class="space-y-3">
      <div class="text-[10px] uppercase tracking-wider opacity-60">{copy.eyebrow}</div>
      <h1 class="font-serif text-4xl leading-tight lg:text-6xl">{copy.title}</h1>
      {#if copy.body}<p class="max-w-2xl text-base opacity-70">{copy.body}</p>{/if}
    </header>

    <div class="space-y-3">
      <div class="flex flex-wrap items-center gap-2">
        <button type="button" class={chip(kind === "all")} onclick={() => (kind = "all")}>{copy.allLabel}</button>
        {#each ALL_KINDS as value (value)}
          <button type="button" class={chip(kind === value)} onclick={() => (kind = value)}>
            {kindLabels[value] ?? value}
          </button>
        {/each}
      </div>

      {#if allTools.length > 0}
        <div class="flex flex-wrap items-center gap-2">
          <span class="text-[10px] uppercase tracking-wider opacity-50">{copy.toolLabel}</span>
          <button
            type="button"
            class={`px-1 py-0 text-[11px] underline underline-offset-4 ${tool === "" ? "font-bold" : "opacity-60"}`}
            onclick={() => (tool = "")}
          >{copy.toolAllLabel}</button>
          {#each allTools as value (value)}
            <button
              type="button"
              class={`px-1 py-0 text-[11px] underline underline-offset-4 ${tool === value ? "font-bold" : "opacity-60"}`}
              onclick={() => (tool = value === tool ? "" : value)}
            >{value}</button>
          {/each}
        </div>
      {/if}
    </div>

    {#if filtered.length === 0}
      <p class="text-sm opacity-60">{copy.emptyText}</p>
    {:else}
      <ul class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {#each filtered as item (item._id)}
          <li class="rounded-md border-2 border-current transition-shadow hover:shadow-md">
            <a href={`/library/${item.slug}`} class="group block space-y-3 p-4">
              <div class="flex items-baseline justify-between gap-2">
                <span class="rounded-sm border-2 border-current px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
                  {kindLabels[item.kind] ?? item.kind}
                </span>
                {#if typeof item.upvotes === "number" && item.upvotes > 0}
                  <span class="text-[11px] tabular-nums opacity-60">▲ {item.upvotes}</span>
                {/if}
              </div>
              <h3 class="text-base font-bold leading-tight underline-offset-4 group-hover:underline">{item.title}</h3>
              <p class="line-clamp-3 text-sm opacity-70">{item.excerpt}</p>
              {#if (item.tools ?? []).length > 0}
                <div class="flex flex-wrap gap-1">
                  {#each (item.tools ?? []).slice(0, 4) as itemTool (itemTool)}
                    <span class="rounded border border-current/30 px-1.5 py-0.5 text-[10px] uppercase tracking-wider">{itemTool}</span>
                  {/each}
                </div>
              {/if}
            </a>
          </li>
        {/each}
      </ul>
    {/if}
  </div>
</section>

// frontend/slices/library/views/LibraryIndex.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { LibraryIndexProps, LibraryRow } from "../lib/types";
import {
  ALL_KINDS,
  collectLibraryTools,
  filterLibraryItems,
  resolveKindLabels,
  resolveLibraryCopy,
} from "../lib/core";

// Grid of library cards with kind + tool filters. All copy + kind
// labels are prop-driven (English defaults). Detail routes are
// `/library/<slug>` — adjust the consumer's route group if mounting
// elsewhere.
export function LibraryIndex({
  items,
  copy: copyOverride,
  kindLabels: kindLabelsOverride,
}: LibraryIndexProps) {
  const copy = resolveLibraryCopy(copyOverride);
  const kindLabels = resolveKindLabels(kindLabelsOverride);

  const [kind, setKind] = useState<LibraryRow["kind"] | "all">("all");
  const [tool, setTool] = useState("");

  const allTools = collectLibraryTools(items);
  const filtered = filterLibraryItems(items, kind, tool);

  const chip = (active: boolean) =>
    cn(
      "h-auto border-2 rounded-md px-3 py-1 text-[11px] uppercase tracking-wider font-medium transition-colors hover:bg-transparent",
      active
        ? "border-current bg-foreground text-background hover:bg-foreground hover:text-background"
        : "border-current/40 hover:border-current",
    );

  return (
    <section className="py-12 lg:py-20">
      <div className="container mx-auto px-4 lg:px-8 space-y-8">
        <header className="space-y-3">
          <div className="text-[10px] uppercase tracking-wider opacity-60">{copy.eyebrow}</div>
          <h1 className="font-serif text-4xl lg:text-6xl leading-tight">{copy.title}</h1>
          {copy.body ? <p className="text-base opacity-70 max-w-2xl">{copy.body}</p> : null}
        </header>

        <div className="space-y-3">
          <div className="flex flex-wrap items-center gap-2">
            <Button type="button" variant="ghost" onClick={() => setKind("all")} className={chip(kind === "all")}>
              {copy.allLabel}
            </Button>
            {ALL_KINDS.map((k) => (
              <Button key={k} type="button" variant="ghost" onClick={() => setKind(k)} className={chip(kind === k)}>
                {kindLabels[k] ?? k}
              </Button>
            ))}
          </div>
          {allTools.length > 0 ? (
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[10px] uppercase tracking-wider opacity-50">{copy.toolLabel}</span>
              <Button
                type="button"
                variant="ghost"
                onClick={() => setTool("")}
                className={cn(
                  "h-auto px-1 py-0 text-[11px] underline underline-offset-4 hover:bg-transparent",
                  tool === "" ? "font-bold" : "opacity-60",
                )}
              >
                {copy.toolAllLabel}
              </Button>
              {allTools.map((t) => (
                <Button
                  key={t}
                  type="button"
                  variant="ghost"
                  onClick={() => setTool(t === tool ? "" : t)}
                  className={cn(
                    "h-auto px-1 py-0 text-[11px] underline underline-offset-4 hover:bg-transparent",
                    tool === t ? "font-bold" : "opacity-60",
                  )}
                >
                  {t}
                </Button>
              ))}
            </div>
          ) : null}
        </div>

        {filtered.length === 0 ? (
          <p className="text-sm opacity-60">{copy.emptyText}</p>
        ) : (
          <ul className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {filtered.map((i) => (
              <li
                key={i._id}
                className="border-2 border-current rounded-md hover:shadow-md transition-shadow"
              >
                <Link href={`/library/${i.slug}`} className="block p-4 space-y-3 group">
                  <div className="flex items-baseline justify-between gap-2">
                    <span className="border-2 border-current rounded-sm px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
                      {kindLabels[i.kind] ?? i.kind}
                    </span>
                    {typeof i.upvotes === "number" && i.upvotes > 0 ? (
                      <span className="text-[11px] tabular-nums opacity-60">▲ {i.upvotes}</span>
                    ) : null}
                  </div>
                  <h3 className="font-bold text-base leading-tight group-hover:underline underline-offset-4">
                    {i.title}
                  </h3>
                  <p className="text-sm opacity-70 line-clamp-3">{i.excerpt}</p>
                  {(i.tools ?? []).length > 0 ? (
                    <div className="flex flex-wrap gap-1">
                      {(i.tools ?? []).slice(0, 4).map((t) => (
                        <span
                          key={t}
                          className="text-[10px] uppercase tracking-wider border border-current/30 rounded px-1.5 py-0.5"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  ) : null}
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>
    </section>
  );
}
