// frontend/slices/image-picker/components/ImagePickerDialog.tsx
"use client";

/** ImagePickerDialog — the 4-tab image chooser (Gallery · Upload · Link ·
 *  Unsplash). Upload tab appears only when `onUpload` is wired; the Unsplash
 *  tab live-searches (debounced) via the injected `searchUnsplash` and falls
 *  back to the curated set. `defaultQuery` pre-fills + auto-runs the search and
 *  opens on that tab. Usually you don't render this directly — use
 *  ImagePickerButton, which owns the trigger + open state. */

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import type { ImageValue, ImageSourceProps } from "../types";
import { pickerTabLabel, pickerTabs, type ImagePickerTab } from "../lib/core";
import { GalleryTab } from "./image-picker/GalleryTab";
import { UploadTab } from "./image-picker/UploadTab";
import { LinkTab } from "./image-picker/LinkTab";
import { UnsplashTab } from "./image-picker/UnsplashTab";

interface Props extends ImageSourceProps {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  onSelect: (c: ImageValue) => void;
  title?: string;
  /** Pre-fill + auto-run the Unsplash search (opens on that tab). */
  defaultQuery?: string;
}

export function ImagePickerDialog({ open, onOpenChange, onSelect, onUpload, searchUnsplash, title = "Choose image", defaultQuery }: Props) {
  const [tab, setTab] = React.useState<ImagePickerTab>(defaultQuery ? "unsplash" : "gallery");
  const tabs = pickerTabs(!!onUpload).map((id) => ({ id, label: pickerTabLabel(id) }));
  const handle = (c: ImageValue) => { onSelect(c); onOpenChange(false); };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl gap-0 p-0">
        <DialogHeader className="border-b border-border px-4 py-3">
          <DialogTitle className="text-sm">{title}</DialogTitle>
        </DialogHeader>
        <div className="flex items-center gap-1 border-b border-border px-2 py-1.5">
          {tabs.map((t) => (
            <Button
              key={t.id} type="button" variant="ghost" onClick={() => setTab(t.id)}
              className={cn(
                "h-auto rounded-md px-3 py-1 text-xs font-medium transition",
                tab === t.id ? "bg-accent text-foreground" : "text-muted-foreground hover:bg-accent/50",
              )}
            >
              {t.label}
            </Button>
          ))}
        </div>
        <div className="h-[440px] overflow-y-auto">
          {tab === "gallery" && <GalleryTab onSelect={handle} />}
          {tab === "upload" && onUpload && <UploadTab onSelect={handle} onUpload={onUpload} />}
          {tab === "link" && <LinkTab onSelect={handle} />}
          {tab === "unsplash" && <UnsplashTab onSelect={handle} searchUnsplash={searchUnsplash} defaultQuery={defaultQuery} />}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// frontend/slices/image-picker-svelte/components/ImagePickerDialog.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import GalleryTab from "./GalleryTab.svelte";
  import LinkTab from "./LinkTab.svelte";
  import UnsplashTab from "./UnsplashTab.svelte";
  import UploadTab from "./UploadTab.svelte";
  import { pickerTabLabel, pickerTabs, type ImagePickerTab } from "@/features/image-picker/lib/core";
  import type { ImageValue, UnsplashSearchFn, UploadFn } from "@/features/image-picker/types";

  let {
    open = $bindable(false),
    onSelect,
    onUpload,
    searchUnsplash,
    title = "Choose image",
    defaultQuery,
  }: {
    open?: boolean;
    onSelect: (image: ImageValue) => void;
    onUpload?: UploadFn;
    searchUnsplash?: UnsplashSearchFn;
    title?: string;
    defaultQuery?: string;
  } = $props();

  let tab = $state<ImagePickerTab>("gallery");
  let tabs = $derived(pickerTabs(Boolean(onUpload)));
  let visibleTab = $derived<ImagePickerTab>(tabs.includes(tab) ? tab : "gallery");

  function close() {
    open = false;
  }

  function choose(image: ImageValue) {
    onSelect(image);
    close();
  }

  function handleKeydown(event: KeyboardEvent) {
    if (open && event.key === "Escape") close();
  }

  onMount(() => {
    if (defaultQuery) tab = "unsplash";
  });
</script>

<svelte:window onkeydown={handleKeydown} />

{#if open}
  <div class="fixed inset-0 z-50 grid place-items-center p-4">
    <button
      type="button"
      class="absolute inset-0 bg-black/55"
      aria-label="Close image picker"
      onclick={close}
    ></button>
    <div
      role="dialog"
      aria-modal="true"
      aria-label={title}
      class="relative z-10 flex max-h-[min(88vh,620px)] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-border bg-background shadow-2xl"
    >
      <header class="flex items-center justify-between border-b border-border px-4 py-3">
        <h2 class="text-sm font-semibold">{title}</h2>
        <button type="button" class="rounded-md px-2 py-1 text-sm text-muted-foreground hover:bg-muted hover:text-foreground" onclick={close} aria-label="Close">×</button>
      </header>

      <div class="flex items-center gap-1 overflow-x-auto border-b border-border px-2 py-1.5">
        {#each tabs as item (item)}
          <button
            type="button"
            class={visibleTab === item
              ? "rounded-md bg-accent px-3 py-1 text-xs font-medium text-foreground"
              : "rounded-md px-3 py-1 text-xs font-medium text-muted-foreground hover:bg-accent/50"}
            onclick={() => (tab = item)}
          >
            {pickerTabLabel(item)}
          </button>
        {/each}
      </div>

      <div class="min-h-0 flex-1 overflow-y-auto">
        {#if visibleTab === "gallery"}
          <GalleryTab onSelect={choose} />
        {:else if visibleTab === "upload" && onUpload}
          <UploadTab onSelect={choose} {onUpload} />
        {:else if visibleTab === "link"}
          <LinkTab onSelect={choose} />
        {:else}
          <UnsplashTab onSelect={choose} {searchUnsplash} {defaultQuery} />
        {/if}
      </div>
    </div>
  </div>
{/if}
