// frontend/slices/cover/components/cover-picker/UnsplashTab.tsx
"use client";

import * as React from "react";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CURATED_UNSPLASH } from "../../lib/unsplashCurated";
import type { CoverData, UnsplashPhoto, UnsplashSearchFn } from "../../types";

export function UnsplashTab({
  onPick, searchUnsplash,
}: { onPick: (c: CoverData) => void; searchUnsplash?: UnsplashSearchFn }) {
  const [q, setQ] = React.useState("");
  const [photos, setPhotos] = React.useState<UnsplashPhoto[]>(CURATED_UNSPLASH);
  const [curated, setCurated] = React.useState(true);
  const [busy, setBusy] = React.useState(false);
  const [err, setErr] = React.useState<string | null>(null);

  const run = async () => {
    if (!q.trim() || !searchUnsplash) return;
    setBusy(true);
    setErr(null);
    const res = await searchUnsplash(q.trim(), 24);
    setBusy(false);
    if (res.error) setErr(res.error);
    setPhotos(res.photos.length ? res.photos : CURATED_UNSPLASH);
    setCurated(res.photos.length === 0);
  };

  const pick = (p: UnsplashPhoto) =>
    onPick({
      type: "unsplash", value: p.regular, positionY: 50,
      metadata: { id: p.id, thumb: p.thumb, full: p.full, photographer: p.photographer, photographerUrl: p.photographerUrl, source: p.source },
    });

  return (
    <div className="space-y-3 p-4">
      <div className="flex gap-2">
        <Input
          placeholder={searchUnsplash ? "Search Unsplash…" : "Curated picks (wire searchUnsplash for live search)"}
          value={q} disabled={!searchUnsplash}
          onChange={(e) => setQ(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && run()}
        />
        <Button onClick={run} disabled={!searchUnsplash || busy} size="icon" aria-label="Search">
          <Search className="h-4 w-4" />
        </Button>
      </div>
      {err && <p className="text-xs text-destructive">{err}</p>}
      {curated && (
        <p className="text-[11px] text-muted-foreground">
          Curated landscapes{searchUnsplash ? " — search above for more" : ""}.
        </p>
      )}
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
        {photos.map((p) => (
          <button
            key={p.id} type="button" onClick={() => pick(p)}
            className="group relative h-20 overflow-hidden rounded-md ring-1 ring-border transition hover:ring-2 hover:ring-primary"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={p.thumb} alt={p.alt} loading="lazy" className="h-full w-full object-cover" />
            <span className="absolute inset-x-0 bottom-0 truncate bg-black/50 px-1 py-0.5 text-[9px] text-white opacity-0 transition group-hover:opacity-100">
              {p.photographer}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}

// frontend/slices/image-picker-svelte/components/UnsplashTab.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { pickerTabLabel, toUnsplashImageValue } from "@/features/image-picker/lib/core";
  import { CURATED_UNSPLASH } from "@/features/image-picker/lib/unsplashCurated";
  import type { ImageValue, UnsplashPhoto, UnsplashSearchFn } from "@/features/image-picker/types";

  let { onSelect, searchUnsplash, defaultQuery }: {
    onSelect: (image: ImageValue) => void;
    searchUnsplash?: UnsplashSearchFn;
    defaultQuery?: string;
  } = $props();

  let query = $state("");
  let results = $state.raw<UnsplashPhoto[] | null>(null);
  let busy = $state(false);
  let error = $state<string | null>(null);
  let searchTimer: ReturnType<typeof setTimeout> | undefined;
  let searchGeneration = 0;
  let photos = $derived(results ?? CURATED_UNSPLASH);

  function scheduleSearch(nextQuery: string, delay = 400) {
    query = nextQuery;
    searchGeneration += 1;
    const generation = searchGeneration;
    if (searchTimer) clearTimeout(searchTimer);

    const trimmed = nextQuery.trim();
    if (!searchUnsplash || !trimmed) {
      results = null;
      error = null;
      busy = false;
      searchTimer = undefined;
      return;
    }

    searchTimer = setTimeout(() => {
      searchTimer = undefined;
      void runSearch(trimmed, generation);
    }, delay);
  }

  async function runSearch(trimmed: string, generation: number) {
    if (!searchUnsplash) return;
    busy = true;
    error = null;
    const response = await searchUnsplash(trimmed, 24);
    if (generation !== searchGeneration) return;
    busy = false;
    if (response.error) {
      error = response.error;
      results = null;
      return;
    }
    results = response.photos;
  }

  onMount(() => {
    if (defaultQuery) scheduleSearch(defaultQuery, 0);
  });

  onDestroy(() => {
    searchGeneration += 1;
    if (searchTimer) clearTimeout(searchTimer);
  });
</script>

<div class="space-y-3 p-4">
  <div class="relative">
    <input
      class="h-9 w-full rounded-md border border-input bg-background px-3 pr-20 text-sm"
      aria-label="Search Unsplash"
      placeholder={searchUnsplash ? "Search Unsplash…" : "Curated picks (wire searchUnsplash for live search)"}
      value={query}
      disabled={!searchUnsplash}
      oninput={(event) => scheduleSearch(event.currentTarget.value)}
    />
    <span class="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-[10px] text-muted-foreground">
      {busy ? "Searching…" : pickerTabLabel("unsplash")}
    </span>
  </div>

  {#if error}
    <p class="text-xs text-destructive">{error}</p>
  {:else if !results}
    <p class="text-[11px] text-muted-foreground">
      Curated landscapes{searchUnsplash ? " — type above for live search" : ""}.
    </p>
  {:else if results.length === 0 && !busy}
    <p class="text-xs text-muted-foreground">No results for “{query.trim()}”.</p>
  {/if}

  <div class="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4">
    {#each photos as photo (photo.id)}
      <button
        type="button"
        class="group relative h-20 w-full overflow-hidden rounded-md p-0 ring-1 ring-border transition hover:ring-2 hover:ring-primary"
        onclick={() => onSelect(toUnsplashImageValue(photo))}
      >
        <img src={photo.thumb} alt={photo.alt || "Stock photo"} loading="lazy" class="h-full w-full object-cover" />
        <span class="absolute inset-x-0 bottom-0 truncate bg-black/55 px-1 py-0.5 text-left text-[9px] text-white">
          {photo.photographer || "Unknown"}
        </span>
      </button>
    {/each}
  </div>
</div>
