// frontend/slices/image-picker/components/image-picker/UploadTab.tsx
"use client";

import * as React from "react";
import { UploadCloud } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ImageValue, UploadFn } from "../../types";

const MAX = 8 * 1024 * 1024;

export function UploadTab({ onSelect, onUpload }: { onSelect: (c: ImageValue) => void; onUpload: UploadFn }) {
  const [file, setFile] = React.useState<File | null>(null);
  const [preview, setPreview] = React.useState<string | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [err, setErr] = React.useState<string | null>(null);

  const pick = (f: File | undefined) => {
    if (!f) return;
    if (!f.type.startsWith("image/")) { setErr("Images only"); return; }
    if (f.size > MAX) { setErr("Max 8 MB"); return; }
    setErr(null);
    setFile(f);
    setPreview(URL.createObjectURL(f));
  };

  const apply = async () => {
    if (!file) return;
    setBusy(true);
    setErr(null);
    try {
      const ref = await onUpload(file);
      onSelect({ type: "upload", value: ref, positionY: 50, metadata: { filename: file.name } });
    } catch (e) {
      setErr(`Upload failed: ${(e as Error).message}`);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="space-y-3 p-4">
      <label
        onDragOver={(e) => e.preventDefault()}
        onDrop={(e) => { e.preventDefault(); pick(e.dataTransfer.files?.[0]); }}
        className="flex h-32 cursor-pointer flex-col items-center justify-center gap-2 overflow-hidden rounded-md border-2 border-dashed border-border text-sm text-muted-foreground transition hover:border-primary"
      >
        {preview ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={preview} alt="" className="h-full w-full object-cover" />
        ) : (
          <>
            <UploadCloud className="h-6 w-6" />
            <span>Drag an image or click to choose (≤ 8 MB)</span>
          </>
        )}
        <input type="file" accept="image/*" className="hidden" onChange={(e) => pick(e.target.files?.[0] ?? undefined)} />
      </label>
      {err && <p className="text-xs text-destructive">{err}</p>}
      <Button onClick={apply} disabled={!file || busy} className="w-full">
        {busy ? "Uploading…" : "Upload & set image"}
      </Button>
    </div>
  );
}

// frontend/slices/image-picker-svelte/components/UploadTab.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { validateUploadFile } from "@/features/image-picker/lib/core";
  import type { ImageValue, UploadFn } from "@/features/image-picker/types";

  let { onSelect, onUpload }: { onSelect: (image: ImageValue) => void; onUpload: UploadFn } = $props();
  let file = $state<File | null>(null);
  let preview = $state<string | null>(null);
  let busy = $state(false);
  let error = $state<string | null>(null);

  function pick(next: File | undefined) {
    if (!next) return;
    const problem = validateUploadFile(next);
    if (problem) {
      error = problem;
      return;
    }
    error = null;
    file = next;
    if (preview) URL.revokeObjectURL(preview);
    preview = URL.createObjectURL(next);
  }

  async function apply() {
    if (!file || busy) return;
    busy = true;
    error = null;
    try {
      const ref = await onUpload(file);
      onSelect({ type: "upload", value: ref, positionY: 50, metadata: { filename: file.name } });
    } catch (cause) {
      error = `Upload failed: ${cause instanceof Error ? cause.message : String(cause)}`;
    } finally {
      busy = false;
    }
  }

  onDestroy(() => {
    if (preview) URL.revokeObjectURL(preview);
  });

  function drop(event: DragEvent) {
    event.preventDefault();
    pick(event.dataTransfer?.files?.[0]);
  }
</script>

<div class="space-y-3 p-4">
  <label class="flex h-32 cursor-pointer flex-col items-center justify-center gap-2 overflow-hidden rounded-md border-2 border-dashed border-border text-sm text-muted-foreground transition hover:border-primary" ondragover={(event) => event.preventDefault()} ondrop={drop}>
    <input class="sr-only" type="file" accept="image/*" onchange={(event) => pick(event.currentTarget.files?.[0])} />
    {#if preview}
      <img src={preview} alt="Selected upload preview" class="h-full w-full object-cover" />
    {:else}
      <span class="text-lg" aria-hidden="true">⇧</span>
      <span>Drag an image or click to choose (≤ 8 MB)</span>
    {/if}
  </label>
  {#if error}<p class="text-xs text-destructive">{error}</p>{/if}
  <button type="button" class="h-9 w-full rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={!file || busy} onclick={() => void apply()}>
    {busy ? "Uploading…" : "Upload & set image"}
  </button>
</div>
