// frontend/slices/resend-newsletter/components/subscribe-form.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { newsletterSuccessMessage } from "../lib/core";
import { newsletterPublicApi } from "../lib/host";

export default function SubscribeForm() {
  const [email, setEmail] = useState("");
  const [website, setWebsite] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    if (busy || !newsletterPublicApi.configured) return;
    setBusy(true);
    setMessage("");
    setError("");
    try {
      const result = await newsletterPublicApi.subscribe({ email, website });
      setMessage(newsletterSuccessMessage(result));
      if (!result.already) setEmail("");
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Could not subscribe. Try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <Card className="mx-auto mt-12 flex max-w-md flex-col gap-3 p-6">
      <div>
        <h2 className="text-xl font-semibold">Subscribe to the newsletter</h2>
        <p className="mt-1 text-sm text-muted-foreground">Single opt-in: a successful submit activates the address immediately.</p>
      </div>
      {!newsletterPublicApi.configured && (
        <p className="rounded-md border border-border bg-muted/40 p-3 text-sm text-muted-foreground" role="status">
          Configure the newsletter adapter before rendering this form.
        </p>
      )}
      <form onSubmit={handleSubmit} className="flex flex-col gap-3">
        <Label htmlFor="newsletter-email">Email</Label>
        <Input
          id="newsletter-email"
          type="email"
          required
          autoComplete="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          placeholder="you@domain.com"
        />
        <label className="sr-only" aria-hidden="true">
          Website
          <input tabIndex={-1} autoComplete="off" value={website} onChange={(event) => setWebsite(event.target.value)} />
        </label>
        <Button type="submit" disabled={busy || !newsletterPublicApi.configured}>
          {busy ? "Subscribing…" : "Subscribe"}
        </Button>
        {message && <p className="text-sm text-emerald-600" role="status">{message}</p>}
        {error && <p className="text-sm text-destructive" role="alert">{error}</p>}
      </form>
    </Card>
  );
}

// frontend/slices/resend-newsletter-svelte/components/SubscribeForm.svelte
<script lang="ts">
  import { newsletterSuccessMessage } from "../../resend-newsletter/lib/core";
  import { newsletterPublicApi } from "../../resend-newsletter/lib/host";

  let email = $state("");
  let website = $state("");
  let busy = $state(false);
  let message = $state("");
  let error = $state("");
  let configured = $derived(newsletterPublicApi.configured);

  async function submit() {
    if (busy || !configured) return;
    busy = true;
    message = "";
    error = "";
    try {
      const result = await newsletterPublicApi.subscribe({ email, website });
      message = newsletterSuccessMessage(result);
      if (!result.already) email = "";
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Could not subscribe. Try again.";
    } finally {
      busy = false;
    }
  }
</script>

<section class="mx-auto mt-12 flex max-w-md flex-col gap-3 rounded-xl border border-border bg-card p-6 text-card-foreground">
  <div>
    <h2 class="text-xl font-semibold">Subscribe to the newsletter</h2>
    <p class="mt-1 text-sm text-muted-foreground">Single opt-in: a successful submit activates the address immediately.</p>
  </div>

  {#if !configured}
    <p class="rounded-md border border-border bg-muted/40 p-3 text-sm text-muted-foreground" role="status">
      Configure the newsletter adapter before rendering this form.
    </p>
  {/if}

  <form class="flex flex-col gap-3" onsubmit={(event) => { event.preventDefault(); void submit(); }}>
    <label class="grid gap-1 text-sm" for="newsletter-email-svelte">Email</label>
    <input
      id="newsletter-email-svelte"
      class="h-9 rounded-md border border-input bg-background px-3 text-sm"
      type="email"
      required
      autocomplete="email"
      bind:value={email}
      placeholder="you@domain.com"
    />
    <label class="sr-only" aria-hidden="true">
      Website
      <input tabindex="-1" autocomplete="off" bind:value={website} />
    </label>
    <button
      class="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:pointer-events-none disabled:opacity-50"
      type="submit"
      disabled={busy || !configured}
    >{busy ? "Subscribing…" : "Subscribe"}</button>
    {#if message}<p class="text-sm text-emerald-600" role="status">{message}</p>{/if}
    {#if error}<p class="text-sm text-destructive" role="alert">{error}</p>{/if}
  </form>
</section>
