// frontend/slices/payment-svelte/variants/doku/components/DokuStatusBadge.svelte
<script lang="ts">
  import { DOKU_STATUS_LABEL } from "@/features/payment/lib/doku-core";
  import type { DokuStatus } from "@/features/payment/lib/contracts";

  let {
    status,
    onResync = undefined,
  } = $props<{
    status: DokuStatus;
    onResync?: () => void | Promise<unknown>;
  }>();

  const statusClass: Record<DokuStatus, string> = {
    pending: "bg-secondary text-secondary-foreground",
    client_claimed: "bg-secondary text-secondary-foreground",
    paid: "bg-primary text-primary-foreground",
    failed: "bg-destructive text-destructive-foreground",
    expired: "border bg-background text-foreground",
    refunded: "border bg-background text-foreground",
  };
</script>

<div class="flex items-center gap-2">
  <span class={`rounded-full px-2.5 py-1 text-xs font-medium ${statusClass[status]}`}>{DOKU_STATUS_LABEL[status]}</span>
  {#if status === "pending" && onResync}
    <button type="button" onclick={() => void onResync?.()} class="rounded-md px-2 py-1 text-xs hover:bg-accent">Cek ulang</button>
  {/if}
</div>

// frontend/slices/doku-payment/components/DokuStatusBadge.tsx
"use client";

/**
 * Live status badge — props-driven so the slice stays Convex-free at the
 * type-checking level. Consumer feeds `status` from a Convex reactive
 * query, and optionally `onResync` from an action.
 *
 *   const order = useQuery(api.features.payment.queries.getOrderByOrderId, { orderId });
 *   const sync = useAction(api.features.payment.actions.doku.getPaymentStatus);
 *   <DokuStatusBadge
 *     status={order?.status ?? "pending"}
 *     onResync={() => sync({ orderId })}
 *   />
 */

import * as React from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export type DokuStatus =
  | "pending"
  | "client_claimed"
  | "paid"
  | "failed"
  | "expired"
  | "refunded";

const VARIANT: Record<DokuStatus, "default" | "secondary" | "destructive" | "outline"> = {
  pending: "secondary",
  client_claimed: "secondary",
  paid: "default",
  failed: "destructive",
  expired: "outline",
  refunded: "outline",
};

const LABEL: Record<DokuStatus, string> = {
  pending: "Menunggu pembayaran",
  client_claimed: "Menunggu konfirmasi",
  paid: "Lunas",
  failed: "Gagal",
  expired: "Kedaluwarsa",
  refunded: "Dikembalikan",
};

interface Props {
  status: DokuStatus;
  onResync?: () => void | Promise<unknown>;
}

export function DokuStatusBadge({ status, onResync }: Props) {
  return (
    <div className="flex items-center gap-2">
      <Badge variant={VARIANT[status]}>{LABEL[status]}</Badge>
      {status === "pending" && onResync && (
        <Button size="sm" variant="ghost" onClick={() => void onResync()}>
          Cek ulang
        </Button>
      )}
    </div>
  );
}
