// frontend/slices/data-table/components/DataTable.tsx
"use client";

import * as React from "react";
import {
  type ColumnDef,
  type ColumnFiltersState,
  type SortingState,
  type VisibilityState,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
} from "@tanstack/react-table";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";

import { DataTablePagination } from "./data-table-pagination";
import { DataTableToolbar } from "./data-table-toolbar";
import {
  dataTableCellPadding,
  resolveDataTableLabels,
  type DataTableDensity,
  type DataTableLabels,
} from "../lib/core";
import { selectionColumn } from "../lib/columns-helpers";

export interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[];
  data: TData[];
  density?: DataTableDensity;
  selectable?: boolean;
  searchKey?: string;
  searchPlaceholder?: string;
  pageSize?: number;
  labels?: Partial<DataTableLabels>;
  className?: string;
}

export function DataTable<TData, TValue>({
  columns,
  data,
  density = "comfortable",
  selectable = false,
  searchKey,
  searchPlaceholder,
  pageSize = 10,
  labels,
  className,
}: DataTableProps<TData, TValue>) {
  const [sorting, setSorting] = React.useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = React.useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = React.useState({});
  const resolvedLabels = React.useMemo(() => resolveDataTableLabels(labels), [labels]);

  const resolvedColumns = React.useMemo(
    () =>
      selectable
        ? [selectionColumn<TData>(resolvedLabels) as ColumnDef<TData, TValue>, ...columns]
        : columns,
    [columns, resolvedLabels, selectable],
  );

  const table = useReactTable({
    data,
    columns: resolvedColumns,
    state: { sorting, columnFilters, columnVisibility, rowSelection },
    enableRowSelection: selectable,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    initialState: { pagination: { pageSize } },
  });

  const cellPad = dataTableCellPadding(density);

  return (
    <div className={cn("w-full", className)}>
      <DataTableToolbar
        table={table}
        searchKey={searchKey}
        searchPlaceholder={searchPlaceholder}
        labels={resolvedLabels}
      />
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((group) => (
              <TableRow key={group.id}>
                {group.headers.map((header) => (
                  <TableHead key={header.id} className={cellPad}>
                    {header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows.length ? (
              table.getRowModel().rows.map((row) => (
                <TableRow key={row.id} data-state={row.getIsSelected() && "selected"}>
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id} className={cellPad}>
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell colSpan={resolvedColumns.length} className="h-24 text-center text-sm text-muted-foreground">
                  {resolvedLabels.noResults}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
      <DataTablePagination table={table} selectable={selectable} labels={resolvedLabels} />
    </div>
  );
}

// frontend/slices/data-table-svelte/components/DataTable.svelte
<script lang="ts" generics="TData extends RowData">
  import { untrack } from "svelte";
  import { createTable, FlexRender, type RowData } from "@tanstack/svelte-table";
  import {
    dataTableCellPadding,
    resolveDataTableLabels,
    type DataTableDensity,
    type DataTableLabels,
  } from "../../data-table/lib/core";
  import DataTablePagination from "./DataTablePagination.svelte";
  import DataTableToolbar from "./DataTableToolbar.svelte";
  import { dataTableFeatures, type DataTableColumn } from "../lib/table";

  type Props = {
    columns: DataTableColumn<TData>[];
    data: TData[];
    density?: DataTableDensity;
    selectable?: boolean;
    searchKey?: string;
    searchPlaceholder?: string;
    pageSize?: number;
    labels?: Partial<DataTableLabels>;
    class?: string;
  };

  let {
    columns,
    data,
    density = "comfortable",
    selectable = false,
    searchKey,
    searchPlaceholder,
    pageSize = 10,
    labels,
    class: className = "",
  }: Props = $props();

  const table = createTable({
    features: dataTableFeatures,
    get data() {
      return data;
    },
    get columns() {
      return columns;
    },
    get enableRowSelection() {
      return selectable;
    },
    initialState: { pagination: { pageIndex: 0, pageSize: untrack(() => pageSize) } },
  });

  let resolvedLabels = $derived(resolveDataTableLabels(labels));
  let cellPadding = $derived(dataTableCellPadding(density));
  let state = $derived(table.store.get());
  let headerGroups = $derived.by(() => {
    void state;
    return table.getHeaderGroups();
  });
  let rows = $derived.by(() => {
    void state;
    return table.getRowModel().rows;
  });
  let allPageSelected = $derived.by(() => {
    void state;
    return table.getIsAllPageRowsSelected();
  });
  let somePageSelected = $derived.by(() => {
    void state;
    return table.getIsSomePageRowsSelected();
  });
</script>

<div class={`w-full ${className}`.trim()}>
  <DataTableToolbar
    {table}
    {searchKey}
    {searchPlaceholder}
    labels={resolvedLabels}
  />

  <div class="overflow-x-auto rounded-md border">
    <table class="w-full caption-bottom text-sm">
      <thead class="[&_tr]:border-b">
        {#each headerGroups as headerGroup (headerGroup.id)}
          <tr class="border-b transition-colors">
            {#if selectable}
              <th class={`h-10 px-2 text-left align-middle ${cellPadding}`}>
                <button
                  type="button"
                  role="checkbox"
                  aria-label={resolvedLabels.selectAllRows}
                  aria-checked={somePageSelected && !allPageSelected ? "mixed" : allPageSelected}
                  class="inline-grid size-4 place-items-center rounded border border-input text-[10px]"
                  onclick={() => table.toggleAllPageRowsSelected(!allPageSelected)}
                >
                  {allPageSelected ? "✓" : somePageSelected ? "−" : ""}
                </button>
              </th>
            {/if}
            {#each headerGroup.headers as header (header.id)}
              <th class={`h-10 px-2 text-left align-middle font-medium text-foreground ${cellPadding}`}>
                {#if !header.isPlaceholder}
                  {#if header.column.getCanSort()}
                    <button
                      type="button"
                      class="-ml-2 inline-flex h-7 items-center gap-1 rounded px-2 text-xs font-medium hover:bg-accent"
                      onclick={header.column.getToggleSortingHandler()}
                    >
                      <FlexRender header={header} />
                      <span aria-hidden="true" class:opacity-50={!header.column.getIsSorted()}>
                        {header.column.getIsSorted() === "asc"
                          ? "↑"
                          : header.column.getIsSorted() === "desc"
                            ? "↓"
                            : "↕"}
                      </span>
                    </button>
                  {:else}
                    <FlexRender header={header} />
                  {/if}
                {/if}
              </th>
            {/each}
          </tr>
        {/each}
      </thead>
      <tbody class="[&_tr:last-child]:border-0">
        {#if rows.length}
          {#each rows as row (row.id)}
            <tr class="border-b transition-colors hover:bg-muted/50" data-state={row.getIsSelected() ? "selected" : undefined}>
              {#if selectable}
                <td class={`px-2 align-middle ${cellPadding}`}>
                  <input
                    type="checkbox"
                    aria-label={resolvedLabels.selectRow}
                    checked={row.getIsSelected()}
                    onchange={(event) => row.toggleSelected(event.currentTarget.checked)}
                  />
                </td>
              {/if}
              {#each row.getVisibleCells() as cell (cell.id)}
                <td class={`px-2 align-middle ${cellPadding}`}>
                  <FlexRender {cell} />
                </td>
              {/each}
            </tr>
          {/each}
        {:else}
          <tr>
            <td
              colspan={columns.length + (selectable ? 1 : 0)}
              class="h-24 px-2 text-center text-sm text-muted-foreground"
            >
              {resolvedLabels.noResults}
            </td>
          </tr>
        {/if}
      </tbody>
    </table>
  </div>

  <DataTablePagination {table} {selectable} labels={resolvedLabels} />
</div>
