// frontend/slices/data-table/components/data-table-pagination.tsx
"use client";

import type { Table } from "@tanstack/react-table";
import { ChevronLeft, ChevronRight } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  dataTablePageSummary,
  dataTableRowSummary,
  type DataTableLabels,
} from "../lib/core";

export interface DataTablePaginationProps<TData> {
  table: Table<TData>;
  selectable?: boolean;
  labels: DataTableLabels;
}

export function DataTablePagination<TData>({
  table,
  selectable = false,
  labels,
}: DataTablePaginationProps<TData>) {
  const pageIndex = table.getState().pagination.pageIndex;
  const pageCount = table.getPageCount();
  const filtered = table.getFilteredRowModel().rows.length;
  const selected = table.getFilteredSelectedRowModel().rows.length;

  return (
    <div className="flex items-center justify-between gap-4 px-1 py-2">
      <div className="text-xs text-muted-foreground">
        {dataTableRowSummary(filtered, selected, selectable, labels)}
      </div>
      <div className="flex items-center gap-4">
        <span className="text-xs font-medium text-muted-foreground">
          {dataTablePageSummary(pageIndex, pageCount, labels)}
        </span>
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-8"
            onClick={() => table.previousPage()}
            disabled={!table.getCanPreviousPage()}
          >
            <ChevronLeft className="size-4" />
            {labels.previous}
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="h-8"
            onClick={() => table.nextPage()}
            disabled={!table.getCanNextPage()}
          >
            {labels.next}
            <ChevronRight className="size-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}

// frontend/slices/data-table-svelte/components/DataTablePagination.svelte
<script lang="ts" generics="TData extends RowData">
  import type { RowData } from "@tanstack/svelte-table";
  import {
    dataTablePageSummary,
    dataTableRowSummary,
    type DataTableLabels,
  } from "../../data-table/lib/core";
  import type { DataTableInstance } from "../lib/table";

  type Props = {
    table: DataTableInstance<TData>;
    selectable?: boolean;
    labels: DataTableLabels;
  };

  let { table, selectable = false, labels }: Props = $props();
  let pagination = $derived(table.atoms.pagination.get());
  let filters = $derived(table.atoms.columnFilters.get());
  let selection = $derived(table.atoms.rowSelection.get());
  let filteredCount = $derived.by(() => {
    void filters;
    return table.getFilteredRowModel().rows.length;
  });
  let selectedCount = $derived.by(() => {
    void selection;
    void filters;
    return table.getFilteredSelectedRowModel().rows.length;
  });
  let pageCount = $derived.by(() => {
    void pagination;
    void filters;
    return table.getPageCount();
  });
</script>

<div class="flex flex-wrap items-center justify-between gap-3 px-1 py-2">
  <div class="text-xs text-muted-foreground">
    {dataTableRowSummary(filteredCount, selectedCount, selectable, labels)}
  </div>
  <div class="flex flex-wrap items-center gap-3">
    <span class="text-xs font-medium text-muted-foreground">
      {dataTablePageSummary(pagination.pageIndex, pageCount, labels)}
    </span>
    <div class="flex items-center gap-1">
      <button
        type="button"
        class="h-8 rounded-md border border-input px-3 text-xs font-medium hover:bg-accent disabled:pointer-events-none disabled:opacity-50"
        onclick={() => table.previousPage()}
        disabled={!table.getCanPreviousPage()}
      >
        ← {labels.previous}
      </button>
      <button
        type="button"
        class="h-8 rounded-md border border-input px-3 text-xs font-medium hover:bg-accent disabled:pointer-events-none disabled:opacity-50"
        onclick={() => table.nextPage()}
        disabled={!table.getCanNextPage()}
      >
        {labels.next} →
      </button>
    </div>
  </div>
</div>
