// frontend/slices/image-editor-svelte/components/LayersPanel.svelte
<script lang="ts">
  import type { BrowserEditorCore, EditorSnapshot } from "@/features/image-editor/lib/editor-core";
  let { editor, snapshot } = $props<{ editor: BrowserEditorCore; snapshot: EditorSnapshot }>();
  let topFirst = $derived([...snapshot.doc.layers].reverse());
  const glyph=(kind:string)=>({image:"🖼️",text:"T",shape:"◆",paint:"🎨",adjustment:"☼"}[kind]??"◻");
</script>
<section class="flex min-h-0 flex-col border-t">
  <header class="flex items-center border-b px-3 py-2"><strong class="text-xs uppercase tracking-wide text-muted-foreground">Layers</strong><span class="ml-auto text-[10px] text-muted-foreground">{snapshot.doc.layers.length}</span></header>
  <div class="min-h-0 flex-1 overflow-y-auto p-1">
    {#each topFirst as layer (layer.id)}
      <div class={`flex items-center gap-1 rounded hover:bg-muted ${snapshot.selectedId===layer.id?"bg-muted font-medium":""}`}>
        <button class="flex min-w-0 flex-1 items-center gap-1.5 px-2 py-1.5 text-left text-xs" onclick={()=>editor.select(layer.id)}>
          <span aria-hidden="true">{glyph(layer.kind)}</span><span class="min-w-0 flex-1 truncate">{layer.name}</span><span class="text-[10px] text-muted-foreground">{Math.round(layer.opacity*100)}%</span>
        </button>
        <button class="rounded px-1 text-[10px]" title={layer.visible?"Hide layer":"Show layer"} aria-label={layer.visible?"Hide layer":"Show layer"} onclick={()=>editor.update(layer.id,{visible:!layer.visible})}>{layer.visible?"👁":"—"}</button>
        <button class="mr-1 rounded px-1 text-[10px]" title={layer.locked?"Unlock layer":"Lock layer"} aria-label={layer.locked?"Unlock layer":"Lock layer"} onclick={()=>editor.update(layer.id,{locked:!layer.locked})}>{layer.locked?"🔒":"🔓"}</button>
      </div>
    {/each}
  </div>
  <footer class="grid grid-cols-4 gap-1 border-t p-1.5">
    <button class="rounded border px-1 py-1 text-[10px] disabled:opacity-30" disabled={!snapshot.selectedId} onclick={()=>snapshot.selectedId&&editor.raise(snapshot.selectedId)}>↑</button>
    <button class="rounded border px-1 py-1 text-[10px] disabled:opacity-30" disabled={!snapshot.selectedId} onclick={()=>snapshot.selectedId&&editor.lower(snapshot.selectedId)}>↓</button>
    <button class="rounded border px-1 py-1 text-[10px] disabled:opacity-30" disabled={!snapshot.selectedId} onclick={()=>snapshot.selectedId&&editor.duplicateLayer(snapshot.selectedId)}>Copy</button>
    <button class="rounded border px-1 py-1 text-[10px] text-destructive disabled:opacity-30" disabled={!snapshot.selectedId} onclick={()=>snapshot.selectedId&&editor.removeLayer(snapshot.selectedId)}>Delete</button>
  </footer>
</section>

// frontend/slices/image-editor/components/panels/layers-panel.tsx
"use client";

import { useState } from "react";
import { Eye, EyeOff, GripVertical, Lock, SquareDashed } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { useEditor } from "../../lib/store";
import type { Layer } from "../../lib/types";
import { LayerThumb } from "./layer-thumb";
import { LayerActionsMenu } from "./layer-actions-menu";

const KIND_LABEL: Record<Layer["kind"], string> = {
  image: "IMG",
  text: "TEXT",
  shape: "SHAPE",
  paint: "PIXEL",
  adjustment: "ADJ",
};
import { LayersHeader } from "./layers-header";
import { LayersFooter } from "./layers-footer";

// Compact, Photoshop-style Layers panel:
//   header  → blend + opacity (selected layer)
//   rows    → [eye | thumbnail | name | ⋮ actions]  (drag to reorder)
//   footer  → New ▾ / Duplicate / Crop / Delete action bar
// Per-row controls collapse to the eye (left) + the kebab menu (right) so the
// list reads dense like Photoshop; everything else lives in header/footer/menu.
export function LayersPanel() {
  const ed = useEditor();
  const { doc, selectedId } = ed;
  const [editing, setEditing] = useState<string | null>(null);
  const [dragIdx, setDragIdx] = useState<number | null>(null);
  const [overIdx, setOverIdx] = useState<number | null>(null);

  const rows = [...doc.layers].reverse();
  const toReal = (display: number) => doc.layers.length - 1 - display;
  const resetDrag = () => { setDragIdx(null); setOverIdx(null); };
  const onDrop = (to: number) => {
    if (dragIdx !== null && dragIdx !== to) ed.reorder(toReal(dragIdx), toReal(to));
    resetDrag();
  };

  return (
    <div className="flex h-full flex-col bg-card text-foreground">
      <LayersHeader />

      <ScrollArea className="min-h-0 flex-1">
        <div className="flex flex-col">
          {rows.map((l: Layer, di: number) => {
            const isSel = l.id === selectedId;
            const isOver = overIdx === di && dragIdx !== null && dragIdx !== di;
            return (
              <div
                key={l.id}
                draggable
                onDragStart={() => setDragIdx(di)}
                onDragOver={(e) => { e.preventDefault(); if (overIdx !== di) setOverIdx(di); }}
                onDrop={(e) => { e.preventDefault(); onDrop(di); }}
                onDragEnd={resetDrag}
                onClick={() => ed.select(l.id)}
                className={cn(
                  "flex cursor-pointer items-center gap-2 border-b border-border px-1.5 py-1 hover:bg-accent/50",
                  isSel && "bg-accent",
                  isOver && "ring-2 ring-inset ring-primary",
                )}
              >
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  aria-label={l.visible ? "Hide" : "Show"}
                  onClick={(e) => { e.stopPropagation(); ed.update(l.id, { visible: !l.visible }); }}
                  className="grid size-6 h-auto shrink-0 place-items-center rounded text-muted-foreground hover:text-foreground"
                >
                  {l.visible ? <Eye className="size-4" /> : <EyeOff className="size-4 opacity-60" />}
                </Button>
                <LayerThumb layer={l} />
                {editing === l.id ? (
                  <Input
                    autoFocus
                    draggable={false}
                    defaultValue={l.name}
                    className="h-6 flex-1 text-xs"
                    onClick={(e) => e.stopPropagation()}
                    onDragStart={(e) => e.stopPropagation()}
                    onBlur={(e) => { ed.update(l.id, { name: e.target.value }); setEditing(null); }}
                    onKeyDown={(e) => {
                      if (e.key !== "Enter") return;
                      ed.update(l.id, { name: (e.target as HTMLInputElement).value });
                      setEditing(null);
                    }}
                  />
                ) : (
                  <span
                    className="flex-1 truncate text-xs"
                    onDoubleClick={(e) => { e.stopPropagation(); setEditing(l.id); }}
                  >
                    {l.name}
                  </span>
                )}
                <span className="shrink-0 rounded bg-muted px-1 text-[9px] font-semibold tracking-wide text-muted-foreground">
                  {KIND_LABEL[l.kind]}
                </span>
                {l.mask && (
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    aria-label="Edit mask"
                    onClick={(e) => { e.stopPropagation(); ed.setMaskEdit(ed.maskEditId === l.id ? null : l.id); }}
                    className={cn(
                      "grid size-5 h-auto shrink-0 place-items-center rounded",
                      ed.maskEditId === l.id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground",
                    )}
                  >
                    <SquareDashed className="size-3.5" />
                  </Button>
                )}
                {l.locked && <Lock className="size-3 shrink-0 text-muted-foreground" />}
                <span onClick={(e) => e.stopPropagation()}>
                  <LayerActionsMenu layer={l} onRename={() => setEditing(l.id)} />
                </span>
              </div>
            );
          })}
        </div>
      </ScrollArea>

      <LayersFooter />
    </div>
  );
}
