// frontend/slices/payment-svelte/variants/doku/components/DokuDirectForm.svelte
<script lang="ts">
  import {
    GROUP_LABELS,
    groupDokuChannels,
    formatIDR,
    type ChannelGroup,
  } from "@/features/payment/lib/doku-core";
  import type {
    DokuDirectInput,
    DokuDirectResult,
    PaymentCustomer,
    PaymentInstructions,
  } from "@/features/payment/lib/contracts";

  let {
    amount,
    orderId = undefined,
    defaultCustomer = {},
    allowedChannels = undefined,
    onSubmit = undefined,
    onSuccess = undefined,
  } = $props<{
    amount: number;
    orderId?: string;
    defaultCustomer?: Partial<PaymentCustomer>;
    allowedChannels?: string[];
    onSubmit?: (input: DokuDirectInput) => Promise<DokuDirectResult>;
    onSuccess?: (result: {
      orderId?: string;
      channel: string;
      instructions: PaymentInstructions;
      expiresAt?: number;
    }) => void;
  }>();

  let channel = $state("QRIS");
  let name = $state("");
  let email = $state("");
  let phone = $state("");
  let loading = $state(false);
  let error = $state<string | null>(null);
  let groups = $derived(groupDokuChannels(allowedChannels));

  $effect(() => {
    name = defaultCustomer.name ?? "";
    email = defaultCustomer.email ?? "";
    phone = defaultCustomer.phone ?? "";
  });

  $effect(() => {
    const available = Object.values(groups).flat();
    if (!available.some((item) => item.id === channel)) channel = available[0]?.id ?? "";
  });

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    if (!channel) {
      error = "Tidak ada metode pembayaran yang tersedia";
      return;
    }
    if (!onSubmit) {
      alert(`(stub) DOKU Direct for ${channel} ${formatIDR(amount)}`);
      return;
    }
    loading = true;
    error = null;
    try {
      const result = await onSubmit({
        orderId,
        amount,
        channel,
        customer: { name, email, phone: phone || undefined },
      });
      if ("ok" in result && result.ok === false) {
        error = result.notice;
        return;
      }
      onSuccess?.({
        orderId: result.orderId ?? orderId,
        channel,
        instructions: result.instructions,
        expiresAt: result.expiresAt,
      });
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Gagal membuat pembayaran";
    } finally {
      loading = false;
    }
  }
</script>

<section class="flex flex-col gap-4 rounded-xl border bg-card p-4 text-card-foreground shadow-sm">
  <header>
    {#if orderId}<div class="text-sm text-muted-foreground">Order {orderId}</div>{/if}
    <div class="text-2xl font-semibold">{formatIDR(amount)}</div>
  </header>

  <form onsubmit={submit} class="flex flex-col gap-3">
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
      <label class="flex flex-col gap-1.5 text-sm">
        <span class="font-medium">Nama</span>
        <input bind:value={name} required class="h-10 rounded-md border bg-background px-3 outline-none focus:ring-2 focus:ring-ring" />
      </label>
      <label class="flex flex-col gap-1.5 text-sm">
        <span class="font-medium">Email</span>
        <input bind:value={email} type="email" required class="h-10 rounded-md border bg-background px-3 outline-none focus:ring-2 focus:ring-ring" />
      </label>
      <label class="flex flex-col gap-1.5 text-sm sm:col-span-2">
        <span class="font-medium">Nomor HP (opsional)</span>
        <input bind:value={phone} class="h-10 rounded-md border bg-background px-3 outline-none focus:ring-2 focus:ring-ring" />
      </label>
    </div>

    <label class="flex flex-col gap-1.5 text-sm">
      <span class="font-medium">Metode pembayaran</span>
      <select bind:value={channel} class="h-10 rounded-md border bg-background px-3">
        {#each Object.keys(groups) as group (group)}
          {@const id = group as ChannelGroup}
          {#if groups[id].length}
            <optgroup label={GROUP_LABELS[id]}>
              {#each groups[id] as item}
                <option value={item.id}>{item.label}</option>
              {/each}
            </optgroup>
          {/if}
        {/each}
      </select>
    </label>

    <button type="submit" disabled={loading || !channel} class="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50">
      {loading ? "Memproses…" : "Lanjut Bayar"}
    </button>
    {#if error}<p class="text-sm text-destructive" role="alert">{error}</p>{/if}
  </form>
</section>

// frontend/slices/payment/variants/doku/components/DokuDirectForm.tsx
"use client";

/**
 * Channel picker + minimal form for DOKU Direct.
 *
 * Convex-agnostic: caller passes `onSubmit` (typically wired to
 * `useAction(api.features.payment.actions.doku.createDirectPayment)` or a
 * server-side place-order action that creates the orderId itself).
 *
 * `orderId` is OPTIONAL — server-generated-orderId flows (guest checkout)
 * omit it; the submit handler then returns the generated id via
 * `DokuDirectResult.orderId`.
 */

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { GROUP_LABELS, groupDokuChannels, type ChannelGroup } from "../lib/channels";
import { formatIDR } from "../lib/format";
import type { DokuDirectInput, DokuDirectResult, PaymentCustomer, PaymentInstructions } from "@/features/payment/lib/contracts";
export type { DokuDirectInput, DokuDirectResult } from "@/features/payment/lib/contracts";

interface DokuDirectFormProps {
  amount: number;
  orderId?: string;
  defaultCustomer?: Partial<PaymentCustomer>;
  allowedChannels?: string[];
  /** Pass `useAction(api.features.payment.actions.doku.createDirectPayment)`. */
  onSubmit?: (input: DokuDirectInput) => Promise<DokuDirectResult>;
  onSuccess?: (result: {
    orderId?: string;
    channel: string;
    instructions: PaymentInstructions;
    expiresAt?: number;
  }) => void;
}

export function DokuDirectForm({
  amount,
  orderId,
  defaultCustomer,
  allowedChannels,
  onSubmit,
  onSuccess,
}: DokuDirectFormProps) {
  const [channel, setChannel] = React.useState<string>("QRIS");
  const [name, setName] = React.useState(defaultCustomer?.name ?? "");
  const [email, setEmail] = React.useState(defaultCustomer?.email ?? "");
  const [phone, setPhone] = React.useState(defaultCustomer?.phone ?? "");
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  const channels = React.useMemo(() => groupDokuChannels(allowedChannels), [allowedChannels]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!onSubmit) {
      alert(`(stub) DOKU Direct for ${channel} ${formatIDR(amount)}`);
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const res = await onSubmit({
        orderId,
        amount,
        channel,
        customer: { name, email, phone: phone || undefined },
      });
      if ("ok" in res && res.ok === false) {
        setError(res.notice);
        return;
      }
      onSuccess?.({
        orderId: res.orderId ?? orderId,
        channel,
        instructions: res.instructions,
        expiresAt: res.expiresAt,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Gagal membuat pembayaran");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="flex flex-col gap-4 p-4">
      <header className="flex items-baseline justify-between">
        <div>
          {orderId && <div className="text-sm text-muted-foreground">Order {orderId}</div>}
          <div className="text-2xl font-semibold">{formatIDR(amount)}</div>
        </div>
      </header>

      <form onSubmit={handleSubmit} className="flex flex-col gap-3">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="doku-name">Nama</Label>
            <Input id="doku-name" value={name} onChange={(e) => setName(e.target.value)} required />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="doku-email">Email</Label>
            <Input id="doku-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
          </div>
          <div className="flex flex-col gap-1.5 sm:col-span-2">
            <Label htmlFor="doku-phone">Nomor HP (opsional)</Label>
            <Input id="doku-phone" value={phone} onChange={(e) => setPhone(e.target.value)} />
          </div>
        </div>

        <div className="flex flex-col gap-1.5">
          <Label htmlFor="doku-channel">Metode pembayaran</Label>
          <Select value={channel} onValueChange={setChannel}>
            <SelectTrigger id="doku-channel" className="w-full">
              <SelectValue placeholder="Pilih metode" />
            </SelectTrigger>
            <SelectContent>
              {(Object.keys(channels) as ChannelGroup[]).map((g) =>
                channels[g].length > 0 ? (
                  <SelectGroup key={g}>
                    <SelectLabel>{GROUP_LABELS[g]}</SelectLabel>
                    {channels[g].map((c) => (
                      <SelectItem key={c.id} value={c.id}>
                        {c.label}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                ) : null,
              )}
            </SelectContent>
          </Select>
        </div>

        <Button type="submit" disabled={loading}>
          {loading ? "Memproses…" : "Lanjut Bayar"}
        </Button>
        {error && <p className="text-sm text-destructive">{error}</p>}
      </form>
    </Card>
  );
}
