// frontend/slices/sections-svelte/sections/PricingSection.svelte
<script lang="ts">
  import { cfgArray, cfgString, isPricingTier, parseConfigObject, type PricingTier } from "../../sections/sections/config";
  import type { LandingSection } from "../../sections/types";
  type Props = { section: LandingSection; tiers: PricingTier[]; featuredBadge?: string; eyebrow?: string; class?: string };
  let { section, tiers, featuredBadge = "Paling populer", eyebrow = "Harga", class: className = "" }: Props = $props();
  let cfg = $derived(parseConfigObject(section.config));
  let list = $derived(cfgArray(cfg, "tiers", isPricingTier) ?? tiers);
  let eyebrowText = $derived(cfgString(cfg, "eyebrow") ?? eyebrow);
</script>
{#if list.length}
<div class={`mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20 ${className}`.trim()}>
  <div class="text-center"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">{eyebrowText}</p><h2 class="mt-2 text-2xl font-semibold tracking-tight">{section.title}</h2>{#if section.subtitle}<p class="mt-2 text-sm text-muted-foreground">{section.subtitle}</p>{/if}</div>
  <div class="mx-auto mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{#each list as tier (tier.name)}<article class={`relative flex h-full flex-col gap-4 rounded-xl border bg-card/50 p-6 ${tier.featured ? "ring-1 ring-foreground/20 shadow-md" : "border-border/60"}`}>{#if tier.featured}<span class="absolute -top-3 left-5 rounded-full bg-primary px-2 py-1 text-xs text-primary-foreground">{featuredBadge}</span>{/if}<div><p class="text-sm font-medium uppercase tracking-wider text-muted-foreground">{tier.name}</p><p class="mt-2"><span class="text-3xl font-semibold">{tier.price}</span>{#if tier.period}<span class="text-sm text-muted-foreground"> {tier.period}</span>{/if}</p>{#if tier.blurb}<p class="mt-2 text-sm text-muted-foreground">{tier.blurb}</p>{/if}</div><ul class="flex-1 space-y-2 text-sm">{#each tier.features as feature (feature)}<li class="flex gap-2"><span>✓</span><span class="text-muted-foreground">{feature}</span></li>{/each}</ul>{#if tier.ctaHref}<a class={`rounded-md px-4 py-2 text-center text-sm font-medium ${tier.featured ? "bg-primary text-primary-foreground" : "border"}`} href={tier.ctaHref}>{tier.ctaLabel ?? "Pilih paket"} →</a>{/if}</article>{/each}</div>
</div>
{/if}

// frontend/slices/sections/sections/PricingSection.tsx
"use client";

import * as React from "react";
import { ArrowRight, Check } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { SectionHead } from "../components/SectionHead";
import { Stagger } from "../components/motion";
import {
  cfgArray,
  cfgString,
  isPricingTier,
  parseConfigObject,
  type PricingTier,
} from "./config";
import type { LandingSection } from "../types";

const GRID_COLS: Record<number, string> = {
  1: "max-w-md",
  2: "sm:grid-cols-2",
  3: "sm:grid-cols-2 lg:grid-cols-3",
  4: "sm:grid-cols-2 lg:grid-cols-4",
};

/**
 * Pricing tier cards — featured tier gets a ring + badge. Content
 * priority: section.config { tiers } > props.tiers. Renders inside
 * LandingSectionShell (caller wraps).
 */
export function PricingSection({
  section,
  tiers,
  featuredBadge = "Paling populer",
  eyebrow = "Harga",
  className,
}: {
  section: LandingSection;
  tiers: PricingTier[];
  featuredBadge?: string;
  /** Section eyebrow. Default "Harga"; override per-locale or via config.eyebrow. */
  eyebrow?: string;
  className?: string;
}) {
  const cfg = parseConfigObject(section.config);
  const list = cfgArray(cfg, "tiers", isPricingTier) ?? tiers;
  if (list.length === 0) return null;
  const cols = GRID_COLS[Math.min(list.length, 4)] ?? GRID_COLS[3];
  const eyebrowText = cfgString(cfg, "eyebrow") ?? eyebrow;

  return (
    <div className={cn("mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20", className)}>
      <SectionHead align="center" eyebrow={eyebrowText} title={section.title} subtitle={section.subtitle} />
      <div className={cn("mx-auto mt-10 grid gap-4", cols)}>
        <Stagger itemClassName="h-full">
          {list.map((t) => (
            <Card
              key={t.name}
              className={cn(
                "relative h-full border-border/60 bg-card/50 transition-[translate,box-shadow] duration-300 hover:-translate-y-1 hover:shadow-lg",
                t.featured && "border-foreground/30 ring-1 ring-foreground/20 shadow-md",
              )}
            >
              <CardContent className="flex h-full flex-col gap-4 p-6">
                {t.featured && (
                  <Badge className="absolute -top-2.5 left-5">{featuredBadge}</Badge>
                )}
                <div>
                  <p className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
                    {t.name}
                  </p>
                  <p className="mt-2 flex items-baseline gap-1">
                    <span className="text-3xl font-semibold tracking-tight">{t.price}</span>
                    {t.period && <span className="text-sm text-muted-foreground">{t.period}</span>}
                  </p>
                  {t.blurb && <p className="mt-2 text-sm text-muted-foreground">{t.blurb}</p>}
                </div>
                <ul className="flex-1 space-y-2 text-sm">
                  {t.features.map((f) => (
                    <li key={f} className="flex items-start gap-2">
                      <Check className="mt-0.5 size-4 shrink-0 text-foreground/70" />
                      <span className="text-muted-foreground">{f}</span>
                    </li>
                  ))}
                </ul>
                {t.ctaHref && (
                  <Button asChild variant={t.featured ? "default" : "outline"} className="w-full">
                    <a href={t.ctaHref}>
                      {t.ctaLabel ?? "Pilih paket"} <ArrowRight className="size-4" />
                    </a>
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </Stagger>
      </div>
    </div>
  );
}
