// frontend/slices/sections-svelte/sections/TestimonialsSection.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { cfgArray, cfgNumber, isTestimonialItem, parseConfigObject, type TestimonialItem } from "../../sections/sections/config";
  import type { LandingSection } from "../../sections/types";
  type Props = { section: LandingSection; items: TestimonialItem[]; eyebrow?: string; class?: string };
  let { section, items, eyebrow = "Testimoni", class: className = "" }: Props = $props();
  let cfg = $derived(parseConfigObject(section.config));
  let list = $derived((cfgArray(cfg, "items", isTestimonialItem) ?? items).slice(0, cfgNumber(cfg, "limit") ?? 9));
  let index = $state(0);
  let current = $derived(list.length ? list[index % list.length] : undefined);
  function move(delta: number) { if (list.length) index = (index + delta + list.length) % list.length; }
  onMount(() => { const timer = setInterval(() => move(1), 4500); return () => clearInterval(timer); });
</script>
{#if current}
<div class={`mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-20 ${className}`.trim()}>
  <div class="mb-6 flex items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">{eyebrow}</p><h2 class="mt-2 text-2xl font-semibold tracking-tight">{section.title}</h2>{#if section.subtitle}<p class="mt-2 text-sm text-muted-foreground">{section.subtitle}</p>{/if}</div><div class="flex gap-2"><button type="button" aria-label="Previous testimonial" class="rounded-full border px-3 py-2" onclick={() => move(-1)}>←</button><button type="button" aria-label="Next testimonial" class="rounded-full border px-3 py-2" onclick={() => move(1)}>→</button></div></div>
  <article class="rounded-xl border border-border/60 bg-card/50 p-6">
    {#if typeof current.rating === "number"}<p aria-label={`${current.rating} dari 5`} class="text-amber-500">{"★".repeat(Math.max(0, Math.min(5, current.rating)))}<span class="text-muted-foreground/30">{"★".repeat(Math.max(0, 5 - current.rating))}</span></p>{/if}
    <blockquote class="mt-3 text-base leading-relaxed text-muted-foreground">“{current.quote}”</blockquote><p class="mt-5 text-sm font-medium">{current.author}</p>{#if current.role}<p class="text-xs text-muted-foreground">{current.role}</p>{/if}
  </article><p class="mt-3 text-center text-xs text-muted-foreground">{index % list.length + 1} / {list.length}</p>
</div>
{/if}

// frontend/slices/sections/sections/TestimonialsSection.tsx
"use client";

import * as React from "react";
import Autoplay from "embla-carousel-autoplay";
import { Quote, Star } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import { cn } from "@/lib/utils";
import { SectionHead } from "../components/SectionHead";
import {
  cfgArray,
  cfgNumber,
  isTestimonialItem,
  parseConfigObject,
  type TestimonialItem,
} from "./config";
import type { LandingSection } from "../types";

/**
 * Testimonials carousel (autoplay, loop). Content priority:
 * section.config { items, limit } > props.items (template store data or
 * defaults). Renders inside LandingSectionShell (caller wraps).
 */
export function TestimonialsSection({
  section,
  items,
  eyebrow = "Testimoni",
  className,
}: {
  section: LandingSection;
  items: TestimonialItem[];
  eyebrow?: string;
  className?: string;
}) {
  const cfg = parseConfigObject(section.config);
  const limit = cfgNumber(cfg, "limit") ?? 9;
  const list = (cfgArray(cfg, "items", isTestimonialItem) ?? items).slice(0, limit);
  if (list.length === 0) return null;

  return (
    <div className={cn("mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20", className)}>
      <Carousel
        opts={{ align: "start", loop: list.length > 3 }}
        plugins={[Autoplay({ delay: 4500, stopOnInteraction: true })]}
      >
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
          <SectionHead
            eyebrow={eyebrow}
            title={section.title}
            subtitle={section.subtitle}
            className="mb-0"
          />
          <div className="flex items-center gap-2">
            <CarouselPrevious />
            <CarouselNext />
          </div>
        </div>
        <CarouselContent>
          {list.map((t, i) => (
            <CarouselItem key={`${t.author}-${i}`} className="basis-full sm:basis-1/2 lg:basis-1/3">
              <Card className="h-full border-border/60 bg-card/50">
                <CardContent className="flex h-full flex-col gap-3 p-5">
                  {typeof t.rating === "number" && (
                    <span className="inline-flex items-center gap-0.5" aria-label={`${t.rating} dari 5`}>
                      {Array.from({ length: 5 }).map((_, s) => (
                        <Star
                          key={s}
                          className={cn("size-4", s < (t.rating ?? 0) ? "fill-amber-400 text-amber-400" : "text-muted-foreground/40")}
                        />
                      ))}
                    </span>
                  )}
                  <div className="relative flex-1">
                    <Quote className="absolute -left-1 -top-1 size-3 text-muted-foreground/40" />
                    <p className="pl-3 text-sm leading-relaxed text-muted-foreground">{t.quote}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium">{t.author}</p>
                    {t.role && <p className="text-xs text-muted-foreground">{t.role}</p>}
                  </div>
                </CardContent>
              </Card>
            </CarouselItem>
          ))}
        </CarouselContent>
      </Carousel>
    </div>
  );
}
