// frontend/slices/admin-svelte/variants/console/components/AdminConsole.svelte
<script lang="ts">
  import { onMount, type Snippet } from "svelte";
  import {
    ADMIN_CONSOLE_SECTIONS,
    type AdminAccess,
    type AdminConsoleSection,
    type AdminTier,
  } from "@/features/admin/variants/console/lib/sections";
  import {
    canSeeAdmin,
    filterSections,
  } from "@/features/admin/variants/console/lib/access";
  import {
    groupSections,
    normalizeActiveSection,
    readSectionFromSearch,
    sectionHref,
  } from "@/features/admin/variants/console/lib/section-core";
  import AnalyticsDashboard from "./sections/AnalyticsDashboard.svelte";
  import AuditLogViewer from "./sections/AuditLogViewer.svelte";
  import LeadsInbox from "./sections/LeadsInbox.svelte";
  import NavConfigManager from "./sections/NavConfigManager.svelte";
  import SeoHealthPanel from "./sections/SeoHealthPanel.svelte";

  export type AdminPanelMap = Record<string, Snippet>;

  type Props = {
    access: AdminAccess;
    tier?: AdminTier;
    sections?: readonly AdminConsoleSection[];
    panels?: AdminPanelMap;
    activeId?: string;
    onNavigate?: (id: string) => void;
    header?: Snippet;
    nav?: boolean;
  };

  let {
    access,
    tier = "org",
    sections = ADMIN_CONSOLE_SECTIONS,
    panels = {},
    activeId,
    onNavigate,
    header,
    nav = true,
  }: Props = $props();

  let visible = $derived(filterSections(sections, access, tier));
  let internalActive = $state("");
  let active = $derived(activeId ?? normalizeActiveSection(visible, internalActive));
  let section = $derived(visible.find((item) => item.id === active));
  let groups = $derived(groupSections(visible));
  let injected = $derived(section ? panels[section.id] : undefined);

  $effect(() => {
    if (activeId !== undefined) return;
    const next = normalizeActiveSection(visible, internalActive);
    if (next !== internalActive) internalActive = next;
  });

  onMount(() => {
    if (activeId === undefined) {
      internalActive = normalizeActiveSection(
        visible,
        readSectionFromSearch(window.location.search),
      );
    }
    const onPop = () => {
      if (activeId !== undefined) return;
      internalActive = normalizeActiveSection(
        visible,
        readSectionFromSearch(window.location.search),
      );
    };
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  });

  function go(id: string) {
    onNavigate?.(id);
    if (activeId !== undefined) return;
    internalActive = id;
    if (typeof window !== "undefined") {
      window.history.pushState({}, "", sectionHref(window.location.href, id));
    }
  }
</script>

{#snippet body()}
  <main class="min-w-0 overflow-y-auto p-4">
    {#if section || header}
      <div class="mb-4 flex items-center justify-between gap-2">
        <h2 class="text-lg font-semibold tracking-tight">{section?.label ?? "Admin"}</h2>
        {#if header}{@render header()}{/if}
      </div>
    {/if}

    {#if !section}
      <p class="text-sm text-muted-foreground">Select a section.</p>
    {:else if injected}
      {@render injected()}
    {:else if section.id === "analytics"}
      <AnalyticsDashboard />
    {:else if section.id === "audit-log"}
      <AuditLogViewer />
    {:else if section.id === "nav-config"}
      <NavConfigManager />
    {:else if section.id === "seo-health"}
      <SeoHealthPanel />
    {:else if section.id === "leads"}
      <LeadsInbox />
    {:else}
      <div class="rounded-lg border border-dashed p-8 text-center">
        <p class="text-sm font-medium">{section.label} not mounted</p>
        <p class="mt-1 text-xs text-muted-foreground">
          Install the <code>{section.provider}</code> slice and pass a Svelte snippet via
          <code>panels["{section.id}"]</code>.
        </p>
      </div>
    {/if}
  </main>
{/snippet}

{#if access.isLoading}
  <div class="flex h-full items-center justify-center text-sm text-muted-foreground">Loading…</div>
{:else if !canSeeAdmin(access)}
  <div class="flex h-full flex-col items-center justify-center gap-2 p-8 text-center">
    <p class="text-sm font-medium">Admin console unavailable</p>
    <p class="max-w-md text-xs text-muted-foreground">
      You don't have admin access. Ask an owner to grant a permission, or configure
      <code>PLATFORM_ADMIN_EMAILS</code> on the backend.
    </p>
  </div>
{:else if !nav}
  {@render body()}
{:else}
  <div class="grid h-full w-full min-w-0 grid-cols-[220px_minmax(0,1fr)]">
    <nav class="overflow-y-auto border-r bg-muted/30 p-2" aria-label="Admin sections">
      {#each groups as group (group.id)}
        <div class="mb-3">
          <p class="px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{group.id}</p>
          {#each group.items as item (item.id)}
            <button
              type="button"
              class={`flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm ${item.id === active ? "bg-accent font-medium" : "hover:bg-accent/60"}`}
              aria-current={item.id === active ? "page" : undefined}
              onclick={() => go(item.id)}
            >
              <span class="grid size-5 shrink-0 place-items-center rounded bg-muted text-[10px]" title={item.icon}>{item.label.slice(0, 1)}</span>
              <span class="min-w-0 flex-1 truncate">{item.label}</span>
              {#if item.provider === "self"}<span class="rounded-full border px-1 text-[9px]">new</span>{/if}
            </button>
          {/each}
        </div>
      {/each}
    </nav>
    {@render body()}
  </div>
{/if}

// frontend/slices/admin-console/components/AdminConsole.tsx
"use client"

import * as React from "react"
import * as Icons from "lucide-react"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import {
  ADMIN_CONSOLE_SECTIONS,
  type AdminAccess,
  type AdminConsoleSection,
  type AdminTier,
} from "../lib/sections"
import { canSeeAdmin, filterSections } from "../lib/access"
import { useAdminSection } from "../hooks/useAdminSection"
import { AnalyticsDashboard } from "./sections/AnalyticsDashboard"
import { AuditLogViewer } from "./sections/AuditLogViewer"
import { NavConfigManager } from "./sections/NavConfigManager"
import { LeadsInbox } from "./sections/LeadsInbox"
import { SeoHealthPanel } from "./sections/SeoHealthPanel"

/** The 5 gap sections this slice owns, wired with mock defaults. */
const OWNED: Record<string, React.ReactNode> = {
  analytics: <AnalyticsDashboard />,
  "audit-log": <AuditLogViewer />,
  "nav-config": <NavConfigManager />,
  "seo-health": <SeoHealthPanel />,
  leads: <LeadsInbox />,
}

export interface AdminConsoleProps {
  /** Injected access — consumer's useAdminAccess result or a mock. */
  access: AdminAccess
  tier?: AdminTier
  /** Section catalog. Defaults to the harvested ADMIN_CONSOLE_SECTIONS. */
  sections?: readonly AdminConsoleSection[]
  /**
   * Consumer-supplied nodes for reuse sections (id → element), e.g.
   * `{ users: <UsersPanel/> }` from the installed user-management slice.
   * Also overrides an owned section when you want to pass real data.
   */
  components?: Record<string, React.ReactNode>
  /** Controlled active section id (omit for internal URL-synced state). */
  activeId?: string
  onNavigate?: (id: string) => void
}

function icon(name: string) {
  const I = (Icons as unknown as Record<string, React.ComponentType<{ className?: string }>>)[name]
  return I ?? Icons.Square
}

/**
 * Admin Console — the composed admin panel. Left: gated section nav grouped by
 * area. Right: the active section — an owned gap component, a consumer-mounted
 * reuse component, or a "not installed" hint naming the slice that supplies it.
 *
 * Renders no app chrome of its own; mount inside your dashboard shell.
 */
export function AdminConsole({
  access,
  tier = "org",
  sections = ADMIN_CONSOLE_SECTIONS,
  components,
  activeId,
  onNavigate,
}: AdminConsoleProps) {
  const visible = React.useMemo(() => filterSections(sections, access, tier), [sections, access, tier])
  const internal = useAdminSection(visible)
  const active = activeId ?? internal.activeId
  const go = (id: string) => {
    onNavigate?.(id)
    if (!activeId) internal.navigate(id)
  }

  if (access.isLoading) {
    return <div className="flex h-full items-center justify-center text-sm text-muted-foreground">Loading…</div>
  }
  if (!canSeeAdmin(access)) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-2 p-8 text-center">
        <p className="text-sm font-medium">Admin console unavailable</p>
        <p className="max-w-md text-xs text-muted-foreground">
          You don&apos;t have admin access. Ask an owner to grant a permission, or set{" "}
          <code>PLATFORM_ADMIN_EMAILS</code> on the backend.
        </p>
      </div>
    )
  }

  const section = visible.find((s) => s.id === active)
  const groups = Array.from(new Set(visible.map((s) => s.group)))

  return (
    <div className="grid h-full w-full grid-cols-[220px_1fr]">
      <nav className="border-r bg-muted/30">
        <ScrollArea className="h-full p-2">
          {groups.map((g) => (
            <div key={g} className="mb-3">
              <p className="px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{g}</p>
              {visible
                .filter((s) => s.group === g)
                .map((s) => {
                  const Ic = icon(s.icon)
                  return (
                    <Button
                      key={s.id}
                      variant="ghost"
                      onClick={() => go(s.id)}
                      className={cn(
                        "h-auto w-full justify-start gap-2 px-2 py-1.5 font-normal",
                        s.id === active && "bg-accent font-medium",
                      )}
                    >
                      <Ic className="size-4 shrink-0" />
                      <span className="flex-1 text-left">{s.label}</span>
                      {s.provider === "self" && (
                        <Badge variant="secondary" className="px-1 py-0 text-[9px]">
                          new
                        </Badge>
                      )}
                    </Button>
                  )
                })}
            </div>
          ))}
        </ScrollArea>
      </nav>

      <main className="overflow-y-auto p-4">
        {section && (
          <div className="mb-4">
            <h2 className="text-lg font-semibold tracking-tight">{section.label}</h2>
          </div>
        )}
        <SectionBody section={section} components={components} />
      </main>
    </div>
  )
}

function SectionBody({
  section,
  components,
}: {
  section?: AdminConsoleSection
  components?: Record<string, React.ReactNode>
}) {
  if (!section) return <p className="text-sm text-muted-foreground">Select a section.</p>
  const override = components?.[section.id]
  if (override !== undefined) return <>{override}</>
  if (section.provider === "self") return <>{OWNED[section.id]}</>
  return (
    <div className="rounded-lg border border-dashed p-8 text-center">
      <p className="text-sm font-medium">{section.label} not mounted</p>
      <p className="mt-1 text-xs text-muted-foreground">
        Install the <code>{section.provider}</code> slice and pass its panel via{" "}
        <code>components={`{{ "${section.id}": <Panel/> }}`}</code>.
      </p>
    </div>
  )
}
