// frontend/slices/rbac-roles/components/PermissionMatrix.tsx
"use client";

// Grouped permission checkbox grid. Drives role create/edit (set
// `onChange`) or read-only role inspection (`readOnly`). A role holding
// `*` shows every box checked + disabled.

import { cn } from "@/lib/utils";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { matchPermission } from "../lib/permissions";
import { PERMISSION_GROUPS, type PermissionGroup } from "../lib/permission-catalog";

interface PermissionMatrixProps {
  value: readonly string[];
  onChange?: (next: string[]) => void;
  groups?: PermissionGroup[];
  readOnly?: boolean;
  className?: string;
}

export function PermissionMatrix({
  value, onChange, groups = PERMISSION_GROUPS, readOnly, className,
}: PermissionMatrixProps) {
  const isSuper = value.includes("*");
  const checked = (key: string) => isSuper || value.some((p) => matchPermission(p, key));
  const locked = readOnly || isSuper || !onChange;

  const toggle = (key: string, on: boolean) => {
    if (locked) return;
    onChange?.(on ? [...new Set([...value, key])] : value.filter((p) => p !== key));
  };

  return (
    <div className={cn("space-y-4", className)}>
      {groups.map((g) => (
        <div key={g.group} className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{g.group}</p>
          <div className="grid gap-2 sm:grid-cols-2">
            {g.permissions.map((perm) => {
              const id = `perm-${perm.key}`;
              return (
                <Label
                  key={perm.key}
                  htmlFor={id}
                  className={cn(
                    "flex items-center gap-2 rounded-md border px-3 py-2 text-sm font-normal",
                    locked ? "cursor-default opacity-80" : "cursor-pointer hover:bg-accent/40",
                  )}
                >
                  <Checkbox
                    id={id}
                    checked={checked(perm.key)}
                    disabled={locked}
                    onCheckedChange={(c) => toggle(perm.key, !!c)}
                  />
                  <span>{perm.label}</span>
                  <code className="ml-auto text-[10px] text-muted-foreground">{perm.key}</code>
                </Label>
              );
            })}
          </div>
        </div>
      ))}
      {isSuper ? (
        <p className="text-xs text-muted-foreground">
          Role holds <code>*</code> (superadmin) — every permission is granted.
        </p>
      ) : null}
    </div>
  );
}

// frontend/slices/rbac-roles-svelte/components/PermissionMatrix.svelte
<script lang="ts">
  import { matchPermission } from "../../rbac-roles/lib/permissions";
  import {
    PERMISSION_GROUPS,
    type PermissionGroup,
  } from "../../rbac-roles/lib/permission-catalog";

  type Props = {
    value: readonly string[];
    onChange?: (next: string[]) => void;
    groups?: PermissionGroup[];
    readOnly?: boolean;
    class?: string;
  };

  let {
    value,
    onChange,
    groups = PERMISSION_GROUPS,
    readOnly = false,
    class: className = "",
  }: Props = $props();

  let isSuper = $derived(value.includes("*"));
  let locked = $derived(readOnly || isSuper || !onChange);

  function checked(key: string): boolean {
    return isSuper || value.some((permission) => matchPermission(permission, key));
  }

  function toggle(key: string, enabled: boolean): void {
    if (locked || !onChange) return;
    onChange(
      enabled
        ? [...new Set([...value, key])]
        : value.filter((permission) => permission !== key),
    );
  }
</script>

<div class={`space-y-4 ${className}`}>
  {#each groups as group (group.group)}
    <section class="space-y-2">
      <p class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        {group.group}
      </p>
      <div class="grid gap-2 sm:grid-cols-2">
        {#each group.permissions as permission (permission.key)}
          {@const id = `perm-${permission.key}`}
          <label
            for={id}
            class={`flex items-center gap-2 rounded-md border px-3 py-2 text-sm font-normal ${locked ? "cursor-default opacity-80" : "cursor-pointer hover:bg-accent/40"}`}
          >
            <input
              id={id}
              type="checkbox"
              checked={checked(permission.key)}
              disabled={locked}
              onchange={(event) => toggle(permission.key, event.currentTarget.checked)}
            />
            <span>{permission.label}</span>
            <code class="ml-auto text-[10px] text-muted-foreground">{permission.key}</code>
          </label>
        {/each}
      </div>
    </section>
  {/each}

  {#if isSuper}
    <p class="text-xs text-muted-foreground">
      Role holds <code>*</code> (superadmin) — every permission is granted.
    </p>
  {/if}
</div>
