// frontend/slices/admin-console/components/AccessGate.tsx
"use client"

import * as React from "react"
import type { AdminAccess, AdminAccessLevel } from "../lib/sections"
import { hasPermission, meetsLevel } from "../lib/access"

interface AccessGateProps {
  access: AdminAccess
  /** Minimum level required. Defaults to any admin level. */
  minLevel?: AdminAccessLevel
  /** Required permission (overrides minLevel when provided). */
  permission?: string
  fallback?: React.ReactNode
  children: React.ReactNode
}

/**
 * Renders children only when the injected `access` meets the requirement.
 * Portable: access is passed in (consumer's own useAdminAccess or a mock), so
 * this never imports Convex and stays unit-testable.
 */
export function AccessGate({
  access,
  minLevel = "delegated_admin",
  permission,
  fallback = null,
  children,
}: AccessGateProps) {
  if (access.isLoading) return null
  const ok = permission
    ? hasPermission(access.permissions, permission) || access.level === "platform_admin"
    : meetsLevel(access.level, minLevel)
  return <>{ok ? children : fallback}</>
}

// frontend/slices/admin-svelte/variants/console/components/AccessGate.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type {
    AdminAccess,
    AdminAccessLevel,
  } from "@/features/admin/variants/console/lib/sections";
  import {
    hasPermission,
    meetsLevel,
  } from "@/features/admin/variants/console/lib/access";

  type Props = {
    access: AdminAccess;
    minLevel?: AdminAccessLevel;
    permission?: string;
    children: Snippet;
    fallback?: Snippet;
  };

  let {
    access,
    minLevel = "delegated_admin",
    permission,
    children,
    fallback,
  }: Props = $props();

  let allowed = $derived(
    permission
      ? access.level === "platform_admin" || hasPermission(access.permissions, permission)
      : meetsLevel(access.level, minLevel),
  );
</script>

{#if !access.isLoading}
  {#if allowed}
    {@render children()}
  {:else if fallback}
    {@render fallback()}
  {/if}
{/if}
