// frontend/slices/media-viewer-svelte/components/ViewerToolbar.svelte
<script lang="ts">
  import { editorFor } from "../../media-viewer/lib/media";
  import { openWindow } from "../../media-viewer/lib/host-core";
  import type { Sample } from "../../media-viewer/lib/samples";

  let {
    file,
    index,
    count,
    zoom,
    onPrev,
    onNext,
    onZoomIn,
    onZoomOut,
    onDownload,
  } = $props<{
    file: Sample;
    index: number;
    count: number;
    zoom: number;
    onPrev: () => void;
    onNext: () => void;
    onZoomIn: () => void;
    onZoomOut: () => void;
    onDownload: () => void;
  }>();

  let editor = $derived(editorFor(file.kind));

  function openEditor() {
    if (!editor) return;
    openWindow(editor.app, file.name, undefined, {
      path: file.name,
      name: file.name,
      kind: file.kind,
    });
  }
</script>

<header class="flex flex-wrap items-center gap-x-2 gap-y-1 border-b bg-background/60 px-3 py-2 backdrop-blur">
  <span class="min-w-0 flex-1 truncate text-sm font-semibold @max-[480px]:basis-full">{file.name}</span>
  <span class="rounded-md bg-secondary px-2 py-0.5 font-mono text-[10px] uppercase text-secondary-foreground">{file.kind}</span>

  {#if file.kind === "image"}
    <span class="mx-1 h-5 w-px bg-border @max-[480px]:hidden" aria-hidden="true"></span>
    <button type="button" title="Zoom out" aria-label="Zoom out" disabled={zoom <= 0.4} onclick={onZoomOut} class="grid size-8 place-items-center rounded-md hover:bg-accent disabled:opacity-40">−</button>
    <span class="w-10 text-center font-mono text-[11px] tabular-nums text-muted-foreground">{Math.round(zoom * 100)}%</span>
    <button type="button" title="Zoom in" aria-label="Zoom in" disabled={zoom >= 3} onclick={onZoomIn} class="grid size-8 place-items-center rounded-md hover:bg-accent disabled:opacity-40">+</button>
  {/if}

  <span class="mx-1 h-5 w-px bg-border @max-[480px]:hidden" aria-hidden="true"></span>
  <button type="button" title="Download" aria-label="Download" onclick={onDownload} class="grid size-8 place-items-center rounded-md hover:bg-accent">↓</button>
  {#if editor}
    <button type="button" title={`Open in ${editor.label}`} aria-label={`Open in ${editor.label}`} onclick={openEditor} class="rounded-md px-2 py-1 text-xs hover:bg-accent">Edit</button>
  {/if}

  <span class="mx-1 h-5 w-px bg-border @max-[480px]:hidden" aria-hidden="true"></span>
  <button type="button" title="Previous" aria-label="Previous" onclick={onPrev} class="grid size-8 place-items-center rounded-md hover:bg-accent">←</button>
  <span class="font-mono text-[11px] tabular-nums text-muted-foreground">{index + 1}/{count}</span>
  <button type="button" title="Next" aria-label="Next" onclick={onNext} class="grid size-8 place-items-center rounded-md hover:bg-accent">→</button>
</header>

// frontend/slices/media-viewer/components/viewer-toolbar.tsx
"use client";

import {
  ZoomIn,
  ZoomOut,
  ChevronLeft,
  ChevronRight,
  Download,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { openWindow } from "../lib/host";
import { cn } from "@/lib/utils";
import type { Sample } from "../lib/samples";
import { editorFor } from "../lib/media";

type Props = {
  file: Sample;
  index: number;
  count: number;
  zoom: number;
  onPrev: () => void;
  onNext: () => void;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onDownload: () => void;
};

export function ViewerToolbar({
  file,
  index,
  count,
  zoom,
  onPrev,
  onNext,
  onZoomIn,
  onZoomOut,
  onDownload,
}: Props) {
  const isImage = file.kind === "image";
  const editor = editorFor(file.kind);

  return (
    <header className="flex items-center gap-2 border-b bg-background/60 px-3 py-2 backdrop-blur">
      <span className="min-w-0 flex-1 truncate text-sm font-semibold">
        {file.name}
      </span>
      <Badge variant="secondary" className="font-mono text-[10px] uppercase">
        {file.kind}
      </Badge>

      {isImage && (
        <>
          <Separator orientation="vertical" className="mx-1 h-5" />
          <IconBtn label="Zoom out" onClick={onZoomOut} disabled={zoom <= 0.4}>
            <ZoomOut className="size-4" />
          </IconBtn>
          <span className="w-10 text-center font-mono text-[11px] tabular-nums text-muted-foreground">
            {Math.round(zoom * 100)}%
          </span>
          <IconBtn label="Zoom in" onClick={onZoomIn} disabled={zoom >= 3}>
            <ZoomIn className="size-4" />
          </IconBtn>
        </>
      )}

      <Separator orientation="vertical" className="mx-1 h-5" />
      <IconBtn label="Download" onClick={onDownload}>
        <Download className="size-4" />
      </IconBtn>
      {editor && (
        <IconBtn
          label={`Open in ${editor.label}`}
          onClick={() =>
            openWindow(editor.app, file.name, undefined, {
              path: file.name,
              name: file.name,
              kind: file.kind,
            })
          }
        >
          <ExternalLink className="size-4" />
        </IconBtn>
      )}

      <Separator orientation="vertical" className="mx-1 h-5" />
      <IconBtn label="Previous" onClick={onPrev}>
        <ChevronLeft className="size-4" />
      </IconBtn>
      <span className="font-mono text-[11px] tabular-nums text-muted-foreground">
        {index + 1}/{count}
      </span>
      <IconBtn label="Next" onClick={onNext}>
        <ChevronRight className="size-4" />
      </IconBtn>
    </header>
  );
}

function IconBtn({
  label,
  children,
  className,
  ...rest
}: React.ComponentProps<typeof Button> & { label: string }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button
          size="icon"
          variant="ghost"
          className={cn("size-7", className)}
          {...rest}
        >
          {children}
        </Button>
      </TooltipTrigger>
      <TooltipContent>{label}</TooltipContent>
    </Tooltip>
  );
}
