// frontend/slices/marketing-chrome/components/MarketingFooter.tsx
"use client";

import * as React from "react";
import {
  AtSign,
  Bird,
  Camera,
  GitFork,
  PlayCircle,
  type LucideIcon,
} from "lucide-react";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import type {
  Brand,
  MarketingFooterProps,
  SocialKind,
  SocialLink,
} from "../lib/types";

// NOTE: lucide dropped dedicated brand glyphs; these are the closest neutral
// stand-ins. Swap for your brand-icon set (e.g. simple-icons) post-copy.
const SOCIAL_ICON: Record<SocialKind, LucideIcon> = {
  github: GitFork,
  x: Bird,
  linkedin: AtSign,
  youtube: PlayCircle,
  instagram: Camera,
};

function BrandMark({ brand }: { brand: Brand }) {
  const inner = (
    <span className="flex items-center gap-2 font-semibold tracking-tight">
      {brand.logo}
      <span>{brand.name}</span>
    </span>
  );
  return brand.href ? (
    <a href={brand.href} className="transition-opacity hover:opacity-80">
      {inner}
    </a>
  ) : (
    inner
  );
}

function Social({ social }: { social: SocialLink[] }) {
  if (social.length === 0) return null;
  return (
    <div className="flex items-center gap-3">
      {social.map((s) => {
        const Icon = SOCIAL_ICON[s.kind];
        return (
          <a
            key={s.kind + s.href}
            href={s.href}
            aria-label={s.kind}
            target="_blank"
            rel="noreferrer noopener"
            className="text-muted-foreground transition-colors hover:text-foreground"
          >
            <Icon className="size-4" />
          </a>
        );
      })}
    </div>
  );
}

function LegalRow({
  copyright,
  legal,
}: {
  copyright?: string;
  legal: { label: string; href: string }[];
}) {
  return (
    <div className="flex flex-col items-center justify-between gap-2 text-xs text-muted-foreground sm:flex-row">
      <span>{copyright}</span>
      {legal.length > 0 ? (
        <div className="flex items-center gap-4">
          {legal.map((l) => (
            <a
              key={l.href + l.label}
              href={l.href}
              className="transition-colors hover:text-foreground"
            >
              {l.label}
            </a>
          ))}
        </div>
      ) : null}
    </div>
  );
}

/**
 * Config-driven marketing footer.
 * - `columns` (default) — brand blurb + multi-column link grid + legal bar
 * - `slim` — single row: brand · legal links · social
 */
export function MarketingFooter({
  brand,
  columns = [],
  social = [],
  legal = [],
  copyright,
  layout = "columns",
  className,
}: MarketingFooterProps) {
  if (layout === "slim") {
    return (
      <footer className={cn("w-full border-t bg-background", className)}>
        <div className="mx-auto flex w-full max-w-6xl flex-col items-center justify-between gap-4 px-6 py-6 sm:flex-row">
          <BrandMark brand={brand} />
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            {legal.map((l) => (
              <a
                key={l.href + l.label}
                href={l.href}
                className="transition-colors hover:text-foreground"
              >
                {l.label}
              </a>
            ))}
            {copyright ? <span>{copyright}</span> : null}
          </div>
          <Social social={social} />
        </div>
      </footer>
    );
  }

  return (
    <footer className={cn("w-full border-t bg-background", className)}>
      <div className="mx-auto w-full max-w-6xl px-6 py-12">
        <div className="grid gap-10 md:grid-cols-[1.5fr_repeat(auto-fit,minmax(0,1fr))]">
          <div className="flex flex-col gap-4">
            <BrandMark brand={brand} />
            <Social social={social} />
          </div>
          {columns.map((col) => (
            <div key={col.heading} className="flex flex-col gap-3">
              <h3 className="text-sm font-semibold">{col.heading}</h3>
              <ul className="flex flex-col gap-2">
                {col.links.map((l) => (
                  <li key={l.href + l.label}>
                    <a
                      href={l.href}
                      className="text-sm text-muted-foreground transition-colors hover:text-foreground"
                    >
                      {l.label}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <Separator className="my-8" />
        <LegalRow copyright={copyright} legal={legal} />
      </div>
    </footer>
  );
}

// frontend/slices/marketing-chrome-svelte/components/MarketingFooter.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import BrandMark from "./BrandMark.svelte";
  import {
    SOCIAL_TEXT,
    type BrandBase,
    type FooterColumn,
    type FooterLayout,
    type LegalLink,
    type SocialLink,
  } from "../../marketing-chrome/lib/core";

  type SvelteBrand = BrandBase & { logo?: Snippet };
  type Props = {
    brand: SvelteBrand;
    columns?: FooterColumn[];
    social?: SocialLink[];
    legal?: LegalLink[];
    copyright?: string;
    layout?: FooterLayout;
    class?: string;
  };

  let {
    brand,
    columns = [],
    social = [],
    legal = [],
    copyright,
    layout = "columns",
    class: className = "",
  }: Props = $props();
</script>

{#snippet socialLinks()}
  {#if social.length > 0}
    <div class="flex items-center gap-3">
      {#each social as item (`${item.kind}:${item.href}`)}
        <a
          href={item.href}
          aria-label={item.kind}
          target="_blank"
          rel="noreferrer noopener"
          class="inline-flex min-w-5 items-center justify-center text-xs font-semibold text-muted-foreground transition-colors hover:text-foreground"
        >{SOCIAL_TEXT[item.kind]}</a>
      {/each}
    </div>
  {/if}
{/snippet}

{#if layout === "slim"}
  <footer class={`w-full border-t bg-background ${className}`}>
    <div class="mx-auto flex w-full max-w-6xl flex-col items-center justify-between gap-4 px-6 py-6 sm:flex-row">
      <BrandMark {brand} />
      <div class="flex items-center gap-4 text-xs text-muted-foreground">
        {#each legal as item (`${item.href}:${item.label}`)}
          <a href={item.href} class="transition-colors hover:text-foreground">{item.label}</a>
        {/each}
        {#if copyright}<span>{copyright}</span>{/if}
      </div>
      {@render socialLinks()}
    </div>
  </footer>
{:else}
  <footer class={`w-full border-t bg-background ${className}`}>
    <div class="mx-auto w-full max-w-6xl px-6 py-12">
      <div class="grid gap-10 md:grid-cols-[1.5fr_repeat(auto-fit,minmax(0,1fr))]">
        <div class="flex flex-col gap-4">
          <BrandMark {brand} />
          {@render socialLinks()}
        </div>
        {#each columns as column (column.heading)}
          <div class="flex flex-col gap-3">
            <h3 class="text-sm font-semibold">{column.heading}</h3>
            <ul class="flex flex-col gap-2">
              {#each column.links as item (`${item.href}:${item.label}`)}
                <li><a href={item.href} class="text-sm text-muted-foreground transition-colors hover:text-foreground">{item.label}</a></li>
              {/each}
            </ul>
          </div>
        {/each}
      </div>
      <div class="my-8 h-px bg-border" aria-hidden="true"></div>
      <div class="flex flex-col items-center justify-between gap-2 text-xs text-muted-foreground sm:flex-row">
        <span>{copyright}</span>
        {#if legal.length > 0}
          <div class="flex items-center gap-4">
            {#each legal as item (`legal:${item.href}:${item.label}`)}
              <a href={item.href} class="transition-colors hover:text-foreground">{item.label}</a>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  </footer>
{/if}
