// frontend/slices/command-menu-svelte/components/SearchModal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import {
    resolveSearchLabels,
    searchView,
    type SearchBindingsBase,
    type SearchHitBase,
    type SearchModalLabels,
  } from "../../command-menu/lib/core";

  let {
    open = $bindable(false),
    onOpenChange,
    labels,
    bindings,
    renderIcon,
  } = $props<{
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    labels?: SearchModalLabels;
    bindings: SearchBindingsBase;
    renderIcon?: Snippet<[SearchHitBase, "page" | "database"]>;
  }>();

  let inputElement = $state<HTMLInputElement>();
  let query = $state("");
  let text = $derived(resolveSearchLabels(labels));
  let view = $derived(searchView(query, bindings));

  function setOpen(value: boolean) {
    open = value;
    onOpenChange?.(value);
  }

  function setQuery(value: string) {
    query = value;
    bindings.onQueryChange(value);
  }

  function select(hit: SearchHitBase, kind: "page" | "database") {
    if (kind === "page") bindings.onSelectPage(hit);
    else bindings.onSelectDatabase(hit);
    setOpen(false);
  }

  $effect(() => {
    if (!open) {
      if (query) query = "";
      return;
    }
    queueMicrotask(() => inputElement?.focus());
  });
</script>

{#if open}
  <div class="fixed inset-0 z-50 flex items-start justify-center bg-background/70 p-4 pt-[14vh] backdrop-blur-sm" role="presentation" onclick={(event) => event.currentTarget === event.target && setOpen(false)}>
    <div class="w-full max-w-xl overflow-hidden rounded-xl border bg-popover shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="command-search-title" aria-describedby="command-search-description">
      <h2 id="command-search-title" class="sr-only">{text.searchTitle}</h2>
      <p id="command-search-description" class="sr-only">{text.searchDescription}</p>
      <div class="flex items-center gap-2 border-b px-4 py-3">
        <span aria-hidden="true">⌕</span>
        <input
          bind:this={inputElement}
          value={query}
          oninput={(event) => setQuery(event.currentTarget.value)}
          onkeydown={(event) => event.key === "Escape" && setOpen(false)}
          placeholder={text.searchPlaceholder}
          class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        />
        {#if bindings.isLoading}<span class="animate-pulse text-xs text-muted-foreground">…</span>{/if}
        <kbd class="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">{text.escapeHint}</kbd>
      </div>

      <div class="max-h-[420px] overflow-y-auto p-2">
        {#if view.showNoResults}
          <div class="px-3 py-8 text-center text-sm text-muted-foreground">{text.noResults(query)}</div>
        {/if}

        {#if view.recent.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.recentHeading}</div>
          {#each view.recent as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "page")}>
              {#if renderIcon}{@render renderIcon(hit, "page")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if bindings.pages.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.pagesHeading}</div>
          {#each bindings.pages as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "page")}>
              {#if renderIcon}{@render renderIcon(hit, "page")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if bindings.databases.length > 0}
          <div class="px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{text.databasesHeading}</div>
          {#each bindings.databases as hit (hit.id)}
            <button type="button" class="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left hover:bg-accent" onclick={() => select(hit, "database")}>
              {#if renderIcon}{@render renderIcon(hit, "database")}{/if}
              <span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">{hit.title || "Untitled"}</span>{#if hit.subtitle}<span class="block truncate text-xs text-muted-foreground">{hit.subtitle}</span>{/if}</span>
            </button>
          {/each}
        {/if}

        {#if view.showEmptyHint}
          <div class="px-3 py-8 text-center text-sm text-muted-foreground">{text.emptyHint}</div>
        {/if}
      </div>
    </div>
  </div>
{/if}

// frontend/slices/command-menu/components/SearchModal.tsx
"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Search, FileText, Clock, Database as DatabaseIcon, Loader2 } from "lucide-react";
import { resolveSearchLabels, searchView } from "../lib/core";
import type { SearchHit, SearchModalBindings, SearchModalLabels } from "../lib/types";

export type { SearchHit, SearchModalBindings } from "../lib/types";

interface Props {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  /** Override copy strings. Defaults are generic English. */
  labels?: SearchModalLabels;
  /** Consumer-supplied data + handlers. */
  bindings: SearchModalBindings;
}

/** Renderless search modal. Owns dialog chrome, query input, section
 *  layout, and empty/loading states. ALL data + navigation flow comes
 *  from the `bindings` prop so the slice is portable. */
export function SearchModal({ open, onOpenChange, labels, bindings }: Props) {
  const t = resolveSearchLabels(labels);
  const [q, setQ] = useState("");
  const view = searchView(q, bindings);
  const recent = view.recent;

  useEffect(() => { if (!open) setQ(""); }, [open]);

  const handleQ = (v: string) => {
    setQ(v);
    bindings.onQueryChange(v);
  };

  const goPage = (hit: SearchHit) => { bindings.onSelectPage(hit); onOpenChange(false); };
  const goDb = (hit: SearchHit) => { bindings.onSelectDatabase(hit); onOpenChange(false); };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="p-0 overflow-hidden max-w-xl gap-0 top-[20%] translate-y-0">
        <DialogTitle className="sr-only">{t.searchTitle}</DialogTitle>
        <DialogDescription className="sr-only">
          {t.searchDescription}
        </DialogDescription>
        <div className="flex items-center gap-3 px-4 py-3 border-b border-border">
          <Search className="h-4 w-4 text-muted-foreground" />
          <input
            autoFocus
            value={q}
            onChange={e => handleQ(e.target.value)}
            placeholder={t.searchPlaceholder}
            className="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
          />
          {bindings.isLoading && <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />}
          <kbd className="text-[10px] text-muted-foreground border border-border rounded px-1.5 py-0.5">{t.escapeHint}</kbd>
        </div>
        <div className="max-h-[420px] overflow-y-auto p-2">
          {view.showNoResults && (
            <div className="px-3 py-8 text-center text-sm text-muted-foreground">{t.noResults(q)}</div>
          )}
          {!q && recent.length > 0 && (
            <>
              <SectionHeader icon={<Clock className="h-3 w-3" />}>{t.recentHeading}</SectionHeader>
              {recent.map(p => (
                <Row key={p.id} hit={p} onClick={() => goPage(p)} kind="page" />
              ))}
            </>
          )}
          {bindings.pages.length > 0 && (
            <>
              <SectionHeader icon={<FileText className="h-3 w-3" />}>{t.pagesHeading}</SectionHeader>
              {bindings.pages.map(p => (
                <Row key={p.id} hit={p} onClick={() => goPage(p)} kind="page" />
              ))}
            </>
          )}
          {bindings.databases.length > 0 && (
            <>
              <SectionHeader icon={<DatabaseIcon className="h-3 w-3" />}>{t.databasesHeading}</SectionHeader>
              {bindings.databases.map(d => (
                <Row key={d.id} hit={d} onClick={() => goDb(d)} kind="db" />
              ))}
            </>
          )}
          {view.showEmptyHint && (
            <div className="px-3 py-8 text-center text-sm text-muted-foreground">{t.emptyHint}</div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

function SectionHeader({ icon, children }: { icon: ReactNode; children: ReactNode }) {
  return (
    <div className="px-3 py-1.5 text-[11px] uppercase tracking-wider text-muted-foreground font-semibold flex items-center gap-1.5">
      {icon} {children}
    </div>
  );
}

function Row({
  hit,
  onClick,
  kind,
}: {
  hit: SearchHit;
  onClick: () => void;
  kind: "page" | "db";
}) {
  const TrailIcon = kind === "db" ? DatabaseIcon : FileText;
  const title = hit.title || "Untitled";
  return (
    <Button
      variant="ghost"
      onClick={onClick}
      className="flex h-auto w-full items-center justify-start gap-3 rounded-md px-3 py-2 text-left font-normal hover:bg-accent"
    >
      {hit.icon ?? <TrailIcon className="h-4 w-4 text-muted-foreground" />}
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-medium">{title}</div>
        {hit.subtitle && <div className="truncate text-xs text-muted-foreground">{hit.subtitle}</div>}
      </div>
      <TrailIcon className="h-3.5 w-3.5 text-muted-foreground" />
    </Button>
  );
}
