// frontend/slices/media-viewer/components/audio-player.tsx
"use client";

import { Music } from "lucide-react";
import { cn } from "@/lib/utils";
import type { Sample } from "../lib/samples";
import { usePlayback } from "../lib/use-playback";
import { TransportBar } from "./transport";

const BARS = 72;

// Deterministic pseudo-waveform heights (0.15..1), stable across renders.
const HEIGHTS = Array.from({ length: BARS }, (_, i) => {
  const v = Math.abs(Math.sin(i * 0.5) * Math.cos(i * 0.23));
  return 0.15 + v * 0.85;
});

export function AudioPlayer({ file }: { file: Sample }) {
  const duration = file.duration ?? 42;
  const { playing, pos, toggle, seek } = usePlayback(duration);

  return (
    <div className="flex w-full max-w-lg flex-col gap-5 rounded-2xl border bg-card/80 p-6 shadow-2xl backdrop-blur">
      <div className="flex items-center gap-4">
        <div className="grid size-14 shrink-0 place-items-center rounded-xl bg-[var(--accent)]/15 text-[var(--accent)]">
          <Music className="size-7" />
        </div>
        <div className="min-w-0">
          <div className="truncate text-base font-semibold">{file.name}</div>
          <div className="text-xs text-muted-foreground">{file.meta ?? "Audio"}</div>
        </div>
      </div>

      <Waveform pos={pos} />

      <TransportBar
        playing={playing}
        pos={pos}
        duration={duration}
        onToggle={toggle}
        onSeek={seek}
      />
    </div>
  );
}

// CSS-bar waveform. Bars before the playhead read as accent, the rest muted.
// Clicking a bar seeks to that fraction.
function Waveform({ pos }: { pos: number }) {
  return (
    <div className="flex h-14 items-center gap-[2px]">
      {HEIGHTS.map((h, i) => {
        const on = i / BARS <= pos;
        return (
          <div
            key={i}
            className={cn(
              "flex-1 rounded-full transition-colors",
              on ? "bg-[var(--accent)]" : "bg-border",
            )}
            style={{ height: `${Math.round(h * 100)}%` }}
          />
        );
      })}
    </div>
  );
}

// frontend/slices/media-viewer-svelte/components/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Sample } from "../../media-viewer/lib/samples";
  import Transport from "./Transport.svelte";

  const BARS = 72;
  const heights = Array.from({ length: BARS }, (_, index) => {
    const value = Math.abs(Math.sin(index * 0.5) * Math.cos(index * 0.23));
    return 0.15 + value * 0.85;
  });

  let { file } = $props<{ file: Sample }>();
  let playing = $state(false);
  let pos = $state(0);
  let duration = $derived(file.duration ?? 42);

  onMount(() => {
    const timer = setInterval(() => {
      if (!playing) return;
      const next = Math.min(1, pos + 0.1 / Math.max(duration, 0.1));
      pos = next;
      if (next >= 1) playing = false;
    }, 100);
    return () => clearInterval(timer);
  });

  function seek(next: number) {
    pos = Math.max(0, Math.min(1, next));
  }
</script>

<div class="flex w-full max-w-lg flex-col gap-5 rounded-2xl border bg-card/80 p-6 shadow-2xl backdrop-blur">
  <div class="flex items-center gap-4">
    <div class="grid size-14 shrink-0 place-items-center rounded-xl bg-[var(--accent)]/15 text-2xl text-[var(--accent)]">♫</div>
    <div class="min-w-0">
      <div class="truncate text-base font-semibold">{file.name}</div>
      <div class="text-xs text-muted-foreground">{file.meta ?? "Audio"}</div>
    </div>
  </div>

  <div class="flex h-14 items-center gap-[2px]" aria-label="Waveform">
    {#each heights as height, index}
      <div
        class={`flex-1 rounded-full transition-colors ${index / BARS <= pos ? "bg-[var(--accent)]" : "bg-border"}`}
        style:height={`${Math.round(height * 100)}%`}
      ></div>
    {/each}
  </div>

  <Transport {playing} {pos} {duration} onToggle={() => (playing = !playing)} onSeek={seek} />
</div>
