// frontend/slices/library-svelte/components/PayloadRender.svelte
<script lang="ts">
  import CopyButton from "./CopyButton.svelte";
  import {
    formatLibraryFileSize,
    libraryVideoSource,
  } from "@/features/library/lib/core";
  import type { LibraryCopy, LibraryItem } from "@/features/library/lib/types";

  let { item, copy }: { item: LibraryItem; copy: LibraryCopy } = $props();
  let media = $derived(libraryVideoSource(item.videoUrl));
</script>

{#if item.kind === "prompt"}
  <div class="space-y-3">
    {#if item.promptModel}
      <span class="inline-block rounded-sm border-2 border-current px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
        Model: {item.promptModel}
      </span>
    {/if}
    <pre class="whitespace-pre-wrap break-words rounded-md border-2 border-current p-4 text-sm leading-relaxed" translate="no">{item.promptText}</pre>
    {#if item.promptText}
      <CopyButton text={item.promptText} label={copy.copyPromptLabel} copiedLabel={copy.copiedLabel} />
    {/if}
  </div>
{:else if item.kind === "image" && item.imageUrl}
  <figure class="space-y-2">
    <div class="overflow-hidden rounded-md border-2 border-current">
      <img src={item.imageUrl} alt={item.imageAlt ?? item.title} loading="lazy" class="h-auto w-full" />
    </div>
    {#if item.imageAlt}<figcaption class="text-xs opacity-60">{item.imageAlt}</figcaption>{/if}
  </figure>
{:else if item.kind === "video" && media}
  {#if media.kind === "youtube"}
    <div class="aspect-video overflow-hidden rounded-md border-2 border-current">
      <iframe
        src={media.src}
        title={item.title}
        class="h-full w-full"
        allow="accelerometer; encrypted-media; picture-in-picture"
        allowfullscreen
      ></iframe>
    </div>
  {:else if media.kind === "vimeo"}
    <div class="aspect-video overflow-hidden rounded-md border-2 border-current">
      <iframe src={media.src} title={item.title} class="h-full w-full" allow="autoplay; fullscreen" allowfullscreen></iframe>
    </div>
  {:else}
    <video src={media.src} controls class="w-full rounded-md border-2 border-current">
      <track kind="captions" src={item.videoCaptionsUrl} />
    </video>
  {/if}
{:else if item.kind === "link" && item.linkUrl}
  <a
    href={item.linkUrl}
    target="_blank"
    rel="noopener noreferrer nofollow ugc"
    class="inline-flex items-center gap-2 rounded-md border-2 border-current bg-foreground px-4 py-2 text-sm font-medium uppercase tracking-wider text-background transition-colors hover:bg-background hover:text-foreground"
  >
    {copy.openLinkLabel}
  </a>
{:else if item.kind === "download" && item.fileStorageId}
  <a
    href={item.fileStorageId}
    download={item.fileName ?? item.slug}
    class="inline-flex items-center gap-2 rounded-md border-2 border-current bg-foreground px-4 py-2 text-sm font-medium uppercase tracking-wider text-background transition-colors hover:bg-background hover:text-foreground"
  >
    {copy.downloadLabel} {item.fileName ?? "file"}{item.fileSize ? ` · ${formatLibraryFileSize(item.fileSize)}` : ""}
  </a>
{:else if item.kind === "snippet"}
  <div class="space-y-3">
    {#if item.snippetLang}
      <span class="inline-block rounded-sm border-2 border-current px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
        {item.snippetLang}
      </span>
    {/if}
    <pre class="overflow-x-auto rounded-md border-2 border-current p-4 text-xs leading-relaxed" translate="no"><code translate="no" class="notranslate">{item.snippetCode}</code></pre>
    {#if item.snippetCode}
      <CopyButton text={item.snippetCode} label={copy.copyCodeLabel} copiedLabel={copy.copiedLabel} />
    {/if}
  </div>
{/if}

// frontend/slices/library/components/PayloadRender.tsx
import Image from "next/image";
import { CopyButton } from "./CopyButton";
import type { LibraryCopy, LibraryItem } from "../lib/types";
import { formatLibraryFileSize, libraryVideoSource } from "../lib/core";

// Switches on `item.kind` to render the kind-specific payload. Video
// embeds YouTube (nocookie) / Vimeo when the URL matches, else falls
// back to a native <video>. `prompt`/`snippet` get a CopyButton.
export function PayloadRender({
  item,
  copy,
}: {
  item: LibraryItem;
  copy: LibraryCopy;
}) {
  switch (item.kind) {
    case "prompt":
      return (
        <div className="space-y-3">
          {item.promptModel ? (
            <span className="inline-block border-2 border-current rounded-sm px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
              Model: {item.promptModel}
            </span>
          ) : null}
          <pre
            className="border-2 border-current rounded-md p-4 text-sm whitespace-pre-wrap break-words leading-relaxed"
            translate="no"
          >
            {item.promptText}
          </pre>
          {item.promptText ? (
            <CopyButton text={item.promptText} label={copy.copyPromptLabel} copiedLabel={copy.copiedLabel} />
          ) : null}
        </div>
      );
    case "image":
      return item.imageUrl ? (
        <figure className="space-y-2">
          <div className="relative w-full border-2 border-current rounded-md overflow-hidden">
            <Image
              src={item.imageUrl}
              alt={item.imageAlt ?? item.title}
              width={1200}
              height={800}
              className="w-full h-auto"
              unoptimized
            />
          </div>
          {item.imageAlt ? (
            <figcaption className="text-xs opacity-60">{item.imageAlt}</figcaption>
          ) : null}
        </figure>
      ) : null;
    case "video": {
      const media = libraryVideoSource(item.videoUrl);
      if (!media) return null;
      const frame = "aspect-video border-2 border-current rounded-md overflow-hidden";
      if (media.kind === "youtube")
        return (
          <div className={frame}>
            <iframe
              src={media.src}
              title={item.title}
              className="w-full h-full"
              allow="accelerometer; encrypted-media; picture-in-picture"
              allowFullScreen
            />
          </div>
        );
      if (media.kind === "vimeo")
        return (
          <div className={frame}>
            <iframe
              src={media.src}
              title={item.title}
              className="w-full h-full"
              allow="autoplay; fullscreen"
              allowFullScreen
            />
          </div>
        );
      return (
        <video src={media.src} controls className="w-full border-2 border-current rounded-md">
          <track kind="captions" src={item.videoCaptionsUrl} />
        </video>
      );
    }
    case "link":
      return item.linkUrl ? (
        <a
          href={item.linkUrl}
          target="_blank"
          rel="noopener noreferrer nofollow ugc"
          className="inline-flex items-center gap-2 border-2 border-current rounded-md bg-foreground text-background hover:bg-background hover:text-foreground transition-colors px-4 py-2 text-sm uppercase tracking-wider font-medium"
        >
          {copy.openLinkLabel}
        </a>
      ) : null;
    case "download":
      return item.fileStorageId ? (
        <a
          href={item.fileStorageId}
          download={item.fileName ?? item.slug}
          className="inline-flex items-center gap-2 border-2 border-current rounded-md bg-foreground text-background hover:bg-background hover:text-foreground transition-colors px-4 py-2 text-sm uppercase tracking-wider font-medium"
        >
          {copy.downloadLabel} {item.fileName ?? "file"}
          {item.fileSize ? ` · ${formatLibraryFileSize(item.fileSize)}` : ""}
        </a>
      ) : null;
    case "snippet":
      return (
        <div className="space-y-3">
          {item.snippetLang ? (
            <span className="inline-block border-2 border-current rounded-sm px-2 py-0.5 text-[10px] uppercase tracking-wider opacity-70">
              {item.snippetLang}
            </span>
          ) : null}
          <pre
            className="border-2 border-current rounded-md p-4 text-xs leading-relaxed overflow-x-auto"
            translate="no"
          >
            <code translate="no" className="notranslate">
              {item.snippetCode}
            </code>
          </pre>
          {item.snippetCode ? (
            <CopyButton text={item.snippetCode} label={copy.copyCodeLabel} copiedLabel={copy.copiedLabel} />
          ) : null}
        </div>
      );
  }
}
