// frontend/slices/sections/sections/NewsletterSection.tsx
"use client";

import * as React from "react";
import { Check, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { Reveal } from "../components/motion";
import { cfgString, parseConfigObject } from "./config";
import type { LandingSection } from "../types";

/**
 * Newsletter capture band. By default submit is LOCAL-ONLY (shows the success
 * state, stores nothing) so the slice stays framework-pure. Hosts that want to
 * persist leads pass `onSubscribe` (e.g. a Convex mutation) — on `{ok:true}`
 * the success state shows; on `{ok:false}` the returned `notice` is surfaced.
 * Config keys: { placeholder, buttonLabel, successText }.
 * Renders inside LandingSectionShell (caller wraps).
 */
export function NewsletterSection({
  section,
  placeholder = "Alamat email kamu",
  buttonLabel = "Daftar",
  successText = "Terima kasih — kamu terdaftar!",
  onSubscribe,
  className,
}: {
  section: LandingSection;
  placeholder?: string;
  buttonLabel?: string;
  successText?: string;
  onSubscribe?: (email: string) => Promise<{ ok: boolean; notice?: string }>;
  className?: string;
}) {
  const cfg = parseConfigObject(section.config);
  const ph = cfgString(cfg, "placeholder") ?? placeholder;
  const btn = cfgString(cfg, "buttonLabel") ?? buttonLabel;
  const ok = cfgString(cfg, "successText") ?? successText;
  const [email, setEmail] = React.useState("");
  const [done, setDone] = React.useState(false);
  const [busy, setBusy] = React.useState(false);
  const [notice, setNotice] = React.useState<string | null>(null);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!email.includes("@")) return;
    setNotice(null);
    if (!onSubscribe) {
      setDone(true);
      return;
    }
    setBusy(true);
    try {
      const res = await onSubscribe(email);
      if (res.ok) setDone(true);
      else setNotice(res.notice ?? "Gagal mendaftar — coba lagi.");
    } catch {
      setNotice("Gagal mendaftar — coba lagi.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className={cn("mx-auto max-w-3xl px-4 py-16 sm:px-6", className)}>
      <Reveal variant="zoom">
        <div className="rounded-2xl border border-border/60 bg-gradient-to-b from-muted/40 to-card/60 p-8 text-center sm:p-10">
          <span className="mx-auto grid size-10 place-items-center rounded-full bg-foreground/5">
            <Mail className="size-5 text-foreground/70" />
          </span>
          <h2 className="mt-4 text-2xl font-semibold tracking-tight sm:text-3xl">
            {section.title}
          </h2>
          {section.subtitle && (
            <p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">
              {section.subtitle}
            </p>
          )}
          {done ? (
            <p className="mt-6 inline-flex items-center gap-2 text-sm font-medium">
              <Check className="size-4 text-emerald-600" /> {ok}
            </p>
          ) : (
            <form
              className="mx-auto mt-6 flex max-w-md flex-col gap-2 sm:flex-row"
              onSubmit={submit}
            >
              <Input
                type="email"
                aria-label="Email address"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder={ph}
                className="h-10 flex-1 bg-background"
              />
              <Button type="submit" className="h-10" disabled={busy}>
                {btn}
              </Button>
            </form>
          )}
          {notice && (
            <p className="mt-3 text-sm text-muted-foreground">{notice}</p>
          )}
        </div>
      </Reveal>
    </div>
  );
}

// frontend/slices/sections-svelte/sections/NewsletterSection.svelte
<script lang="ts">
  import { cfgString, parseConfigObject } from "../../sections/sections/config";
  import type { LandingSection } from "../../sections/types";
  type Result = { ok: boolean; notice?: string };
  type Props = { section: LandingSection; placeholder?: string; buttonLabel?: string; successText?: string; onSubscribe?: (email: string) => Promise<Result>; class?: string };
  let { section, placeholder = "Alamat email kamu", buttonLabel = "Daftar", successText = "Terima kasih — kamu terdaftar!", onSubscribe, class: className = "" }: Props = $props();
  let cfg = $derived(parseConfigObject(section.config));
  let ph = $derived(cfgString(cfg, "placeholder") ?? placeholder);
  let btn = $derived(cfgString(cfg, "buttonLabel") ?? buttonLabel);
  let success = $derived(cfgString(cfg, "successText") ?? successText);
  let email = $state(""); let done = $state(false); let busy = $state(false); let notice = $state("");
  async function submit(event: SubmitEvent) { event.preventDefault(); if (!email.includes("@")) return; notice = ""; if (!onSubscribe) { done = true; return; } busy = true; try { const result = await onSubscribe(email); if (result.ok) done = true; else notice = result.notice ?? "Gagal mendaftar — coba lagi."; } catch { notice = "Gagal mendaftar — coba lagi."; } finally { busy = false; } }
</script>
<div class={`mx-auto max-w-3xl px-4 py-16 sm:px-6 ${className}`.trim()}><div class="rounded-2xl border border-border/60 bg-gradient-to-b from-muted/40 to-card/60 p-8 text-center sm:p-10"><span aria-hidden="true" class="text-2xl">✉</span><h2 class="mt-4 text-2xl font-semibold tracking-tight sm:text-3xl">{section.title}</h2>{#if section.subtitle}<p class="mx-auto mt-2 max-w-md text-sm text-muted-foreground">{section.subtitle}</p>{/if}{#if done}<p class="mt-6 text-sm font-medium">✓ {success}</p>{:else}<form class="mx-auto mt-6 flex max-w-md flex-col gap-2 sm:flex-row" onsubmit={submit}><input type="email" required aria-label="Email address" bind:value={email} placeholder={ph} class="h-10 flex-1 rounded-md border bg-background px-3 text-sm" /><button type="submit" disabled={busy} class="h-10 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50">{btn}</button></form>{/if}{#if notice}<p class="mt-3 text-sm text-muted-foreground">{notice}</p>{/if}</div></div>
