// frontend/slices/image-editor-svelte/components/TopBar.svelte
<script lang="ts">
  import type { BrowserEditorCore, EditorSnapshot } from "@/features/image-editor/lib/editor-core";
  import { createLayer, blankDoc, ASPECT_PRESETS } from "@/features/image-editor/lib/model";
  import { loadImage } from "@/features/image-editor/lib/konva-helpers";
  import { removeImageBackground } from "@/features/image-editor/lib/bg-removal";
  import { downloadDataURL, stageToDataURL, type ExportFormat } from "@/features/image-editor/lib/export";
  import { downloadProject, parseProject } from "@/features/image-editor/lib/project-core";

  let { editor, snapshot, onAi } = $props<{ editor: BrowserEditorCore; snapshot: EditorSnapshot; onAi: () => void }>();
  let imageInput = $state<HTMLInputElement>();
  let projectInput = $state<HTMLInputElement>();
  let busy = $state(false);
  let exportFormat = $state<ExportFormat>("png");
  function attachImageInput(node: HTMLInputElement) {
    imageInput=node; return()=>{if(imageInput===node)imageInput=undefined;};
  }
  function attachProjectInput(node: HTMLInputElement) {
    projectInput=node; return()=>{if(projectInput===node)projectInput=undefined;};
  }

  async function importImage(file: File) {
    const url=URL.createObjectURL(file);
    try {
      const img=await loadImage(url); const max=Math.min(snapshot.doc.width,snapshot.doc.height)*.9; const k=Math.min(1,max/Math.max(img.width,img.height)); const w=Math.round(img.width*k),h=Math.round(img.height*k);
      editor.addLayer(createLayer("image",{name:file.name,src:url,t:{x:Math.round((snapshot.doc.width-w)/2),y:Math.round((snapshot.doc.height-h)/2),width:w,height:h,rotation:0,scaleX:1,scaleY:1}})); editor.setTool("move");
    } catch { URL.revokeObjectURL(url); }
  }
  async function openProject(file: File) { const project=parseProject(await file.text()); if(project) editor.loadProject(project); }
  async function removeBg() { const selected=editor.selected; if(!selected||selected.kind!=="image"||!selected.src)return; busy=true; try{const src=await removeImageBackground(selected.src);editor.update(selected.id,{src,name:`${selected.name} (cutout)`});}finally{busy=false;} }
  function exportImage() { const stage=editor.stageRef.current; if(!stage)return; const url=stageToDataURL(stage,{format:exportFormat,pixelRatio:1});downloadDataURL(url,`image-editor.${exportFormat==="jpeg"?"jpg":exportFormat}`); }
  function newDoc() { if(window.confirm("Start a new document?")) editor.reset(blankDoc()); }
</script>
<header class="flex flex-wrap items-center gap-1 border-b bg-background px-2 py-1.5 text-xs">
  <strong class="mr-2">Image Editor</strong>
  <button class="rounded border px-2 py-1" onclick={newDoc}>New</button>
  <button class="rounded border px-2 py-1" onclick={()=>imageInput?.click()}>Open image</button>
  <button class="rounded border px-2 py-1" onclick={()=>projectInput?.click()}>Open project</button>
  <button class="rounded border px-2 py-1" onclick={()=>downloadProject(editor.exportProject(),"image-editor")}>Save project</button>
  <span class="mx-1 h-5 w-px bg-border"></span>
  <button class="rounded border px-2 py-1 disabled:opacity-40" disabled={!snapshot.canUndo} onclick={editor.undo}>Undo</button>
  <button class="rounded border px-2 py-1 disabled:opacity-40" disabled={!snapshot.canRedo} onclick={editor.redo}>Redo</button>
  <span class="mx-1 h-5 w-px bg-border"></span>
  <select class="rounded border bg-background px-2 py-1" aria-label="Canvas preset" onchange={(e)=>{const p=ASPECT_PRESETS[Number(e.currentTarget.value)];if(p)editor.setDocSize(p.w,p.h);}}><option value="">Canvas</option>{#each ASPECT_PRESETS as preset,i (preset.label)}<option value={i}>{preset.label}</option>{/each}</select>
  <button class="rounded border px-2 py-1 disabled:opacity-40" disabled={editor.selected?.kind!=="image"||busy} onclick={()=>void removeBg()}>{busy?"Removing…":"Remove BG"}</button>
  <button class="rounded border px-2 py-1" onclick={onAi}>AI</button>
  <span class="ml-auto"></span>
  <select class="rounded border bg-background px-2 py-1" value={exportFormat} onchange={(e)=>exportFormat=e.currentTarget.value as ExportFormat}><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select>
  <button class="rounded bg-primary px-3 py-1 text-primary-foreground" onclick={exportImage}>Export</button>
  <input class="hidden" type="file" accept="image/*" {@attach attachImageInput} onchange={(e)=>{const f=e.currentTarget.files?.[0];if(f)void importImage(f);e.currentTarget.value="";}} />
  <input class="hidden" type="file" accept=".json,application/json" {@attach attachProjectInput} onchange={(e)=>{const f=e.currentTarget.files?.[0];if(f)void openProject(f);e.currentTarget.value="";}} />
</header>

// frontend/slices/image-editor/components/top-bar.tsx
"use client";

import { useRef, useState } from "react";
import {
  Upload,
  Scissors,
  Undo2,
  Redo2,
  ZoomIn,
  ZoomOut,
  Save,
  FolderOpen,
  FileDown,
  Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { useEditor } from "../lib/store";
import { createLayer } from "../lib/model";
import { loadImage } from "../lib/konva-helpers";
import { removeImageBackground } from "../lib/bg-removal";
import { stageToDataURL } from "../lib/export";
import { downloadProject, parseProject } from "../lib/project";

// Top command bar: open an image, remove its background (free, in-browser),
// undo/redo, zoom, and Save (fires onSave with a PNG data URL).
export function TopBar({ onSave }: { onSave?: (dataUrl: string) => void }) {
  const { doc, selected, addLayer, update, undo, redo, canUndo, canRedo, zoom, setZoom, stageRef, exportProject, loadProject } = useEditor();
  const fileRef = useRef<HTMLInputElement | null>(null);
  const projRef = useRef<HTMLInputElement | null>(null);
  const [busy, setBusy] = useState(false);

  async function openProject(file: File) {
    const p = parseProject(await file.text());
    if (p) loadProject(p);
  }

  async function openFile(file: File) {
    const url = URL.createObjectURL(file);
    const img = await loadImage(url);
    const max = Math.min(doc.width, doc.height) * 0.9;
    const k = Math.min(1, max / Math.max(img.width, img.height));
    const w = Math.round(img.width * k);
    const h = Math.round(img.height * k);
    addLayer(createLayer("image", { name: file.name, src: url, t: { x: Math.round((doc.width - w) / 2), y: Math.round((doc.height - h) / 2), width: w, height: h, rotation: 0, scaleX: 1, scaleY: 1 } }));
  }

  async function removeBg() {
    if (!selected || selected.kind !== "image" || !selected.src) return;
    setBusy(true);
    try {
      const out = await removeImageBackground(selected.src);
      update(selected.id, { src: out, name: `${selected.name} (cutout)` });
    } finally {
      setBusy(false);
    }
  }

  const canCut = selected?.kind === "image" && !!selected.src;
  const z = (d: number) => setZoom(Math.min(5, Math.max(0.1, Math.round((zoom + d) * 100) / 100)));

  return (
    <div className="flex h-12 shrink-0 items-center gap-1 border-b border-border bg-card px-3">
      <span className="mr-2 text-sm font-semibold">Image Editor</span>
      <input
        ref={fileRef}
        type="file"
        accept="image/*"
        className="hidden"
        onChange={(e) => {
          const f = e.target.files?.[0];
          if (f) void openFile(f);
          e.target.value = "";
        }}
      />
      <input
        ref={projRef}
        type="file"
        accept=".json,application/json"
        className="hidden"
        onChange={(e) => { const f = e.target.files?.[0]; if (f) void openProject(f); e.target.value = ""; }}
      />
      <Button variant="ghost" size="sm" onClick={() => fileRef.current?.click()}>
        <Upload className="size-4" /> Open
      </Button>
      <Button variant="ghost" size="sm" disabled={!canCut || busy} onClick={() => void removeBg()}>
        {busy ? <Loader2 className="size-4 animate-spin" /> : <Scissors className="size-4" />} Remove BG
      </Button>
      <Separator orientation="vertical" className="mx-1 h-6" />
      <Button variant="ghost" size="sm" onClick={() => projRef.current?.click()}>
        <FolderOpen className="size-4" /> Open Project
      </Button>
      <Button variant="ghost" size="sm" onClick={() => downloadProject(exportProject())}>
        <FileDown className="size-4" /> Save Project
      </Button>
      <Separator orientation="vertical" className="mx-1 h-6" />
      <Button variant="ghost" size="icon" disabled={!canUndo} onClick={undo} aria-label="Undo">
        <Undo2 className="size-4" />
      </Button>
      <Button variant="ghost" size="icon" disabled={!canRedo} onClick={redo} aria-label="Redo">
        <Redo2 className="size-4" />
      </Button>
      <Separator orientation="vertical" className="mx-1 h-6" />
      <Button variant="ghost" size="icon" onClick={() => z(-0.1)} aria-label="Zoom out">
        <ZoomOut className="size-4" />
      </Button>
      <span className="w-12 text-center text-xs tabular-nums text-muted-foreground">{Math.round(zoom * 100)}%</span>
      <Button variant="ghost" size="icon" onClick={() => z(0.1)} aria-label="Zoom in">
        <ZoomIn className="size-4" />
      </Button>
      <div className="flex-1" />
      {onSave && (
        <Button size="sm" onClick={() => { const s = stageRef.current; if (s) onSave(stageToDataURL(s, { format: "png" })); }}>
          <Save className="size-4" /> Save
        </Button>
      )}
    </div>
  );
}
