// frontend/slices/user-management/components/RolePermissionGrid.tsx
"use client";

// Local permission checkbox grid (the slice doesn't import rbac-roles'
// PermissionMatrix). Groups come in as a prop. A role holding `*` shows
// every box checked + locked.

import { cn } from "@/lib/utils";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { matchPermission } from "../lib/can";
import type { PermissionGroupDef } from "../types";

interface Props {
  value: readonly string[];
  groups: PermissionGroupDef[];
  onChange?: (next: string[]) => void;
  readOnly?: boolean;
  className?: string;
}

export function RolePermissionGrid({ value, groups, onChange, readOnly, className }: Props) {
  const isSuper = value.includes("*");
  const locked = readOnly || isSuper || !onChange;
  const checked = (key: string) => isSuper || value.some((p) => matchPermission(p, key));
  const toggle = (key: string, on: boolean) => {
    if (locked) return;
    onChange?.(on ? [...new Set([...value, key])] : value.filter((p) => p !== key));
  };

  return (
    <div className={cn("space-y-4", className)}>
      {groups.map((g) => (
        <div key={g.group} className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{g.group}</p>
          <div className="grid gap-2 sm:grid-cols-2">
            {g.permissions.map((perm) => {
              const id = `role-perm-${perm.key}`;
              return (
                <Label
                  key={perm.key}
                  htmlFor={id}
                  className={cn(
                    "flex items-center gap-2 rounded-md border px-3 py-2 text-sm font-normal",
                    locked ? "cursor-default opacity-80" : "cursor-pointer hover:bg-accent/40",
                  )}
                >
                  <Checkbox id={id} checked={checked(perm.key)} disabled={locked} onCheckedChange={(c) => toggle(perm.key, !!c)} />
                  <span>{perm.label}</span>
                  <code className="ml-auto text-[10px] text-muted-foreground">{perm.key}</code>
                </Label>
              );
            })}
          </div>
        </div>
      ))}
      {isSuper ? (
        <p className="text-xs text-muted-foreground">Role holds <code>*</code> — every permission granted.</p>
      ) : null}
    </div>
  );
}

// frontend/slices/user-management-svelte/components/RolePermissionGrid.svelte
<script lang="ts">
  import { matchPermission } from "../../user-management/lib/can"; import type { PermissionGroupDef } from "../../user-management/types";
  let { value, groups, onChange, readOnly = false, className = "" }: { value: readonly string[]; groups: PermissionGroupDef[]; onChange?: (next: string[]) => void; readOnly?: boolean; className?: string } = $props();
  let isSuper = $derived(value.includes("*")); let locked = $derived(readOnly || isSuper || !onChange);
  const checked = (key: string) => isSuper || value.some((permission) => matchPermission(permission, key));
  function toggle(key: string, enabled: boolean) { if (locked) return; onChange?.(enabled ? [...new Set([...value, key])] : value.filter((permission) => permission !== key)); }
</script>

<div class={`space-y-4 ${className}`}>
  {#each groups as group (group.group)}<section class="space-y-2"><p class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{group.group}</p><div class="grid gap-2 sm:grid-cols-2">
    {#each group.permissions as permission (permission.key)}<label class="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={checked(permission.key)} disabled={locked} onchange={(e) => toggle(permission.key, e.currentTarget.checked)} /><span>{permission.label}</span><code class="ml-auto text-[10px] text-muted-foreground">{permission.key}</code></label>{/each}
  </div></section>{/each}
  {#if isSuper}<p class="text-xs text-muted-foreground">Role holds <code>*</code> — every permission granted.</p>{/if}
</div>
