// frontend/slices/resources-launcher-admin-svelte/components/ResourceEditor.svelte
<script lang="ts">
  import {
    RESOURCE_ICON_NAMES,
    resourcesApi,
    type Resource,
  } from "@/features/resources-launcher-admin/lib/core";

  let { row, onDone, onCancel }: {
    row: Resource | null;
    onDone: () => void;
    onCancel: () => void;
  } = $props();

  class EditorForm {
    label = $state("");
    icon = $state<string>(RESOURCE_ICON_NAMES[0]);
    url = $state("");
    group = $state("Links");
    order = $state("0");

    constructor(getResource: () => Resource | null) {
      const resource = getResource();
      this.label = resource?.label ?? "";
      this.icon = resource?.icon ?? RESOURCE_ICON_NAMES[0];
      this.url = resource?.url ?? "";
      this.group = resource?.group ?? "Links";
      this.order = String(resource?.order ?? 0);
    }
  }

  const form = new EditorForm(() => row);
  let busy = $state(false);
  let error = $state("");
  let valid = $derived(Boolean(form.label.trim() && form.url.trim()));

  async function save() {
    if (!valid || busy) return;
    busy = true;
    error = "";
    try {
      await resourcesApi.upsert({
        id: row?.id,
        label: form.label,
        icon: form.icon,
        url: form.url,
        group: form.group,
        order: Number(form.order) || 0,
      });
      onDone();
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Unable to save resource.";
    } finally {
      busy = false;
    }
  }
</script>

<section class="mb-4 rounded-xl border border-border bg-muted/30 p-4" aria-label={row ? `Edit ${row.label}` : "Add resource"}>
  <div class="grid gap-3 sm:grid-cols-2">
    <label class="grid gap-1 text-xs font-medium text-muted-foreground">
      Label
      <input class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground" bind:value={form.label} placeholder="Docs" />
    </label>
    <label class="grid gap-1 text-xs font-medium text-muted-foreground">
      Icon
      <select class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground" bind:value={form.icon}>
        {#each RESOURCE_ICON_NAMES as name (name)}
          <option value={name}>{name}</option>
        {/each}
      </select>
    </label>
    <label class="grid gap-1 text-xs font-medium text-muted-foreground sm:col-span-2">
      URL
      <input class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground" bind:value={form.url} placeholder="https:// or mailto:" />
    </label>
    <label class="grid gap-1 text-xs font-medium text-muted-foreground">
      Group
      <input class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground" bind:value={form.group} placeholder="Links" />
    </label>
    <label class="grid gap-1 text-xs font-medium text-muted-foreground">
      Order
      <input class="h-9 rounded-md border border-input bg-background px-3 text-sm text-foreground" bind:value={form.order} type="number" inputmode="numeric" />
    </label>
  </div>
  {#if error}
    <p class="mt-3 text-xs text-destructive">{error}</p>
  {/if}
  <div class="mt-3 flex gap-2">
    <button type="button" class="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" onclick={() => void save()} disabled={!valid || busy}>{busy ? "Saving…" : "Save"}</button>
    <button type="button" class="rounded-md px-3 py-2 text-sm font-medium hover:bg-muted" onclick={onCancel}>Cancel</button>
  </div>
</section>

// frontend/slices/resources-launcher-admin/components/resource-editor.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { ICON_NAMES } from "../lib/icons";
import { useResourcesApi, type Resource } from "../lib/host";

// Add / edit form for a single launcher link. `row` null = create a new link.
export function ResourceEditor({
  row,
  onDone,
  onCancel,
}: {
  row: Resource | null;
  onDone: () => void;
  onCancel: () => void;
}) {
  const api = useResourcesApi();
  const [label, setLabel] = useState(row?.label ?? "");
  const [icon, setIcon] = useState(row?.icon ?? ICON_NAMES[0]);
  const [url, setUrl] = useState(row?.url ?? "");
  const [group, setGroup] = useState(row?.group ?? "Links");
  const [order, setOrder] = useState(String(row?.order ?? 0));
  const [busy, setBusy] = useState(false);

  const valid = !!label.trim() && !!url.trim();

  async function save() {
    if (!valid || busy) return;
    setBusy(true);
    try {
      await api.upsert({
        id: row?.id,
        label: label.trim(),
        icon,
        url: url.trim(),
        group: group.trim() || "Links",
        order: Number(order) || 0,
      });
      onDone();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mb-4 rounded-lg border border-border bg-muted/30 p-3">
      <div className="grid gap-3 sm:grid-cols-2">
        <div className="grid gap-1">
          <Label className="text-xs text-muted-foreground">Label</Label>
          <Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Docs" className="h-9" />
        </div>
        <div className="grid gap-1">
          <Label className="text-xs text-muted-foreground">Icon</Label>
          <NativeSelect value={icon} onChange={(e) => setIcon(e.target.value)} className="h-9">
            {ICON_NAMES.map((n) => (
              <NativeSelectOption key={n} value={n}>
                {n}
              </NativeSelectOption>
            ))}
          </NativeSelect>
        </div>
        <div className="grid gap-1 sm:col-span-2">
          <Label className="text-xs text-muted-foreground">URL</Label>
          <Input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https:// or mailto:" className="h-9" />
        </div>
        <div className="grid gap-1">
          <Label className="text-xs text-muted-foreground">Group</Label>
          <Input value={group} onChange={(e) => setGroup(e.target.value)} placeholder="Links" className="h-9" />
        </div>
        <div className="grid gap-1">
          <Label className="text-xs text-muted-foreground">Order</Label>
          <Input value={order} onChange={(e) => setOrder(e.target.value)} placeholder="0" type="number" className="h-9" />
        </div>
      </div>
      <div className="mt-3 flex gap-2">
        <Button size="sm" onClick={save} disabled={busy || !valid}>
          {busy ? "Saving…" : "Save"}
        </Button>
        <Button size="sm" variant="ghost" onClick={onCancel}>
          Cancel
        </Button>
      </div>
    </div>
  );
}
