// frontend/slices/user-management-svelte/components/AccessMatrix.svelte
<script lang="ts">
  import RoleChip from "./RoleChip.svelte"; import { can } from "../../user-management/lib/can";
  import { DEFAULT_ACCESS_LABELS, tenantKey, type AccessCells, type AccessMatrixLabels, type MatrixUser, type TenantNode } from "../../user-management/access-types";
  import type { RoleOption } from "../../user-management/types";
  let { tenants, users, cells, roles, currentPerms, onAssign, labels: overrides = {}, className = "" }: {
    tenants: TenantNode[]; users: MatrixUser[]; cells: AccessCells; roles: RoleOption[]; currentPerms?: readonly string[];
    onAssign?: (input: { userId: string; tenantId: string | null; roleSlug: string }) => void | Promise<void>;
    labels?: Partial<AccessMatrixLabels>; className?: string;
  } = $props();
  let labels = $derived({ ...DEFAULT_ACCESS_LABELS, ...overrides }); let editable = $derived(!!currentPerms && can(currentPerms, "members.manage") && !!onAssign);
  const userLabel = (user: MatrixUser) => user.name ?? user.email ?? "Unknown";
  const roleOf = (slug?: string) => slug ? (roles.find((role) => role.slug === slug) ?? { slug, name: slug }) : undefined;
</script>

{#if users.length === 0}<p class="p-6 text-center text-sm text-muted-foreground">{labels.empty}</p>{:else}
<div class={`overflow-x-auto rounded-lg border ${className}`}><table class="w-full text-sm"><thead class="border-b"><tr><th class="sticky left-0 bg-background px-3 py-2 text-left">{labels.member}</th>{#each tenants as tenant (tenantKey(tenant.id))}<th class="whitespace-nowrap px-3 py-2 text-left">{tenant.name}</th>{/each}</tr></thead><tbody class="divide-y">
{#each users as user (user.userId)}<tr><td class="sticky left-0 bg-background px-3 py-2"><div class="flex items-center gap-2"><span class="grid h-6 w-6 place-items-center rounded-full bg-muted text-[9px]">{userLabel(user).slice(0, 2).toUpperCase()}</span><span class="truncate">{userLabel(user)}</span></div></td>
{#each tenants as tenant (tenantKey(tenant.id))}{@const slug = cells[user.userId]?.[tenantKey(tenant.id)]}{@const role = roleOf(slug)}<td class="px-3 py-2">{#if editable}<select class="rounded-md border bg-background px-2 py-1 text-xs" value={slug ?? ""} onchange={(event) => { if (event.currentTarget.value) onAssign?.({ userId: user.userId, tenantId: tenant.id, roleSlug: event.currentTarget.value }); }}><option value="">{labels.noAccess}</option>{#each roles as option (option.slug)}<option value={option.slug}>{option.name}</option>{/each}</select>{:else if role}<RoleChip {role} />{:else}<span class="text-xs text-muted-foreground">{labels.noAccess}</span>{/if}</td>{/each}</tr>{/each}
</tbody></table></div>{/if}

// frontend/slices/user-management/components/AccessMatrix.tsx
"use client";

// AccessMatrix (P4c) — users (rows) × tenants (columns) grid showing each
// user's role per tenant across a hierarchy. Read-only by default; when
// `currentPerms` grants members.manage and `onAssign` is passed, each cell
// becomes a role select. Props-driven + RBAC-agnostic.

import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { RoleChip } from "./RoleChip";
import { can } from "../lib/can";
import { DEFAULT_ACCESS_LABELS, tenantKey } from "../access-types";
import type { TenantNode, MatrixUser, AccessCells, AccessMatrixLabels } from "../access-types";
import type { RoleOption } from "../types";

export interface AccessMatrixProps {
  tenants: TenantNode[];
  users: MatrixUser[];
  cells: AccessCells;
  roles: RoleOption[];
  currentPerms?: readonly string[];
  onAssign?: (i: { userId: string; tenantId: string | null; roleSlug: string }) => void;
  labels?: Partial<AccessMatrixLabels>;
  className?: string;
}

function ulabel(u: MatrixUser) { return u.name ?? u.email ?? "Unknown"; }

export function AccessMatrix({ tenants, users, cells, roles, currentPerms, onAssign, labels: over, className }: AccessMatrixProps) {
  const labels: AccessMatrixLabels = { ...DEFAULT_ACCESS_LABELS, ...over };
  const editable = !!currentPerms && can(currentPerms, "members.manage") && !!onAssign;

  if (!users.length) {
    return <p className="p-6 text-center text-sm text-muted-foreground">{labels.empty}</p>;
  }

  return (
    <div className={cn("overflow-x-auto rounded-lg border", className)}>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="sticky left-0 bg-background">{labels.member}</TableHead>
            {tenants.map((t) => (
              <TableHead key={tenantKey(t.id)} className="whitespace-nowrap">{t.name}</TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {users.map((u) => (
            <TableRow key={u.userId}>
              <TableCell className="sticky left-0 bg-background">
                <div className="flex items-center gap-2">
                  <Avatar className="h-6 w-6">
                    <AvatarImage src={u.avatarUrl} alt="" />
                    <AvatarFallback className="text-[9px]">{ulabel(u).slice(0, 2).toUpperCase()}</AvatarFallback>
                  </Avatar>
                  <span className="truncate text-sm">{ulabel(u)}</span>
                </div>
              </TableCell>
              {tenants.map((t) => {
                const slug = cells[u.userId]?.[tenantKey(t.id)];
                const role = slug ? roles.find((r) => r.slug === slug) ?? { slug, name: slug } : undefined;
                return (
                  <TableCell key={tenantKey(t.id)}>
                    {editable ? (
                      <Select value={slug ?? ""} onValueChange={(v) => onAssign!({ userId: u.userId, tenantId: t.id, roleSlug: v })}>
                        <SelectTrigger className="h-7 w-[120px] text-xs"><SelectValue placeholder={labels.noAccess} /></SelectTrigger>
                        <SelectContent>
                          {roles.map((r) => <SelectItem key={r.slug} value={r.slug}>{r.name}</SelectItem>)}
                        </SelectContent>
                      </Select>
                    ) : role ? (
                      <RoleChip role={role} />
                    ) : (
                      <span className="text-xs text-muted-foreground">{labels.noAccess}</span>
                    )}
                  </TableCell>
                );
              })}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
