// frontend/slices/user-management-svelte/components/MembersTable.svelte
<script lang="ts">
  import MemberRowActions from "./MemberRowActions.svelte";
  import RoleChip from "./RoleChip.svelte";
  import type { SortDir, SortKey } from "../../user-management/lib/members-core";
  import type { Member, MembersLabels, RoleOption } from "../../user-management/types";
  let { rows, roles, canManage, sortKey, sortDir, onSort, onUpdateRole, onRemove, labels }: {
    rows: Member[]; roles: RoleOption[]; canManage: boolean; sortKey: SortKey; sortDir: SortDir;
    onSort: (key: SortKey) => void;
    onUpdateRole?: (input: { userId: string; roleSlug: string }) => void | Promise<void>;
    onRemove?: (input: { userId: string }) => void | Promise<void>; labels: MembersLabels;
  } = $props();
  const displayName = (member: Member) => member.name ?? member.email ?? "Unknown";
  const initials = (member: Member) => displayName(member).trim().slice(0, 2).toUpperCase();
  const roleOf = (slug: string) => roles.find((role) => role.slug === slug) ?? { slug, name: slug };
  const date = (ts?: number) => ts ? new Date(ts).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";
  const marker = (key: SortKey) => sortKey === key ? (sortDir === "asc" ? "↑" : "↓") : "↕";
</script>

<div class="overflow-x-auto">
  <table class="w-full text-sm">
    <thead class="border-b text-left text-xs text-muted-foreground"><tr>
      <th class="px-3 py-2"><button type="button" onclick={() => onSort("name")}>{labels.columnsMember} {marker("name")}</button></th>
      <th class="px-3 py-2"><button type="button" onclick={() => onSort("role")}>{labels.columnsRole} {marker("role")}</button></th>
      <th class="hidden px-3 py-2 sm:table-cell"><button type="button" onclick={() => onSort("joined")}>{labels.columnsJoined} {marker("joined")}</button></th>
      <th class="px-3 py-2"></th>
    </tr></thead>
    <tbody class="divide-y">
      {#each rows as member (member.userId)}
        <tr class:opacity-60={member.status !== "active"}>
          <td class="px-3 py-2"><div class="flex items-center gap-2.5">
            <span class="grid h-7 w-7 place-items-center rounded-full bg-muted text-[10px]">{initials(member)}</span>
            <div class="min-w-0"><p class="truncate font-medium">{displayName(member)}</p>{#if member.name && member.email}<p class="truncate text-xs text-muted-foreground">{member.email}</p>{/if}</div>
          </div></td>
          <td class="px-3 py-2">
            {#if member.status === "pending"}<span class="text-xs text-muted-foreground">{labels.pending}</span>
            {:else if canManage && onUpdateRole}
              <select class="rounded-md border bg-background px-2 py-1 text-xs" value={member.roleSlug}
                onchange={(event) => onUpdateRole?.({ userId: member.userId, roleSlug: event.currentTarget.value })}>
                {#each roles as role (role.slug)}<option value={role.slug}>{role.name}</option>{/each}
              </select>
            {:else}<RoleChip role={roleOf(member.roleSlug)} />{/if}
          </td>
          <td class="hidden px-3 py-2 text-xs text-muted-foreground sm:table-cell">{date(member.joinedAt)}</td>
          <td class="px-3 py-2"><MemberRowActions {canManage} onRemove={onRemove ? () => onRemove?.({ userId: member.userId }) : undefined} {labels} /></td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// frontend/slices/user-management/components/MembersTable.tsx
"use client";

import type { ReactNode } from "react";
import { ArrowUpDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { RoleChip } from "./RoleChip";
import { MemberRowActions } from "./MemberRowActions";
import type { Member, RoleOption, MembersLabels } from "../types";
import type { SortKey } from "../hooks/useMembersView";

interface Props {
  rows: Member[];
  roles: RoleOption[];
  canManage: boolean;
  sortKey: SortKey;
  sortDir: "asc" | "desc";
  onSort: (k: SortKey) => void;
  onUpdateRole?: (m: { userId: string; roleSlug: string }) => void;
  onRemove?: (m: { userId: string }) => void;
  labels: MembersLabels;
}

function initials(m: Member) {
  return (m.name ?? m.email ?? "?").trim().slice(0, 2).toUpperCase();
}
function fmtDate(ts?: number) {
  return ts ? new Date(ts).toLocaleDateString("default", { month: "short", day: "numeric", year: "numeric" }) : "—";
}
function roleOf(slug: string, roles: RoleOption[]): RoleOption {
  return roles.find((r) => r.slug === slug) ?? { slug, name: slug };
}

export function MembersTable({
  rows, roles, canManage, sortKey, onSort, onUpdateRole, onRemove, labels,
}: Props) {
  const SortBtn = ({ k, children }: { k: SortKey; children: ReactNode }) => (
    <Button
      variant="ghost" size="sm" onClick={() => onSort(k)}
      className="-ml-1 h-auto gap-1 px-1 text-xs font-medium text-muted-foreground hover:bg-transparent"
    >
      {children}
      <ArrowUpDown className={cn("h-3 w-3", sortKey === k ? "text-foreground" : "opacity-40")} />
    </Button>
  );

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead><SortBtn k="name">{labels.columnsMember}</SortBtn></TableHead>
          <TableHead><SortBtn k="role">{labels.columnsRole}</SortBtn></TableHead>
          <TableHead className="hidden sm:table-cell"><SortBtn k="joined">{labels.columnsJoined}</SortBtn></TableHead>
          <TableHead className="w-8" />
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((m) => (
          <TableRow key={m.userId} className={m.status !== "active" ? "opacity-60" : undefined}>
            <TableCell>
              <div className="flex items-center gap-2.5">
                <Avatar className="h-7 w-7">
                  <AvatarImage src={m.avatarUrl} alt="" />
                  <AvatarFallback className="text-[10px]">{initials(m)}</AvatarFallback>
                </Avatar>
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium">{m.name ?? m.email ?? "Unknown"}</p>
                  {m.name && m.email ? <p className="truncate text-xs text-muted-foreground">{m.email}</p> : null}
                </div>
              </div>
            </TableCell>
            <TableCell>
              {m.status === "pending" ? (
                <span className="text-xs text-muted-foreground">{labels.pending}</span>
              ) : canManage && onUpdateRole ? (
                <Select value={m.roleSlug} onValueChange={(slug) => onUpdateRole({ userId: m.userId, roleSlug: slug })}>
                  <SelectTrigger className="h-7 w-[140px] text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {roles.map((r) => <SelectItem key={r.slug} value={r.slug}>{r.name}</SelectItem>)}
                  </SelectContent>
                </Select>
              ) : (
                <RoleChip role={roleOf(m.roleSlug, roles)} />
              )}
            </TableCell>
            <TableCell className="hidden text-xs text-muted-foreground sm:table-cell">{fmtDate(m.joinedAt)}</TableCell>
            <TableCell>
              <MemberRowActions
                canManage={canManage}
                onRemove={onRemove ? () => onRemove({ userId: m.userId }) : undefined}
                labels={labels}
              />
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
