// frontend/slices/user-management-svelte/components/MembersPanel.svelte
<script lang="ts">
  import InviteDialog from "./InviteDialog.svelte"; import MembersTable from "./MembersTable.svelte"; import MembersToolbar from "./MembersToolbar.svelte"; import PendingInvites from "./PendingInvites.svelte";
  import { can } from "../../user-management/lib/can"; import { deriveMembersView, nextSort, type SortDir, type SortKey } from "../../user-management/lib/members-core";
  import { DEFAULT_MEMBERS_LABELS, type Invite, type InviteInput, type Member, type MembersLabels, type RoleOption } from "../../user-management/types";
  let { members, roles, currentPerms, onUpdateRole, onRemove, onInvite, invites, onCancelInvite, onResendInvite, allowPropagate = false, labels: overrides = {}, className = "" }: {
    members: Member[] | undefined; roles: RoleOption[]; currentPerms: readonly string[];
    onUpdateRole?: (input: { userId: string; roleSlug: string }) => void | Promise<void>; onRemove?: (input: { userId: string }) => void | Promise<void>;
    onInvite?: (input: InviteInput) => void | Promise<void>; invites?: Invite[]; onCancelInvite?: (input: { inviteId: string }) => void | Promise<void>;
    onResendInvite?: (input: { inviteId: string }) => void | Promise<void>; allowPropagate?: boolean; labels?: Partial<MembersLabels>; className?: string;
  } = $props();
  let query = $state(""); let roleFilter = $state("all"); let sortKey = $state<SortKey>("name"); let sortDir = $state<SortDir>("asc"); let inviteOpen = $state(false);
  let labels = $derived({ ...DEFAULT_MEMBERS_LABELS, ...overrides }); let canManage = $derived(can(currentPerms, "members.manage")); let canInvite = $derived(can(currentPerms, "members.invite"));
  let rows = $derived(deriveMembersView({ members, query, roleFilter, sortKey, sortDir })); let total = $derived(members?.length ?? 0); let showInvite = $derived(canInvite && !!onInvite);
  function sort(key: SortKey) { const next = nextSort(sortKey, sortDir, key); sortKey = next.sortKey; sortDir = next.sortDir; }
</script>

<div class={className}>
  <MembersToolbar {query} {roleFilter} {roles} canInvite={showInvite} onQuery={(value) => query = value} onRoleFilter={(value) => roleFilter = value} onInvite={() => inviteOpen = true} {labels} />
  {#if (canInvite || canManage) && invites?.length}<PendingInvites className="mt-3" {invites} {roles} canModify={canInvite} onCancel={onCancelInvite} onResend={onResendInvite} {labels} />{/if}
  <div class="mt-3 overflow-hidden rounded-lg border">
    {#if members === undefined}<p class="p-6 text-center text-sm text-muted-foreground">{labels.loading}</p>
    {:else if rows.length === 0}<p class="p-6 text-center text-sm text-muted-foreground">{labels.empty}</p>
    {:else}<MembersTable {rows} {roles} {canManage} {sortKey} {sortDir} onSort={sort} {onUpdateRole} {onRemove} {labels} />{/if}
  </div>
  {#if members !== undefined}<p class="mt-2 text-xs text-muted-foreground">{rows.length} of {total} member{total === 1 ? "" : "s"}</p>{/if}
  {#if onInvite}<InviteDialog open={inviteOpen} onOpenChange={(value) => inviteOpen = value} {roles} onSubmit={onInvite} {labels} {allowPropagate} />{/if}
</div>

// frontend/slices/user-management/components/MembersPanel.tsx
"use client";

// MembersPanel — the members surface. Props-driven + RBAC-agnostic: pass
// `roles` (options) + `currentPerms` (the actor's resolved permission
// strings, wired from rbac-roles at the app level) + CRUD callbacks.
// `members === undefined` renders a loading state. Pass `onInvite` +
// `invites` to enable the invite dialog + pending list (members.invite).

import { useState } from "react";
import { can } from "../lib/can";
import { useMembersView } from "../hooks/useMembersView";
import { MembersToolbar } from "./MembersToolbar";
import { MembersTable } from "./MembersTable";
import { PendingInvites } from "./PendingInvites";
import { InviteDialog } from "./InviteDialog";
import { DEFAULT_MEMBERS_LABELS } from "../types";
import type { Member, RoleOption, MembersLabels, Invite, InviteInput } from "../types";

export interface MembersPanelProps {
  members: Member[] | undefined;
  /** Role options for the dropdown / filter / badge (e.g. rbac-roles' presets). */
  roles: RoleOption[];
  /** The actor's resolved permission strings — gates manage / invite. */
  currentPerms: readonly string[];
  onUpdateRole?: (m: { userId: string; roleSlug: string }) => void | Promise<void>;
  onRemove?: (m: { userId: string }) => void | Promise<void>;
  /** Send handler — when set + members.invite, shows the invite button + dialog. */
  onInvite?: (i: InviteInput) => void | Promise<void>;
  /** Pending invitations (e.g. your `listInvites` query). */
  invites?: Invite[];
  onCancelInvite?: (i: { inviteId: string }) => void | Promise<void>;
  onResendInvite?: (i: { inviteId: string }) => void | Promise<void>;
  labels?: Partial<MembersLabels>;
  className?: string;
}

export function MembersPanel({
  members, roles, currentPerms, onUpdateRole, onRemove,
  onInvite, invites, onCancelInvite, onResendInvite, labels: over, className,
}: MembersPanelProps) {
  const labels: MembersLabels = { ...DEFAULT_MEMBERS_LABELS, ...over };
  const view = useMembersView(members);
  const canManage = can(currentPerms, "members.manage");
  const canInvite = can(currentPerms, "members.invite");
  const loading = members === undefined;
  const showInvite = canInvite && !!onInvite;
  const [inviteOpen, setInviteOpen] = useState(false);

  return (
    <div className={className}>
      <MembersToolbar
        query={view.query} onQuery={view.setQuery}
        roleFilter={view.roleFilter} onRoleFilter={view.setRoleFilter}
        roles={roles} canInvite={showInvite} onInvite={() => setInviteOpen(true)} labels={labels}
      />

      {(canInvite || canManage) && invites && invites.length ? (
        <PendingInvites
          className="mt-3" invites={invites} roles={roles} canModify={canInvite}
          onCancel={onCancelInvite} onResend={onResendInvite} labels={labels}
        />
      ) : null}

      <div className="mt-3 overflow-hidden rounded-lg border">
        {loading ? (
          <p className="p-6 text-center text-sm text-muted-foreground">{labels.loading}</p>
        ) : view.rows.length === 0 ? (
          <p className="p-6 text-center text-sm text-muted-foreground">{labels.empty}</p>
        ) : (
          <MembersTable
            rows={view.rows} roles={roles} canManage={canManage}
            sortKey={view.sortKey} sortDir={view.sortDir} onSort={view.toggleSort}
            onUpdateRole={onUpdateRole} onRemove={onRemove} labels={labels}
          />
        )}
      </div>

      {!loading ? (
        <p className="mt-2 text-xs text-muted-foreground">
          {view.rows.length} of {view.total} member{view.total === 1 ? "" : "s"}
        </p>
      ) : null}

      {onInvite ? (
        <InviteDialog
          open={inviteOpen} onOpenChange={setInviteOpen}
          roles={roles} onSubmit={onInvite} labels={labels}
        />
      ) : null}
    </div>
  );
}
