// frontend/slices/user-management-svelte/components/MembersToolbar.svelte
<script lang="ts">
  import type { MembersLabels, RoleOption } from "../../user-management/types";
  let { query, roleFilter, roles, canInvite, onQuery, onRoleFilter, onInvite, labels }: {
    query: string; roleFilter: string; roles: RoleOption[]; canInvite: boolean;
    onQuery: (value: string) => void; onRoleFilter: (value: string) => void; onInvite?: () => void; labels: MembersLabels;
  } = $props();
</script>

<div class="flex flex-wrap items-center gap-2">
  <input class="min-w-[200px] flex-1 rounded-md border bg-background px-3 py-2 text-sm" value={query}
    oninput={(event) => onQuery(event.currentTarget.value)} placeholder={labels.searchPlaceholder} aria-label={labels.searchPlaceholder} />
  <select class="rounded-md border bg-background px-3 py-2 text-sm" value={roleFilter}
    onchange={(event) => onRoleFilter(event.currentTarget.value)} aria-label={labels.allRoles}>
    <option value="all">{labels.allRoles}</option>
    {#each roles as role (role.slug)}<option value={role.slug}>{role.name}</option>{/each}
  </select>
  {#if canInvite && onInvite}
    <button type="button" class="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground" onclick={onInvite}>{labels.invite}</button>
  {/if}
</div>

// frontend/slices/user-management/components/MembersToolbar.tsx
"use client";

import { Search, UserPlus } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import type { RoleOption, MembersLabels } from "../types";

interface Props {
  query: string;
  onQuery: (q: string) => void;
  roleFilter: string;
  onRoleFilter: (r: string) => void;
  roles: RoleOption[];
  canInvite: boolean;
  onInvite?: () => void;
  labels: MembersLabels;
}

export function MembersToolbar({
  query, onQuery, roleFilter, onRoleFilter, roles, canInvite, onInvite, labels,
}: Props) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <div className="relative min-w-[200px] flex-1">
        <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          value={query}
          onChange={(e) => onQuery(e.target.value)}
          placeholder={labels.searchPlaceholder}
          aria-label={labels.searchPlaceholder}
          className="pl-8"
        />
      </div>
      <Select value={roleFilter} onValueChange={onRoleFilter}>
        <SelectTrigger className="w-[150px]"><SelectValue /></SelectTrigger>
        <SelectContent>
          <SelectItem value="all">{labels.allRoles}</SelectItem>
          {roles.map((r) => (
            <SelectItem key={r.slug} value={r.slug}>{r.name}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      {canInvite && onInvite ? (
        <Button type="button" size="sm" onClick={onInvite}>
          <UserPlus className="mr-2 h-4 w-4" />
          {labels.invite}
        </Button>
      ) : null}
    </div>
  );
}
