// frontend/slices/profile-svelte/variants/resume/app.svelte
<script lang="ts">
  import { readResumeProfile } from "@/features/profile/lib/core";

  const profile = readResumeProfile();

  function contactMark(href: string): string {
    if (href.startsWith("mailto:")) return "@";
    if (/^https?:/.test(href)) return "↗";
    return "•";
  }

  function printResume() {
    if (typeof window !== "undefined") window.print();
  }
</script>

<div class="h-full overflow-y-auto bg-card text-foreground">
  <article class="mx-auto max-w-2xl px-7 py-8 print:px-0 print:py-0">
    <header class="flex items-start justify-between gap-4 border-b border-border pb-5">
      <div class="min-w-0">
        <h1 class="text-2xl font-semibold tracking-tight">{profile.name}</h1>
        <p class="mt-1 text-sm font-medium text-muted-foreground">{profile.roles.join(" · ")}</p>
        {#if profile.location}
          <p class="mt-1 text-xs text-muted-foreground">⌖ {profile.location}</p>
        {/if}
        <div class="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-xs">
          {#each profile.contacts as contact (contact.href)}
            <a
              href={contact.href}
              target="_blank"
              rel="noreferrer noopener"
              class="inline-flex items-center gap-1.5 text-muted-foreground transition-colors hover:text-primary"
            >
              <span aria-hidden="true">{contactMark(contact.href)}</span>
              <span class="truncate">{contact.label}</span>
            </a>
          {/each}
        </div>
      </div>
      <button type="button" class="shrink-0 rounded-md border px-3 py-1.5 text-xs font-medium print:hidden" onclick={printResume}>
        Print / PDF
      </button>
    </header>

    <section class="mt-6">
      <h2 class="text-sm font-semibold tracking-tight">Summary</h2>
      <p class="mt-2.5 text-sm leading-relaxed text-muted-foreground">{profile.summary}</p>
    </section>

    <section class="mt-6">
      <h2 class="text-sm font-semibold tracking-tight">Skills</h2>
      <div class="mt-2.5 flex flex-wrap gap-1.5">
        {#each profile.skills as skill (skill)}
          <span class="rounded-full border border-border bg-foreground/5 px-2.5 py-1 text-xs">{skill}</span>
        {/each}
      </div>
    </section>

    <section class="mt-6">
      <h2 class="text-sm font-semibold tracking-tight">Experience</h2>
      <div class="mt-2.5 flex flex-col gap-4">
        {#each profile.experience as experience (`${experience.org}-${experience.role}`)}
          <div>
            <div class="flex items-baseline justify-between gap-3">
              <h3 class="text-sm font-medium">{experience.role} · <span class="text-muted-foreground">{experience.org}</span></h3>
              <span class="shrink-0 text-xs text-muted-foreground">{experience.period}</span>
            </div>
            <ul class="mt-1.5 list-disc space-y-1 pl-4">
              {#each experience.points as point (point)}
                <li class="text-xs text-muted-foreground">{point}</li>
              {/each}
            </ul>
          </div>
        {/each}
      </div>
    </section>

    <section class="mt-6">
      <h2 class="text-sm font-semibold tracking-tight">Projects</h2>
      <div class="mt-2.5 flex flex-col gap-3">
        {#each profile.projects as project (project.name)}
          <div class="rounded-lg border border-border bg-card/60 p-3">
            <h3 class="truncate text-sm font-medium">{project.name}</h3>
            <p class="mt-0.5 text-xs text-muted-foreground">{project.desc}</p>
            {#if project.url}
              <a href={project.url} target="_blank" rel="noreferrer noopener" class="mt-1.5 inline-flex items-center gap-1 text-xs text-primary hover:underline">
                {project.url.replace(/^https?:\/\//, "")} ↗
              </a>
            {/if}
          </div>
        {/each}
      </div>
    </section>
  </article>
</div>

// frontend/slices/profile/variants/resume/app.tsx
"use client";

import {
  FileText, Mail, Globe, Link2, ArrowUpRight, Sparkles, Briefcase, Code2,
  MapPin, Printer, type LucideIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useResumeProfile } from "./lib/host";
import { Section } from "./components/section";

// Pick a contact glyph from the href shape (no brand-specific icon mapping).
function contactIcon(href: string): LucideIcon {
  if (href.startsWith("mailto:")) return Mail;
  if (/^https?:/.test(href)) return Globe;
  return Link2;
}

// Default export so an os-shell can lazy-load this as a window app. Renders
// whatever profile the host injected via configureResume() — a generic
// placeholder person until then. The print:* utilities give a clean PDF when
// the viewer hits "Print / PDF" (window.print()).
export default function Resume() {
  const p = useResumeProfile();
  return (
    <ScrollArea className="h-full bg-card text-foreground">
      <div className="mx-auto max-w-2xl px-7 py-8 print:px-0 print:py-0">
        <header className="flex items-start justify-between gap-4 border-b border-border pb-5">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">{p.name}</h1>
            <p className="mt-1 text-sm font-medium text-muted-foreground">{p.roles.join(" · ")}</p>
            {p.location && (
              <p className="mt-1 inline-flex items-center gap-1.5 text-xs text-muted-foreground">
                <MapPin className="size-3.5" /> {p.location}
              </p>
            )}
            <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-xs">
              {p.contacts.map((c) => {
                const Icon = contactIcon(c.href);
                return (
                  <a
                    key={c.href}
                    href={c.href}
                    target="_blank"
                    rel="noreferrer noopener"
                    className="inline-flex items-center gap-1.5 text-muted-foreground transition-colors hover:text-primary"
                  >
                    <Icon className="size-3.5 shrink-0" />
                    <span className="truncate">{c.label}</span>
                  </a>
                );
              })}
            </div>
          </div>
          <Button
            size="sm"
            variant="outline"
            className="shrink-0 gap-1.5 print:hidden"
            onClick={() => window.print()}
          >
            <Printer className="size-3.5" /> Print / PDF
          </Button>
        </header>

        <Section icon={FileText} title="Summary">
          <p className="text-sm leading-relaxed text-muted-foreground">{p.summary}</p>
        </Section>

        <Section icon={Sparkles} title="Skills">
          <div className="flex flex-wrap gap-1.5">
            {p.skills.map((s) => (
              <span key={s} className="rounded-full border border-border bg-foreground/5 px-2.5 py-1 text-xs">
                {s}
              </span>
            ))}
          </div>
        </Section>

        <Section icon={Briefcase} title="Experience">
          <div className="flex flex-col gap-4">
            {p.experience.map((e) => (
              <div key={`${e.org}-${e.role}`}>
                <div className="flex items-baseline justify-between gap-3">
                  <h3 className="text-sm font-medium">
                    {e.role} · <span className="text-muted-foreground">{e.org}</span>
                  </h3>
                  <span className="shrink-0 text-xs text-muted-foreground">{e.period}</span>
                </div>
                <ul className="mt-1.5 list-disc space-y-1 pl-4">
                  {e.points.map((pt) => (
                    <li key={pt} className="text-xs text-muted-foreground">{pt}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </Section>

        <Section icon={Code2} title="Projects">
          <div className="flex flex-col gap-3">
            {p.projects.map((pr) => (
              <div key={pr.name} className="rounded-lg border border-border bg-card/60 p-3">
                <h3 className="truncate text-sm font-medium">{pr.name}</h3>
                <p className="mt-0.5 text-xs text-muted-foreground">{pr.desc}</p>
                {pr.url && (
                  <a
                    href={pr.url}
                    target="_blank"
                    rel="noreferrer noopener"
                    className="mt-1.5 inline-flex items-center gap-1 text-xs text-primary hover:underline"
                  >
                    {pr.url.replace(/^https?:\/\//, "")} <ArrowUpRight className="size-3" />
                  </a>
                )}
              </div>
            ))}
          </div>
        </Section>
      </div>
    </ScrollArea>
  );
}
