// frontend/slices/profile-svelte/variants/card/app.svelte
<script lang="ts">
  import { initials, readAboutProfile } from "@/features/profile/lib/core";
  import FaqList from "./components/FaqList.svelte";

  const profile = readAboutProfile();
</script>

<div class="h-full overflow-y-auto bg-background text-foreground">
  <article class="flex flex-col items-center px-6 py-8 text-center">
    <div class="grid size-20 place-items-center overflow-hidden rounded-3xl bg-primary text-2xl font-semibold text-primary-foreground shadow-lg">
      {#if profile.avatarUrl}
        <img src={profile.avatarUrl} alt={profile.name} class="size-full object-cover" />
      {:else}
        {initials(profile.name)}
      {/if}
    </div>

    <h1 class="mt-5 text-2xl font-semibold tracking-tight">{profile.name}</h1>
    <p class="mt-1 text-xs font-medium text-muted-foreground">{profile.roles.join(" · ")}</p>
    {#if profile.location}
      <p class="mt-1 text-[11px] text-muted-foreground">⌖ {profile.location}</p>
    {/if}

    <p class="mt-4 max-w-sm text-xs leading-relaxed text-muted-foreground">{profile.description}</p>

    {#if profile.links.length > 0}
      <div class="mt-6 flex w-full max-w-sm flex-col gap-2 text-left">
        {#each profile.links as link (link.href)}
          <a
            href={link.href}
            target="_blank"
            rel="noreferrer noopener"
            class="flex items-center gap-3 rounded-lg border border-border bg-card/60 px-3 py-2 text-sm transition-colors hover:bg-foreground/5"
          >
            <span aria-hidden="true">{link.href.startsWith("mailto:") ? "@" : "↗"}</span>
            <span class="truncate">{link.label}</span>
            <span class="ml-auto text-muted-foreground" aria-hidden="true">↗</span>
          </a>
        {/each}
      </div>
    {/if}

    {#if profile.faq.length > 0}
      <div class="mt-6 w-full max-w-sm text-left">
        <h2 class="mb-2 text-sm font-semibold">FAQ</h2>
        <FaqList items={profile.faq} />
      </div>
    {/if}
  </article>
</div>

// frontend/slices/profile/variants/card/app.tsx
"use client";

import { Mail, Link2, ArrowUpRight, MapPin } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { initials, type AboutLink } from "@/features/profile/lib/core";
import { useAboutProfile } from "./lib/host";
import { FaqList } from "./components/faq-list";

// Default export so an os-shell can lazy-load this as a window app. The whole
// card is driven by the injected profile (host seam) — mock until configured.

function LinkRow({ label, href }: AboutLink) {
  const Icon = href.startsWith("mailto:") ? Mail : Link2;
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer noopener"
      className="flex items-center gap-3 rounded-lg border border-border bg-card/60 px-3 py-2 text-sm transition-colors hover:bg-foreground/5"
    >
      <Icon className="size-4 shrink-0 text-primary" />
      <span className="truncate">{label}</span>
      <ArrowUpRight className="ml-auto size-3.5 shrink-0 text-muted-foreground" />
    </a>
  );
}

export default function AboutProfile() {
  const p = useAboutProfile();
  return (
    <ScrollArea className="h-full bg-background text-foreground">
      <div className="flex flex-col items-center px-6 py-8 text-center">
        <Avatar className="size-20 rounded-3xl shadow-lg">
          {p.avatarUrl ? <AvatarImage src={p.avatarUrl} alt={p.name} /> : null}
          <AvatarFallback className="rounded-3xl bg-primary text-2xl font-semibold text-primary-foreground">
            {initials(p.name)}
          </AvatarFallback>
        </Avatar>

        <h1 className="mt-5 text-2xl font-semibold tracking-tight">{p.name}</h1>
        <p className="mt-1 text-xs font-medium text-muted-foreground">{p.roles.join(" · ")}</p>
        {p.location ? (
          <p className="mt-1 inline-flex items-center gap-1 text-[11px] text-muted-foreground">
            <MapPin className="size-3" /> {p.location}
          </p>
        ) : null}

        <p className="mt-4 max-w-sm text-xs leading-relaxed text-muted-foreground">{p.description}</p>

        {p.links.length > 0 ? (
          <div className="mt-6 flex w-full max-w-sm flex-col gap-2 text-left">
            {p.links.map((l) => (
              <LinkRow key={l.href} {...l} />
            ))}
          </div>
        ) : null}

        {p.faq.length > 0 ? (
          <div className="mt-6 w-full max-w-sm text-left">
            <h2 className="mb-2 text-sm font-semibold">FAQ</h2>
            <FaqList items={p.faq} />
          </div>
        ) : null}
      </div>
    </ScrollArea>
  );
}
