// frontend/slices/settings-page/components/sections/ProfileSection.tsx
"use client";

import * as React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { SettingsProfile } from "../../lib/adapter";

function initials(name: string): string {
  return (
    name
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((w) => w[0]?.toUpperCase() ?? "")
      .join("") || "?"
  );
}

export interface ProfileSectionProps {
  value: SettingsProfile;
  saving?: boolean;
  onSave: (profile: SettingsProfile) => void | Promise<void>;
}

export function ProfileSection({ value, saving, onSave }: ProfileSectionProps) {
  const [draft, setDraft] = React.useState<SettingsProfile>(value);
  React.useEffect(() => setDraft(value), [value]);

  const dirty = JSON.stringify(draft) !== JSON.stringify(value);
  const set = (patch: Partial<SettingsProfile>) =>
    setDraft((d) => ({ ...d, ...patch }));

  return (
    <Card>
      <CardHeader>
        <CardTitle>Profile</CardTitle>
        <CardDescription>Your public identity and contact details.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex items-center gap-4">
          <Avatar className="size-16">
            {draft.avatarUrl ? <AvatarImage src={draft.avatarUrl} alt={draft.name} /> : null}
            <AvatarFallback className="text-lg">{initials(draft.name)}</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-1.5">
            <Label htmlFor="sp-avatar">Avatar URL</Label>
            <Input
              id="sp-avatar"
              value={draft.avatarUrl ?? ""}
              placeholder="https://…"
              onChange={(e) => set({ avatarUrl: e.target.value || undefined })}
            />
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor="sp-name">Name</Label>
            <Input
              id="sp-name"
              value={draft.name}
              onChange={(e) => set({ name: e.target.value })}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="sp-email">Email</Label>
            <Input
              id="sp-email"
              type="email"
              value={draft.email}
              onChange={(e) => set({ email: e.target.value })}
            />
          </div>
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="sp-bio">Bio</Label>
          <Textarea
            id="sp-bio"
            rows={3}
            value={draft.bio ?? ""}
            placeholder="A short bio…"
            onChange={(e) => set({ bio: e.target.value || undefined })}
          />
        </div>

        <div className="flex justify-end">
          <Button disabled={saving || !dirty} onClick={() => onSave(draft)}>
            {saving ? "Saving…" : "Save changes"}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// frontend/slices/settings-svelte/variants/account/components/sections/ProfileSection.svelte
<script lang="ts">
  import {
    settingsProfileInitials,
  } from "@/features/settings/variants/account/lib/core";
  import type { SettingsProfile } from "@/features/settings/variants/account/lib/adapter";

  let {
    value,
    saving = false,
    onSave,
  } = $props<{
    value: SettingsProfile;
    saving?: boolean;
    onSave: (profile: SettingsProfile) => void | Promise<void>;
  }>();

  let draft = $state<SettingsProfile>({ name: "", email: "", avatarUrl: undefined, bio: "" });
  let dirty = $derived(JSON.stringify(draft) !== JSON.stringify(value));

  $effect(() => {
    draft = { ...value };
  });

  function patch(next: Partial<SettingsProfile>) {
    draft = { ...draft, ...next };
  }
</script>

<section class="rounded-xl border bg-card text-card-foreground shadow-sm">
  <header class="space-y-1.5 border-b px-5 py-4">
    <h2 class="font-semibold">Profile</h2>
    <p class="text-sm text-muted-foreground">Your public identity and contact details.</p>
  </header>
  <div class="space-y-5 p-5">
    <div class="flex items-center gap-4">
      <div class="grid size-16 shrink-0 place-items-center overflow-hidden rounded-full bg-muted text-lg font-semibold">
        {#if draft.avatarUrl}
          <img src={draft.avatarUrl} alt={draft.name || "Profile avatar"} class="size-full object-cover" />
        {:else}
          {settingsProfileInitials(draft)}
        {/if}
      </div>
      <label class="flex-1 space-y-1.5 text-sm">
        <span class="font-medium">Avatar URL</span>
        <input
          value={draft.avatarUrl ?? ""}
          oninput={(event) => patch({ avatarUrl: event.currentTarget.value || undefined })}
          placeholder="https://…"
          class="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
        />
      </label>
    </div>

    <div class="grid gap-4 sm:grid-cols-2">
      <label class="space-y-1.5 text-sm">
        <span class="font-medium">Name</span>
        <input
          value={draft.name}
          oninput={(event) => patch({ name: event.currentTarget.value })}
          class="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
        />
      </label>
      <label class="space-y-1.5 text-sm">
        <span class="font-medium">Email</span>
        <input
          type="email"
          value={draft.email}
          oninput={(event) => patch({ email: event.currentTarget.value })}
          class="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
        />
      </label>
    </div>

    <label class="space-y-1.5 text-sm">
      <span class="font-medium">Bio</span>
      <textarea
        rows="3"
        value={draft.bio ?? ""}
        oninput={(event) => patch({ bio: event.currentTarget.value || undefined })}
        placeholder="A short bio…"
        class="min-h-24 w-full resize-y rounded-md border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring"
      ></textarea>
    </label>

    <div class="flex justify-end">
      <button
        type="button"
        disabled={saving || !dirty}
        onclick={() => onSave(draft)}
        class="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {saving ? "Saving…" : "Save changes"}
      </button>
    </div>
  </div>
</section>
