// frontend/slices/library/components/CopyButton.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

// Portable copy-to-clipboard button — shows a transient "Copied" state
// inline. No toast/notification dependency; the consumer can wrap or
// restyle via className.
export function CopyButton({
  text,
  label = "Copy",
  copiedLabel = "Copied",
  className,
}: {
  text: string;
  label?: string;
  copiedLabel?: string;
  className?: string;
}) {
  const [copied, setCopied] = useState(false);
  return (
    <Button
      type="button"
      variant="ghost"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        } catch {
          /* clipboard blocked — no-op */
        }
      }}
      className={cn(
        "inline-flex h-auto items-center gap-2 border-2 border-current rounded-md px-3 py-1.5 text-[11px] uppercase tracking-wider font-medium transition-colors hover:bg-current hover:text-background",
        className,
      )}
    >
      {copied ? copiedLabel : label}
    </Button>
  );
}

// frontend/slices/library-svelte/components/CopyButton.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  let {
    text,
    label = "Copy",
    copiedLabel = "Copied",
    class: className = "",
  }: {
    text: string;
    label?: string;
    copiedLabel?: string;
    class?: string;
  } = $props();

  let copied = $state(false);
  let resetTimer: ReturnType<typeof setTimeout> | undefined;

  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      copied = true;
      if (resetTimer) clearTimeout(resetTimer);
      resetTimer = setTimeout(() => {
        copied = false;
        resetTimer = undefined;
      }, 1500);
    } catch {
      // Clipboard can be unavailable in sandboxed or insecure contexts.
    }
  }

  onDestroy(() => {
    if (resetTimer) clearTimeout(resetTimer);
  });
</script>

<button
  type="button"
  onclick={copy}
  class={`inline-flex items-center gap-2 rounded-md border-2 border-current px-3 py-1.5 text-[11px] font-medium uppercase tracking-wider transition-colors hover:bg-current hover:text-background ${className}`}
>
  {copied ? copiedLabel : label}
</button>
