// frontend/slices/library/components/UpvotePanel.tsx
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { UpvoteHandler } from "../lib/types";
import { optimisticVote, settleVote } from "../lib/core";

// Decoupled upvote control. The vote backend is consumer-owned: pass an
// `onUpvote` handler that persists the toggle and resolves the new
// state. Without a handler the control renders read-only (count only),
// so the slice carries no `/api/*` route or voter-token dependency.
export function UpvotePanel({
  itemId,
  initial,
  onUpvote,
  label = "Upvote",
}: {
  itemId: string;
  initial: number;
  onUpvote?: UpvoteHandler;
  label?: string;
}) {
  const [count, setCount] = useState(initial);
  const [voted, setVoted] = useState(false);
  const [busy, setBusy] = useState(false);

  const readOnly = !onUpvote;

  const toggle = async () => {
    if (busy || !onUpvote) return;
    setBusy(true);
    const prev = voted;
    const optimistic = optimisticVote(count, prev);
    setVoted(optimistic.voted);
    setCount(optimistic.count);
    try {
      const { voted: next } = await onUpvote(itemId);
      const settled = settleVote(count, prev, next);
      setVoted(settled.voted);
      setCount(settled.count);
    } catch {
      setVoted(prev);
      setCount((c) => (prev ? c + 1 : Math.max(0, c - 1)));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Button
      type="button"
      variant="ghost"
      onClick={toggle}
      disabled={busy || readOnly}
      aria-pressed={voted}
      className={cn(
        "inline-flex h-auto items-center gap-2 border-2 rounded-md px-3 py-1.5 text-[11px] uppercase tracking-wider font-medium transition-colors hover:bg-transparent",
        voted
          ? "border-current bg-foreground text-background hover:bg-foreground hover:text-background"
          : "border-current/40 hover:border-current",
        readOnly && "cursor-default",
      )}
    >
      <span aria-hidden="true">▲</span>
      <span className="tabular-nums">{count}</span>
      {!readOnly ? <span>{label}</span> : null}
    </Button>
  );
}

// frontend/slices/library-svelte/components/UpvotePanel.svelte
<script lang="ts">
  import { optimisticVote, settleVote } from "@/features/library/lib/core";
  import type { UpvoteHandler } from "@/features/library/lib/types";

  let {
    itemId,
    initial,
    onUpvote,
    label = "Upvote",
  }: {
    itemId: string;
    initial: number;
    onUpvote?: UpvoteHandler;
    label?: string;
  } = $props();

  class VoteState {
    count = $state(0);
    voted = $state(false);
    busy = $state(false);

    constructor(getInitial: () => number) {
      this.count = getInitial();
    }
  }

  const vote = new VoteState(() => initial);
  let readOnly = $derived(!onUpvote);

  async function toggle() {
    if (vote.busy || !onUpvote) return;
    vote.busy = true;
    const previous = { count: vote.count, voted: vote.voted };
    const optimistic = optimisticVote(vote.count, vote.voted);
    vote.count = optimistic.count;
    vote.voted = optimistic.voted;
    try {
      const result = await onUpvote(itemId);
      const settled = settleVote(previous.count, previous.voted, result.voted);
      vote.count = settled.count;
      vote.voted = settled.voted;
    } catch {
      vote.count = previous.count;
      vote.voted = previous.voted;
    } finally {
      vote.busy = false;
    }
  }
</script>

<button
  type="button"
  onclick={toggle}
  disabled={vote.busy || readOnly}
  aria-pressed={vote.voted}
  class={`inline-flex items-center gap-2 rounded-md border-2 px-3 py-1.5 text-[11px] font-medium uppercase tracking-wider transition-colors ${vote.voted ? "border-current bg-foreground text-background" : "border-current/40 hover:border-current"} ${readOnly ? "cursor-default" : ""}`}
>
  <span aria-hidden="true">▲</span>
  <span class="tabular-nums">{vote.count}</span>
  {#if !readOnly}<span>{label}</span>{/if}
</button>
