// frontend/slices/selection-svelte/components/SelectableBlock.svelte
<script lang="ts">
  import { getContext, type Snippet } from "svelte";
  import { SELECTION_CONTEXT, type SelectionContext } from "../lib/context";

  type Props = {
    id: string;
    orderedIds: string[];
    children: Snippet;
    class?: string;
    style?: string;
    edges?: boolean;
  };

  let {
    id,
    orderedIds,
    children,
    class: className = "",
    style = "",
    edges = true,
  }: Props = $props();
  const selection = getContext<SelectionContext | undefined>(SELECTION_CONTEXT);
  let revision = $state(0);
  let selected = $derived.by(() => {
    revision;
    return selection?.isSelected(id) ?? false;
  });

  $effect(() => selection?.subscribe((next) => (revision = next)));

  function select(event: MouseEvent) {
    event.preventDefault();
    if (!selection) return;
    if (event.shiftKey) selection.selectRange(id, orderedIds);
    else if (event.metaKey || event.ctrlKey) selection.toggle(id);
    else selection.selectOnly(id);
  }
</script>

{#if selection}
  <div
    data-selectable-id={id}
    data-block-selected={selected || undefined}
    class={`relative rounded-sm transition-colors ${selected ? "bg-primary/10 ring-2 ring-primary/50" : ""} ${className}`}
    {style}
  >
    {#if edges}
      <div data-selectable-edge data-no-marquee aria-hidden="true" class="absolute inset-x-0 top-0 z-10 h-1.5 cursor-pointer" onmousedown={select}></div>
    {/if}
    {@render children()}
    {#if edges}
      <div data-selectable-edge data-no-marquee aria-hidden="true" class="absolute inset-x-0 bottom-0 z-10 h-1.5 cursor-pointer" onmousedown={select}></div>
    {/if}
  </div>
{:else}
  {@render children()}
{/if}

// frontend/slices/selection/components/SelectableBlock.tsx
"use client";

/** SelectableBlock — wrap each list item to opt it into selection (needs a
 *  <SelectionProvider> ancestor; without one it renders children untouched).
 *  Tags the item with data-selectable-id so the marquee can hit-test it, shows
 *  the selected ring, and its thin edge strips click-select (Shift = range,
 *  Cmd/Ctrl = toggle). */

import type { MouseEvent, ReactNode } from "react";
import { cn } from "@/lib/utils";
import { useSelection } from "./SelectionProvider";

export interface SelectableBlockProps {
  id: string;
  orderedIds: string[];
  children: ReactNode;
  className?: string;
}

export function SelectableBlock({ id, orderedIds, children, className }: SelectableBlockProps) {
  const sel = useSelection();
  if (!sel) return <>{children}</>;

  const selected = sel.isSelected(id);
  const onEdge = (e: MouseEvent) => {
    e.preventDefault();
    if (e.shiftKey) sel.selectRange(id, orderedIds);
    else if (e.metaKey || e.ctrlKey) sel.toggle(id);
    else sel.selectOnly(id);
  };

  return (
    <div
      data-selectable-id={id}
      data-block-selected={selected || undefined}
      className={cn("relative rounded-sm transition-colors", selected && "bg-primary/10 ring-2 ring-primary/50", className)}
    >
      <div data-selectable-edge data-no-marquee onMouseDown={onEdge} aria-hidden className="absolute inset-x-0 top-0 z-10 h-1.5 cursor-pointer" />
      {children}
      <div data-selectable-edge data-no-marquee onMouseDown={onEdge} aria-hidden className="absolute inset-x-0 bottom-0 z-10 h-1.5 cursor-pointer" />
    </div>
  );
}
