// frontend/slices/admin-svelte/variants/console/components/sections/LeadsInbox.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import {
    MOCK_LEADS,
    type Lead,
    type LeadStatus,
  } from "@/features/admin/variants/console/lib/mock";

  const STATUSES: LeadStatus[] = ["new", "open", "won", "lost"];

  type Props = {
    leads?: Lead[];
    onUpdateStatus?: (id: string, status: LeadStatus) => void;
    onAddNote?: (id: string, note: string) => void;
  };

  let {
    leads = MOCK_LEADS,
    onUpdateStatus,
    onAddNote,
  }: Props = $props();

  let list = $state<Lead[]>(untrack(() => leads.map((lead) => ({ ...lead, notes: [...lead.notes] }))));
  let activeId = $state<string | null>(null);
  let note = $state("");
  let active = $derived(list.find((lead) => lead.id === activeId) ?? null);

  function setStatus(id: string, status: LeadStatus) {
    list = list.map((lead) => (lead.id === id ? { ...lead, status } : lead));
    onUpdateStatus?.(id, status);
  }

  function addNote() {
    const text = note.trim();
    if (!active || !text) return;
    list = list.map((lead) =>
      lead.id === active.id ? { ...lead, notes: [...lead.notes, text] } : lead,
    );
    onAddNote?.(active.id, text);
    note = "";
  }
</script>

<div class="space-y-3">
  <div class="overflow-x-auto rounded-md border">
    <table class="w-full text-sm">
      <thead class="border-b bg-muted/40 text-left text-xs text-muted-foreground">
        <tr><th class="p-3">Name</th><th>Source</th><th>Status</th><th class="w-16"></th></tr>
      </thead>
      <tbody>
        {#each list as lead (lead.id)}
          <tr class="border-b last:border-0">
            <td class="p-3"><div class="font-medium">{lead.name}</div><div class="text-xs text-muted-foreground">{lead.email}</div></td>
            <td><span class="rounded-full border px-2 py-0.5 text-xs">{lead.source}</span></td>
            <td>
              <select
                class="h-8 rounded-md border bg-background px-2 text-sm"
                value={lead.status}
                onchange={(event) => setStatus(lead.id, event.currentTarget.value as LeadStatus)}
                aria-label={`Status for ${lead.name}`}
              >
                {#each STATUSES as status}
                  <option value={status}>{status}</option>
                {/each}
              </select>
            </td>
            <td><button type="button" class="rounded-md px-2 py-1 text-xs hover:bg-accent" onclick={() => (activeId = lead.id)}>Open</button></td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  {#if active}
    <aside class="rounded-xl border bg-card p-4 shadow-sm" aria-label="Lead details">
      <div class="flex items-start justify-between gap-3">
        <div><h3 class="font-semibold">{active.name}</h3><p class="text-xs text-muted-foreground">{active.email}</p></div>
        <button type="button" class="rounded-md px-2 py-1 text-xs hover:bg-accent" onclick={() => (activeId = null)}>Close</button>
      </div>
      <p class="mt-4 rounded bg-muted p-3 text-sm">{active.message}</p>
      <div class="mt-4 space-y-2">
        <p class="text-xs font-medium text-muted-foreground">Notes</p>
        {#each active.notes as existing, index (`${active.id}-${index}`)}
          <p class="rounded border px-2 py-1 text-sm">{existing}</p>
        {:else}
          <p class="text-sm text-muted-foreground">No notes yet.</p>
        {/each}
      </div>
      <div class="mt-4 space-y-2">
        <label class="block"><span class="sr-only">Add lead note</span><textarea bind:value={note} class="min-h-20 w-full rounded-md border bg-background p-2 text-sm" placeholder="Add a note…"></textarea></label>
        <button type="button" class="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!note.trim()} onclick={addNote}>Add note</button>
      </div>
    </aside>
  {/if}
</div>

// frontend/slices/admin/variants/console/components/sections/LeadsInbox.tsx
"use client"

import * as React from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { MOCK_LEADS, type Lead, type LeadStatus } from "../../lib/mock"

const STATUSES: LeadStatus[] = ["new", "open", "won", "lost"]
const TONE: Record<LeadStatus, "default" | "secondary" | "outline" | "destructive"> = {
  new: "default",
  open: "secondary",
  won: "outline",
  lost: "destructive",
}

/**
 * Leads / CRM inbox — gap section. Status pipeline + notes drawer over injected
 * leads (default: mock). `onUpdateStatus` / `onAddNote` persist; omit for demo.
 */
export function LeadsInbox({
  leads = MOCK_LEADS,
  onUpdateStatus,
  onAddNote,
}: {
  leads?: Lead[]
  onUpdateStatus?: (id: string, status: LeadStatus) => void
  onAddNote?: (id: string, note: string) => void
}) {
  const [list, setList] = React.useState<Lead[]>(leads)
  const [active, setActive] = React.useState<Lead | null>(null)
  const [note, setNote] = React.useState("")

  const setStatus = (id: string, status: LeadStatus) => {
    setList((l) => l.map((x) => (x.id === id ? { ...x, status } : x)))
    onUpdateStatus?.(id, status)
  }

  const addNote = () => {
    if (!active || !note.trim()) return
    const text = note.trim()
    setList((l) => l.map((x) => (x.id === active.id ? { ...x, notes: [...x.notes, text] } : x)))
    onAddNote?.(active.id, text)
    setActive((a) => (a ? { ...a, notes: [...a.notes, text] } : a))
    setNote("")
  }

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Name</TableHead>
            <TableHead>Source</TableHead>
            <TableHead>Status</TableHead>
            <TableHead className="w-10" />
          </TableRow>
        </TableHeader>
        <TableBody>
          {list.map((lead) => (
            <TableRow key={lead.id}>
              <TableCell>
                <div className="font-medium">{lead.name}</div>
                <div className="text-xs text-muted-foreground">{lead.email}</div>
              </TableCell>
              <TableCell>
                <Badge variant="outline">{lead.source}</Badge>
              </TableCell>
              <TableCell>
                <Select value={lead.status} onValueChange={(v) => setStatus(lead.id, v as LeadStatus)}>
                  <SelectTrigger className="h-8 w-28">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {STATUSES.map((s) => (
                      <SelectItem key={s} value={s}>
                        <Badge variant={TONE[s]} className="capitalize">
                          {s}
                        </Badge>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell>
                <Button variant="ghost" size="sm" onClick={() => setActive(lead)}>
                  Open
                </Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <Sheet open={!!active} onOpenChange={(o) => !o && setActive(null)}>
        <SheetContent>
          <SheetHeader>
            <SheetTitle>{active?.name}</SheetTitle>
            <SheetDescription>{active?.email}</SheetDescription>
          </SheetHeader>
          <div className="space-y-4 p-4">
            <p className="rounded bg-muted p-3 text-sm">{active?.message}</p>
            <div className="space-y-2">
              <p className="text-xs font-medium text-muted-foreground">Notes</p>
              {active?.notes.length ? (
                active.notes.map((n, i) => (
                  <p key={i} className="rounded border px-2 py-1 text-sm">
                    {n}
                  </p>
                ))
              ) : (
                <p className="text-sm text-muted-foreground">No notes yet.</p>
              )}
            </div>
            <div className="space-y-2">
              <Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add a note…" />
              <Button size="sm" onClick={addNote} disabled={!note.trim()}>
                Add note
              </Button>
            </div>
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
