// frontend/slices/settings-svelte/variants/account/components/sections/DangerZone.svelte
<script lang="ts">
  let {
    onDeleteAccount = undefined,
  } = $props<{ onDeleteAccount?: () => void | Promise<void> }>();

  let confirming = $state(false);
  let busy = $state(false);

  async function confirmDelete() {
    if (!onDeleteAccount) return;
    busy = true;
    try {
      await onDeleteAccount();
      confirming = false;
    } finally {
      busy = false;
    }
  }
</script>

<section class="rounded-xl border border-destructive/40 bg-card text-card-foreground shadow-sm">
  <header class="space-y-1.5 border-b border-destructive/20 px-5 py-4">
    <h2 class="font-semibold text-destructive">Danger zone</h2>
    <p class="text-sm text-muted-foreground">Irreversible actions. Proceed with caution.</p>
  </header>
  <div class="p-5">
    <div class="flex flex-col gap-3 rounded-lg border border-destructive/40 p-4 sm:flex-row sm:items-center sm:justify-between">
      <div class="space-y-0.5">
        <p class="text-sm font-medium">Delete account</p>
        <p class="text-sm text-muted-foreground">Permanently remove your account and all associated data.</p>
      </div>
      <button
        type="button"
        disabled={busy}
        onclick={() => (confirming = true)}
        class="rounded-md bg-destructive px-3 py-2 text-sm font-medium text-destructive-foreground hover:bg-destructive/90 disabled:opacity-50"
      >
        {busy ? "Deleting…" : "Delete account"}
      </button>
    </div>

    {#if confirming}
      <div class="mt-4 rounded-lg border bg-background p-4" role="alertdialog" aria-labelledby="delete-account-title" aria-describedby="delete-account-description">
        <h3 id="delete-account-title" class="font-semibold">Delete your account?</h3>
        <p id="delete-account-description" class="mt-1 text-sm text-muted-foreground">This action cannot be undone. All your data will be permanently erased.</p>
        <div class="mt-4 flex justify-end gap-2">
          <button type="button" disabled={busy} onclick={() => (confirming = false)} class="rounded-md border px-3 py-2 text-sm hover:bg-accent">Cancel</button>
          <button type="button" disabled={busy} onclick={confirmDelete} class="rounded-md bg-destructive px-3 py-2 text-sm font-medium text-destructive-foreground hover:bg-destructive/90 disabled:opacity-50">Confirm delete</button>
        </div>
      </div>
    {/if}
  </div>
</section>

// frontend/slices/settings/variants/account/components/sections/DangerZone.tsx
"use client";

import * as React from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export interface DangerZoneProps {
  /** Called after the user confirms in the AlertDialog. */
  onDeleteAccount?: () => void | Promise<void>;
}

export function DangerZone({ onDeleteAccount }: DangerZoneProps) {
  const [busy, setBusy] = React.useState(false);

  const confirm = async () => {
    if (!onDeleteAccount) return;
    setBusy(true);
    try {
      await onDeleteAccount();
    } finally {
      setBusy(false);
    }
  };

  return (
    <Card className="border-destructive/40">
      <CardHeader>
        <CardTitle className="text-destructive">Danger zone</CardTitle>
        <CardDescription>
          Irreversible actions. Proceed with caution.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col gap-3 rounded-lg border border-destructive/40 p-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="space-y-0.5">
            <p className="text-sm font-medium">Delete account</p>
            <p className="text-sm text-muted-foreground">
              Permanently remove your account and all associated data.
            </p>
          </div>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="destructive" disabled={busy}>
                {busy ? "Deleting…" : "Delete account"}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete your account?</AlertDialogTitle>
                <AlertDialogDescription>
                  This action cannot be undone. All your data will be permanently
                  erased.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction
                  onClick={confirm}
                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                >
                  Delete account
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </CardContent>
    </Card>
  );
}
