// frontend/slices/ai-workspace-svelte/variants/agents/components/RunTrace.svelte
<script lang="ts">
  import type { AgentRun, StepStatus } from "@/features/ai-workspace/variants/agents/types";
  let { selected }: { selected?: AgentRun } = $props();
  const icon = (status: StepStatus) => status === "done" ? "✓" : status === "error" ? "×" : status === "running" ? "●" : "○";
</script>

<section class="rounded-lg border bg-card">
  <header class="flex flex-wrap items-start justify-between gap-2 border-b p-4">
    <div><h2 class="font-medium">▶ {selected?.agentSlug ?? "—"}</h2><p class="mt-1 text-sm text-muted-foreground">{selected?.input ?? "Select a run to inspect its trace."}</p></div>
    {#if selected}<span class={`rounded-full px-2 py-0.5 text-xs capitalize ${selected.status === "success" ? "bg-emerald-500/15 text-emerald-600" : selected.status === "failed" ? "bg-red-500/15 text-red-600" : selected.status === "running" ? "bg-blue-500/15 text-blue-600" : "bg-muted text-muted-foreground"}`}>{selected.status}</span>{/if}
  </header>
  <div class="p-4">
    {#if selected?.steps.length}
      <ol class="max-h-[22rem] space-y-2 overflow-y-auto pr-2">{#each selected.steps as step (step.index)}<li class="flex items-start gap-3 rounded-md border p-3"><span aria-hidden="true">{icon(step.status)}</span><div class="min-w-0 flex-1"><div class="flex gap-2"><strong class="text-sm">{step.name}</strong><span class="text-xs text-muted-foreground">#{step.index}</span></div>{#if step.args}<pre class="mt-1 overflow-x-auto rounded bg-muted px-2 py-1 text-xs">{step.args}</pre>{/if}{#if step.result}<p class="mt-1 text-sm text-muted-foreground">{step.result}</p>{/if}</div></li>{/each}</ol>
    {:else}<div class="rounded-md border border-dashed p-8 text-center text-sm text-muted-foreground">◷ No steps yet — this run is queued.</div>{/if}
  </div>
</section>

// frontend/slices/ai-workspace/variants/agents/views/RunTrace.tsx
import { Play, Timer } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";

import type { AgentRun } from "../types";
import { RUN_STATUS_STYLE, StepIcon } from "./parts";

/** Step-by-step trace panel for the selected run. */
export function RunTrace({ selected }: { selected: AgentRun | undefined }) {
  return (
    <Card>
      <CardHeader>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <CardTitle className="flex items-center gap-2 text-base">
              <Play className="size-4" aria-hidden />
              {selected?.agentSlug ?? "—"}
            </CardTitle>
            <CardDescription className="mt-1">
              {selected?.input ?? "Select a run to inspect its trace."}
            </CardDescription>
          </div>
          {selected ? (
            <Badge
              variant="secondary"
              className={cn("capitalize", RUN_STATUS_STYLE[selected.status])}
            >
              {selected.status}
            </Badge>
          ) : null}
        </div>
      </CardHeader>
      <CardContent>
        {selected && selected.steps.length > 0 ? (
          <ScrollArea className="h-[22rem] pr-3">
            <ol className="space-y-2">
              {selected.steps.map((step) => (
                <li
                  key={step.index}
                  className="flex items-start gap-3 rounded-md border bg-card p-3"
                >
                  <StepIcon status={step.status} />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{step.name}</span>
                      <span className="text-xs text-muted-foreground">#{step.index}</span>
                    </div>
                    {step.args ? (
                      <pre className="mt-1 overflow-x-auto rounded bg-muted px-2 py-1 text-xs">
                        {step.args}
                      </pre>
                    ) : null}
                    {step.result ? (
                      <p className="mt-1 text-sm text-muted-foreground">{step.result}</p>
                    ) : null}
                  </div>
                </li>
              ))}
            </ol>
          </ScrollArea>
        ) : (
          <div className="flex flex-col items-center gap-2 rounded-md border border-dashed p-8 text-center">
            <Timer className="size-6 text-muted-foreground" aria-hidden />
            <p className="text-sm text-muted-foreground">
              No steps yet — this run is queued.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
