// frontend/slices/content-loops-svelte/components/ContentLoop.svelte
<script lang="ts">
  import { onDestroy, type Snippet } from "svelte";
  import { loopSourceRegistry } from "../../content-loops/lib/registry";
  import { loopVariantIndex } from "../../content-loops/lib/variants";
  import type { LoopEntitySource, LoopItem } from "../../content-loops/lib/types";
  import { createLoopPaginationStore } from "../lib/store";

  type Props = {
    source?: LoopEntitySource;
    sourceId?: string;
    filters?: Record<string, unknown>;
    orderBy?: string;
    direction?: "asc" | "desc";
    pagination?: "none" | "infinite";
    limit?: number;
    pageSize?: number;
    variants: Snippet<[LoopItem, number]>[];
    as?: keyof HTMLElementTagNameMap;
    class?: string;
    loadMoreLabel?: string;
    loadingContent?: Snippet;
    emptyContent?: Snippet;
  };

  let {
    source,
    sourceId,
    filters,
    orderBy,
    direction = "asc",
    pagination = "none",
    limit = 12,
    pageSize = 6,
    variants,
    as = "div",
    class: className,
    loadMoreLabel = "Load more",
    loadingContent,
    emptyContent,
  }: Props = $props();

  function resolveSource(): LoopEntitySource {
    const resolved = source ?? (sourceId ? loopSourceRegistry.getOrThrow(sourceId) : undefined);
    if (!resolved) {
      throw new Error("[content-loops] <ContentLoop> needs a `source` or a registered `sourceId`.");
    }
    return resolved;
  }

  function currentOptions() {
    return {
      source: resolveSource(),
      filters,
      orderBy,
      direction,
      pagination,
      limit,
      pageSize,
    };
  }

  const loop = createLoopPaginationStore(currentOptions());
  let state = $derived($loop);
  let initialized = false;

  $effect(() => {
    if (variants.length === 0) {
      throw new Error("[content-loops] <ContentLoop> needs at least one variant.");
    }
    const next = currentOptions();
    if (!initialized) {
      initialized = true;
      return;
    }
    void loop.update(next);
  });

  onDestroy(() => loop.destroy());
</script>

{#if state.error}
  <div role="alert" class="text-sm text-destructive">{state.error.message}</div>
{:else if state.loading && state.items.length === 0}
  {#if loadingContent}
    {@render loadingContent()}
  {:else}
    <div role="status" class="text-sm text-muted-foreground">Loading…</div>
  {/if}
{:else if state.items.length === 0}
  {#if emptyContent}
    {@render emptyContent()}
  {:else}
    <div class="text-sm text-muted-foreground">No items.</div>
  {/if}
{:else}
  <svelte:element this={as} class={className}>
    {#each state.items as item, index (item.id)}
      {@const Variant = variants[loopVariantIndex(index, variants.length)]}
      {@render Variant(item, index)}
    {/each}
  </svelte:element>

  {#if pagination === "infinite" && state.hasMore}
    <div class="mt-6 flex justify-center">
      <button
        type="button"
        class="inline-flex h-9 items-center justify-center rounded-md border bg-background px-4 text-sm font-medium shadow-xs hover:bg-accent disabled:pointer-events-none disabled:opacity-50"
        disabled={state.loading}
        onclick={() => void loop.loadMore()}
      >
        {state.loading ? "Loading…" : loadMoreLabel}
      </button>
    </div>
  {/if}
{/if}

// frontend/slices/content-loops/components/ContentLoop.tsx
"use client";
// <ContentLoop> — the repeater. Resolves items from a source (passed inline or
// by registered id), then renders one variant per item, round-robining items
// across variants (item i → variants[i % n]). This is Instatic's renderLoop
// round-robin minus the HTML-string emit + entryStack plumbing: variants are
// React components, bindings are props.

import { createElement, type ElementType, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { loopSourceRegistry } from "../lib/registry";
import type { LoopEntitySource, LoopItem } from "../lib/types";
import { loopVariantIndex } from "../lib/variants";
import { useLoopPagination } from "../hooks/use-loop-pagination";

export interface LoopVariantProps {
  item: LoopItem;
  index: number;
}

/** A variant is a component rendered once per matched item. */
export type LoopVariant = (props: LoopVariantProps) => ReactNode;

export interface ContentLoopProps {
  /** Pass a source directly… */
  source?: LoopEntitySource;
  /** …or look one up in the registry by namespaced id. */
  sourceId?: string;
  filters?: Record<string, unknown>;
  orderBy?: string;
  direction?: "asc" | "desc";
  /** 'none' renders up to `limit`; 'infinite' adds a Load more button. */
  pagination?: "none" | "infinite";
  limit?: number;
  pageSize?: number;
  /** One component per variant; items round-robin across them. */
  variants: LoopVariant[];
  /** Wrapper element + class. Default <div>. Use it for the grid/list layout. */
  as?: ElementType;
  className?: string;
  loadMoreLabel?: string;
  /** Shown while the first page loads. */
  loading?: ReactNode;
  /** Shown when the source returns nothing. */
  empty?: ReactNode;
}

export function ContentLoop({
  source,
  sourceId,
  filters,
  orderBy,
  direction = "asc",
  pagination = "none",
  limit = 12,
  pageSize = 6,
  variants,
  as = "div",
  className,
  loadMoreLabel = "Load more",
  loading,
  empty,
}: ContentLoopProps) {
  if (variants.length === 0) {
    throw new Error("[content-loops] <ContentLoop> needs at least one variant.");
  }
  const resolved = source ?? (sourceId ? loopSourceRegistry.getOrThrow(sourceId) : null);
  if (!resolved) {
    throw new Error("[content-loops] <ContentLoop> needs a `source` or a registered `sourceId`.");
  }

  const { items, hasMore, loading: isLoading, error, loadMore } = useLoopPagination({
    source: resolved,
    filters,
    orderBy,
    direction,
    pagination,
    limit,
    pageSize,
  });

  if (error) {
    return (
      <div role="alert" className="text-sm text-destructive">
        {error.message}
      </div>
    );
  }

  if (isLoading && items.length === 0) {
    return (
      <>{loading ?? <div role="status" className="text-sm text-muted-foreground">Loading…</div>}</>
    );
  }

  if (items.length === 0) {
    return <>{empty ?? <div className="text-sm text-muted-foreground">No items.</div>}</>;
  }

  const children = items.map((item, index) => {
    const Variant = variants[loopVariantIndex(index, variants.length)];
    return <Variant key={item.id} item={item} index={index} />;
  });

  return (
    <>
      {createElement(as, { className }, children)}
      {pagination === "infinite" && hasMore && (
        <div className="mt-6 flex justify-center">
          <Button variant="outline" onClick={loadMore} disabled={isLoading}>
            {isLoading ? "Loading…" : loadMoreLabel}
          </Button>
        </div>
      )}
    </>
  );
}
