// frontend/slices/pages-cms-svelte/components/BlockEditor.svelte
<script lang="ts">
  import { BLOCK_KIND_LABEL, type PageBlock } from "../../pages-cms/types";
  import BlockSimpleFields from "./BlockSimpleFields.svelte";
  import BlockListFields from "./BlockListFields.svelte";
  import BlockRichFields from "./BlockRichFields.svelte";

  let { block, onChange, onRemove }: {
    block: PageBlock;
    onChange: (next: PageBlock) => void;
    onRemove?: () => void;
  } = $props();
</script>

<section class="rounded-lg border bg-card">
  <header class="flex items-center justify-between border-b p-4">
    <h3 class="text-sm font-semibold">{BLOCK_KIND_LABEL[block.kind]}</h3>
    {#if onRemove}<button class="text-xs text-muted-foreground" type="button" onclick={onRemove}>Remove block</button>{/if}
  </header>
  <div class="p-4">
    {#if ["hero", "text", "cta", "testimonial", "video"].includes(block.kind)}
      <BlockSimpleFields {block} {onChange} />
    {:else if ["feature-list", "faq", "stats", "logo-cloud"].includes(block.kind)}
      <BlockListFields {block} {onChange} />
    {:else}
      <BlockRichFields {block} {onChange} />
    {/if}
  </div>
</section>

// frontend/slices/pages-cms/components/block-editor.tsx
"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BLOCK_KIND_LABEL, type PageBlock } from "../types";
import { CtaForm, HeroForm, TestimonialForm, TextForm, VideoForm } from "./block-forms-simple";
import { FaqForm, FeatureListForm, LogoCloudForm, StatsForm } from "./block-forms-list";
import { ImageGalleryForm, PricingTableForm } from "./block-forms-rich";

export type BlockEditorProps = {
  block: PageBlock;
  onChange: (next: PageBlock) => void;
  onRemove?: () => void;
};

export function BlockEditor({ block, onChange, onRemove }: BlockEditorProps) {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3">
        <CardTitle className="text-sm font-semibold">{BLOCK_KIND_LABEL[block.kind]}</CardTitle>
        {onRemove && (
          <Button type="button" variant="ghost" size="sm" onClick={onRemove}>
            Remove block
          </Button>
        )}
      </CardHeader>
      <CardContent>
        <BlockBody block={block} onChange={onChange} />
      </CardContent>
    </Card>
  );
}

function BlockBody({ block, onChange }: { block: PageBlock; onChange: (next: PageBlock) => void }) {
  switch (block.kind) {
    case "hero":
      return <HeroForm block={block} onChange={onChange} />;
    case "text":
      return <TextForm block={block} onChange={onChange} />;
    case "cta":
      return <CtaForm block={block} onChange={onChange} />;
    case "testimonial":
      return <TestimonialForm block={block} onChange={onChange} />;
    case "video":
      return <VideoForm block={block} onChange={onChange} />;
    case "feature-list":
      return <FeatureListForm block={block} onChange={onChange} />;
    case "faq":
      return <FaqForm block={block} onChange={onChange} />;
    case "stats":
      return <StatsForm block={block} onChange={onChange} />;
    case "logo-cloud":
      return <LogoCloudForm block={block} onChange={onChange} />;
    case "image-gallery":
      return <ImageGalleryForm block={block} onChange={onChange} />;
    case "pricing-table":
      return <PricingTableForm block={block} onChange={onChange} />;
  }
}
