// frontend/slices/pages-cms-svelte/components/PagesView.svelte
<script lang="ts">
  import { blankPage, duplicatePage } from "../../pages-cms/lib/duplicate";
  import {
    orderPagesForAdmin,
    pageHref,
    type CreateDialogMode,
  } from "../../pages-cms/lib/core";
  import type { PageEntry } from "../../pages-cms/types";
  import { getPagesStore } from "../lib/context";
  import PageCreateDialog from "./PageCreateDialog.svelte";

  let { publicBase, adminBase }: { publicBase: string; adminBase: string } = $props();
  const store = getPagesStore();
  let dialog = $state<CreateDialogMode>(null);
  const ordered = $derived(orderPagesForAdmin(store.pages));
  const systemCount = $derived(store.pages.filter((page) => page.systemPage).length);

  function removePage(page: PageEntry) {
    if (page.systemPage) return;
    if (typeof window === "undefined" || window.confirm(`Delete page “${page.title}”?`)) {
      store.remove(page.id);
    }
  }

  function confirmCreate(values: { slug: string; title: string }) {
    const next = dialog?.mode === "dup"
      ? duplicatePage(dialog.source, values)
      : { ...blankPage(values.slug), title: values.title };
    store.create(next);
    dialog = null;
    if (typeof window !== "undefined") window.location.href = `${adminBase}/pages/${next.id}`;
  }
</script>

<div class="space-y-4">
  <div class="flex items-center justify-between gap-2">
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">Pages</h1>
      <p class="text-xs text-muted-foreground">
        {store.pages.length} total · {systemCount} system · {store.pages.length - systemCount} custom
      </p>
    </div>
    <button class="rounded-md bg-foreground px-3 py-2 text-xs font-medium text-background" type="button" onclick={() => (dialog = { mode: "new" })}>
      + New page
    </button>
  </div>

  <div class="overflow-x-auto rounded-lg border bg-card">
    <table class="w-full text-left text-xs">
      <thead class="border-b text-muted-foreground">
        <tr><th class="p-3">Slug</th><th class="p-3">Title</th><th class="p-3">Status</th><th class="p-3">Type</th><th class="p-3 text-right">Actions</th></tr>
      </thead>
      <tbody>
        {#each ordered as page (page.id)}
          <tr class="border-b last:border-b-0">
            <td class="p-3 font-mono">{page.slug || "/"}</td>
            <td class="p-3"><div class="font-medium">{page.title}</div>{#if page.description}<div class="max-w-sm truncate text-muted-foreground">{page.description}</div>{/if}</td>
            <td class="p-3"><span class="rounded border px-2 py-1 text-[10px]">{page.status}</span></td>
            <td class="p-3"><span class="rounded border px-2 py-1 text-[10px]">{page.systemPage ? "system" : "custom"}</span></td>
            <td class="p-3"><div class="flex justify-end gap-1">
              <a class="rounded px-2 py-1 hover:bg-muted" href={pageHref(publicBase, page.slug)} target="_blank" rel="noreferrer">View</a>
              {#if page.systemPage}
                <button class="rounded px-2 py-1 opacity-40" type="button" disabled>Edit</button>
              {:else}
                <a class="rounded px-2 py-1 hover:bg-muted" href={`${adminBase}/pages/${page.id}`}>Edit</a>
              {/if}
              <button class="rounded px-2 py-1 hover:bg-muted" type="button" onclick={() => (dialog = { mode: "dup", source: page })}>Duplicate</button>
              <button class="rounded px-2 py-1 text-destructive hover:bg-muted disabled:opacity-40" type="button" disabled={page.systemPage} onclick={() => removePage(page)}>Delete</button>
            </div></td>
          </tr>
        {:else}
          <tr><td colspan="5" class="p-8 text-center text-muted-foreground">No pages yet. Create the first page.</td></tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

<PageCreateDialog {dialog} onClose={() => (dialog = null)} onConfirm={confirmCreate} />

// frontend/slices/pages-cms/components/PagesView.tsx
"use client";

import * as React from "react";
import { Copy, ExternalLink, Pencil, Plus, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { usePagesStore } from "./pages-context";
import { blankPage, duplicatePage } from "../lib/duplicate";
import { orderPagesForAdmin, pageHref } from "../lib/core";
import { PageCreateDialog, type CreateDialogMode } from "./page-create-dialog";
import type { PageEntry } from "../types";

/**
 * Admin Pages list — system + custom pages with row actions
 * (View / Edit / Duplicate / Delete). New/Duplicate route through a
 * shadcn Dialog for slug + title entry. Delete is confirm-in-row.
 */
export function PagesView({
  publicBase,
  adminBase,
}: {
  publicBase: string;
  adminBase: string;
}) {
  const { pages, create } = usePagesStore();
  const [dialog, setDialog] = React.useState<CreateDialogMode>(null);

  const ordered = React.useMemo(() => orderPagesForAdmin(pages), [pages]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-2">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Pages</h1>
          <p className="text-xs text-muted-foreground">
            {pages.length} total · {pages.filter((p) => p.systemPage).length} system ·{" "}
            {pages.filter((p) => !p.systemPage).length} custom
          </p>
        </div>
        <Button size="sm" className="gap-1.5" onClick={() => setDialog({ mode: "new" })}>
          <Plus className="size-3.5" /> New page
        </Button>
      </div>

      <div className="overflow-x-auto rounded-lg border bg-card">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[22%]">Slug</TableHead>
              <TableHead>Title</TableHead>
              <TableHead className="w-[10%]">Status</TableHead>
              <TableHead className="w-[10%]">Type</TableHead>
              <TableHead className="w-[16%] text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {ordered.map((p) => (
              <PageRow
                key={p.id}
                page={p}
                publicBase={publicBase}
                adminBase={adminBase}
                onDuplicate={(src) => setDialog({ mode: "dup", source: src })}
              />
            ))}
            {ordered.length === 0 && (
              <TableRow>
                <TableCell colSpan={5} className="py-8 text-center text-xs text-muted-foreground">
                  No pages yet. Click <span className="font-medium">New page</span>.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>

      <PageCreateDialog
        dialog={dialog}
        onClose={() => setDialog(null)}
        onConfirm={({ slug, title }) => {
          const next =
            dialog?.mode === "dup"
              ? duplicatePage(dialog.source, { slug, title })
              : { ...blankPage(slug), title };
          create(next);
          setDialog(null);
          if (typeof window !== "undefined") {
            window.location.href = `${adminBase}/pages/${next.id}`;
          }
        }}
      />
    </div>
  );
}

function PageRow({
  page,
  publicBase,
  adminBase,
  onDuplicate,
}: {
  page: PageEntry;
  publicBase: string;
  adminBase: string;
  onDuplicate: (src: PageEntry) => void;
}) {
  const { remove } = usePagesStore();
  return (
    <TableRow>
      <TableCell className="font-mono text-xs">{page.slug || "/"}</TableCell>
      <TableCell className="text-xs">
        <div className="line-clamp-1 font-medium">{page.title}</div>
        {page.description && (
          <div className="line-clamp-1 text-muted-foreground">{page.description}</div>
        )}
      </TableCell>
      <TableCell>
        <Badge variant={page.status === "published" ? "default" : "outline"} className="text-[10px]">
          {page.status}
        </Badge>
      </TableCell>
      <TableCell>
        <Badge variant="outline" className="text-[10px]">
          {page.systemPage ? "system" : "custom"}
        </Badge>
      </TableCell>
      <TableCell>
        <div className="flex items-center justify-end gap-1">
          <Button asChild size="icon" variant="ghost" className="size-7" title="View public">
            <a href={pageHref(publicBase, page.slug)} target="_blank" rel="noreferrer">
              <ExternalLink className="size-3.5" />
            </a>
          </Button>
          <Button
            asChild
            size="icon"
            variant="ghost"
            className="size-7"
            title={page.systemPage ? "System pages are read-only" : "Edit"}
            disabled={page.systemPage}
          >
            <a href={`${adminBase}/pages/${page.id}`}>
              <Pencil className="size-3.5" />
            </a>
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="size-7"
            title="Duplicate"
            onClick={() => onDuplicate(page)}
          >
            <Copy className="size-3.5" />
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="size-7 text-destructive hover:text-destructive"
            title={page.systemPage ? "System pages can't be deleted" : "Delete"}
            disabled={page.systemPage}
            onClick={() => {
              if (confirm(`Delete page "${page.title}"?`)) remove(page.id);
            }}
          >
            <Trash2 className="size-3.5" />
          </Button>
        </div>
      </TableCell>
    </TableRow>
  );
}
