// frontend/slices/pages-cms-svelte/components/PageEditorView.svelte
<script lang="ts">
  import {
    editablePageSnapshot,
    moveBlock,
    pageHref,
    removeBlock,
    replaceBlock,
  } from "../../pages-cms/lib/core";
  import { emptyBlock, type PageBlock, type PageBlockKind, type PageEntry } from "../../pages-cms/types";
  import { getPagesStore } from "../lib/context";
  import PageEditorBlocks from "./PageEditorBlocks.svelte";

  let { id, publicBase, adminBase }: { id: string; publicBase: string; adminBase: string } = $props();
  const store = getPagesStore();
  const page = $derived(store.pages.find((entry) => entry.id === id) ?? null);
  let draft = $state<PageEntry | null>(null);
  let loadedId = $state<string | null>(null);
  let addKind = $state<PageBlockKind>("hero");

  $effect(() => {
    if (!page) {
      draft = null;
      loadedId = null;
      return;
    }
    if (loadedId !== page.id) {
      draft = structuredClone(page);
      loadedId = page.id;
    }
  });

  const dirty = $derived(Boolean(draft && page && editablePageSnapshot(draft) !== editablePageSnapshot(page)));
  const patchDraft = (patch: Partial<PageEntry>) => {
    if (draft) draft = { ...draft, ...patch };
  };
  const patchBlock = (index: number, next: PageBlock) => {
    if (draft) draft = { ...draft, blocks: replaceBlock(draft.blocks, index, next) };
  };
  const deleteBlock = (index: number) => {
    if (draft) draft = { ...draft, blocks: removeBlock(draft.blocks, index) };
  };
  const addBlock = () => {
    if (draft) draft = { ...draft, blocks: [...draft.blocks, emptyBlock(addKind)] };
  };
  const moveDraftBlock = (from: number, to: number) => {
    if (draft) draft = { ...draft, blocks: moveBlock(draft.blocks, from, to) };
  };
  function save() {
    if (!draft) return;
    store.update(draft.id, {
      slug: draft.slug,
      title: draft.title,
      description: draft.description,
      status: draft.status,
      blocks: draft.blocks,
    });
  }
</script>

{#if !page}
  <div class="space-y-3"><a class="text-xs text-muted-foreground" href={`${adminBase}/pages`}>← Pages</a><p class="text-sm text-muted-foreground">Page not found.</p></div>
{:else if page.systemPage}
  <div class="space-y-3"><a class="text-xs text-muted-foreground" href={`${adminBase}/pages`}>← Pages</a><div class="rounded-lg border border-amber-500/40 bg-amber-500/5 p-4 text-sm"><p class="font-medium">System page — read-only.</p><p class="mt-1 text-xs text-muted-foreground">Duplicate it from the Pages list to edit a custom copy.</p></div></div>
{:else if draft}
  <div class="space-y-4">
    <div class="flex items-center justify-between gap-2">
      <a class="text-xs text-muted-foreground hover:text-foreground" href={`${adminBase}/pages`}>← All pages</a>
      <div class="flex gap-2"><a class="rounded-md border px-3 py-2 text-xs" href={pageHref(publicBase, draft.slug)} target="_blank" rel="noreferrer">View public</a><button class="rounded-md bg-foreground px-3 py-2 text-xs font-medium text-background disabled:opacity-40" type="button" disabled={!dirty} onclick={save}>Save{dirty ? " (unsaved)" : ""}</button></div>
    </div>

    <section class="rounded-lg border bg-card p-5">
      <div class="grid gap-4 sm:grid-cols-2">
        <label class="space-y-1.5 text-xs"><span class="font-mono text-[10px] uppercase">Slug</span><input class="w-full rounded-md border bg-background px-3 py-2 font-mono text-xs" value={draft.slug} oninput={(e) => patchDraft({ slug: e.currentTarget.value })} /><span class="block text-[10px] text-muted-foreground">Renders at {pageHref(publicBase, draft.slug)}</span></label>
        <label class="space-y-1.5 text-xs"><span>Title</span><input class="w-full rounded-md border bg-background px-3 py-2" value={draft.title} oninput={(e) => patchDraft({ title: e.currentTarget.value })} /></label>
        <label class="space-y-1.5 text-xs sm:col-span-2"><span>Description</span><textarea class="min-h-20 w-full rounded-md border bg-background px-3 py-2" value={draft.description} oninput={(e) => patchDraft({ description: e.currentTarget.value })}></textarea></label>
        <label class="space-y-1.5 text-xs"><span>Status</span><select class="w-full rounded-md border bg-background px-3 py-2" value={draft.status} onchange={(e) => patchDraft({ status: e.currentTarget.value as PageEntry["status"] })}><option value="draft">draft</option><option value="published">published</option></select></label>
        <div class="flex items-end gap-2">{#if draft.isLanding}<span class="rounded border px-2 py-1 text-[10px]">landing</span>{/if}{#if draft.duplicatedFrom}<span class="rounded border px-2 py-1 text-[10px]">duplicated from {draft.duplicatedFrom.slice(0, 12)}…</span>{/if}</div>
      </div>
    </section>

    <PageEditorBlocks
      blocks={draft.blocks}
      {addKind}
      setAddKind={(kind) => (addKind = kind)}
      onAdd={addBlock}
      onPatch={patchBlock}
      onRemove={deleteBlock}
      onMoveUp={(index) => moveDraftBlock(index, index - 1)}
      onMoveDown={(index) => moveDraftBlock(index, index + 1)}
    />
  </div>
{/if}

// frontend/slices/pages-cms/components/PageEditorView.tsx
"use client";

import * as React from "react";
import { ArrowLeft, ExternalLink, Save } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { PageEditorBlocks } from "./PageEditorBlocks";
import { Field, PageNotFound, SystemPageNotice } from "./page-editor-helpers";
import { usePage, usePagesStore } from "./pages-context";
import { emptyBlock, type PageBlock, type PageBlockKind, type PageEntry } from "../types";
import { editablePageSnapshot, moveBlock, pageHref, removeBlock as removeBlockAt, replaceBlock as replaceBlockAt } from "../lib/core";

/**
 * Page editor — metadata form + the block editor. A page is composed of
 * an ordered list of `PageBlock`s (blocks-only; the section bridge was
 * severed when this engine became a standalone slice). System pages are
 * read-only.
 */
export function PageEditorView({
  id,
  publicBase,
  adminBase,
}: {
  id: string;
  publicBase: string;
  adminBase: string;
}) {
  const page = usePage(id);
  const { update } = usePagesStore();
  const [draft, setDraft] = React.useState<PageEntry | null>(page);
  const [addKind, setAddKind] = React.useState<PageBlockKind>("hero");

  React.useEffect(() => {
    setDraft(page);
  }, [page]);

  if (!page) return <PageNotFound adminBase={adminBase} />;
  if (page.systemPage) return <SystemPageNotice adminBase={adminBase} />;
  if (!draft) return null;

  const dirty = editablePageSnapshot(draft) !== editablePageSnapshot(page);

  function patchDraft(patch: Partial<PageEntry>) {
    setDraft((d) => (d ? { ...d, ...patch } : d));
  }

  const patchBlock = (idx: number, next: PageBlock) =>
    setDraft((d) => (d ? { ...d, blocks: replaceBlockAt(d.blocks, idx, next) } : d));
  const removeBlock = (idx: number) =>
    setDraft((d) => (d ? { ...d, blocks: removeBlockAt(d.blocks, idx) } : d));
  const addBlock = () =>
    setDraft((d) => (d ? { ...d, blocks: [...d.blocks, emptyBlock(addKind)] } : d));

  function saveMeta() {
    if (!draft) return;
    update(draft.id, {
      slug: draft.slug,
      title: draft.title,
      description: draft.description,
      status: draft.status,
      blocks: draft.blocks,
    });
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-2">
        <a
          href={`${adminBase}/pages`}
          className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-3" /> All pages
        </a>
        <div className="flex items-center gap-2">
          <Button asChild variant="outline" size="sm" className="gap-1.5">
            <a href={pageHref(publicBase, draft.slug)} target="_blank" rel="noreferrer">
              <ExternalLink className="size-3.5" /> View public
            </a>
          </Button>
          <Button size="sm" className="gap-1.5" disabled={!dirty} onClick={saveMeta}>
            <Save className="size-3.5" /> Save{dirty ? " (unsaved)" : ""}
          </Button>
        </div>
      </div>

      <div className="rounded-lg border bg-card p-5">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Slug" mono>
            <Input
              value={draft.slug}
              onChange={(e) => patchDraft({ slug: e.target.value })}
              className="font-mono text-xs"
            />
            <p className="mt-1 text-[10px] text-muted-foreground">
              Renders at <span className="font-mono">{publicBase}/{draft.slug}</span>
            </p>
          </Field>
          <Field label="Title">
            <Input value={draft.title} onChange={(e) => patchDraft({ title: e.target.value })} />
          </Field>
          <div className="sm:col-span-2">
            <Field label="Description">
              <Textarea
                value={draft.description}
                onChange={(e) => patchDraft({ description: e.target.value })}
                rows={2}
              />
            </Field>
          </div>
          <Field label="Status">
            <Select
              value={draft.status}
              onValueChange={(v: "draft" | "published") => patchDraft({ status: v })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="draft">draft</SelectItem>
                <SelectItem value="published">published</SelectItem>
              </SelectContent>
            </Select>
          </Field>
          <div className="flex items-end gap-2">
            {draft.isLanding && (
              <Badge variant="default" className="bg-emerald-500/20 text-emerald-300">
                landing
              </Badge>
            )}
            {draft.duplicatedFrom && (
              <Badge variant="outline" className="text-[10px]">
                duplicated from {draft.duplicatedFrom.slice(0, 12)}…
              </Badge>
            )}
          </div>
        </div>
      </div>

      <PageEditorBlocks
        blocks={draft.blocks}
        addKind={addKind}
        setAddKind={setAddKind}
        onAdd={addBlock}
        onPatch={patchBlock}
        onRemove={removeBlock}
        onMoveUp={(i) => patchDraft({ blocks: moveBlock(draft.blocks, i, i - 1) })}
        onMoveDown={(i) => patchDraft({ blocks: moveBlock(draft.blocks, i, i + 1) })}
      />
    </div>
  );
}
