// frontend/slices/doku-payment/components/checkout-page.tsx
"use client";

/**
 * Demo CheckoutPage for the DOKU slice. Two modes side-by-side:
 *   - "Quick checkout" → hosted page (DOKU UI)
 *   - "Pilih sendiri"  → Direct picker (custom UI, instructions inline)
 *
 * Wire in your consumer:
 *   // app/checkout/page.tsx
 *   export { default } from "@/features/doku-payment/components/checkout-page";
 *
 * The default amount + orderId are demo placeholders; swap for your cart.
 */

import * as React from "react";
import { DokuCheckout } from "./providers/doku";
import { DokuDirectForm } from "./DokuDirectForm";
import { DokuPaymentInstructions, type PaymentInstructions } from "./DokuPaymentInstructions";

interface CheckoutPageProps {
  amount?: number;
  orderId?: string;
  customer?: { name: string; email: string; phone?: string };
  callbackUrl?: string;
  allowedChannels?: string[];
}

export default function CheckoutPage({
  amount = 150_000,
  orderId,
  customer = { name: "Demo User", email: "demo@example.com" },
  callbackUrl,
  allowedChannels,
}: CheckoutPageProps) {
  const id = React.useMemo(() => orderId ?? `ord_${Date.now()}`, [orderId]);
  const [result, setResult] = React.useState<{
    channel: string;
    instructions: PaymentInstructions;
    expiresAt?: number;
  } | null>(null);

  return (
    <main className="mx-auto flex max-w-3xl flex-col gap-6 p-6">
      <header>
        <h1 className="text-2xl font-semibold">Pembayaran</h1>
        <p className="text-sm text-muted-foreground">
          Pilih cara cepat (hosted) atau pilih channel sendiri.
        </p>
      </header>

      {result ? (
        <DokuPaymentInstructions
          channel={result.channel}
          instructions={result.instructions}
          expiresAt={result.expiresAt}
        />
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <section className="flex flex-col gap-2">
            <h2 className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
              Quick checkout
            </h2>
            <DokuCheckout
              amount={amount}
              orderId={id}
              customer={customer}
              callbackUrl={callbackUrl}
              paymentMethods={allowedChannels}
            />
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
              Pilih channel sendiri
            </h2>
            <DokuDirectForm
              amount={amount}
              orderId={id}
              defaultCustomer={customer}
              allowedChannels={allowedChannels}
              onSuccess={(r) => setResult(r as never)}
            />
          </section>
        </div>
      )}
    </main>
  );
}

// frontend/slices/payment-svelte/variants/doku/components/CheckoutPage.svelte
<script lang="ts">
  import type {
    DokuCheckoutInput,
    DokuCheckoutResult,
    DokuDirectInput,
    DokuDirectResult,
    PaymentCustomer,
    PaymentInstructions,
  } from "@/features/payment/lib/contracts";
  import DokuDirectForm from "./DokuDirectForm.svelte";
  import DokuPaymentInstructions from "./DokuPaymentInstructions.svelte";
  import DokuCheckout from "./providers/DokuCheckout.svelte";

  export type CheckoutPageCopy = {
    heading: string;
    subheading: string;
    quickTitle: string;
    directTitle: string;
  };

  const DEFAULT_COPY: CheckoutPageCopy = {
    heading: "Checkout",
    subheading: "Pick the fast hosted flow, or choose your own channel.",
    quickTitle: "Quick checkout",
    directTitle: "Choose your own channel",
  };

  let {
    amount = 150_000,
    orderId = "ord_demo",
    customer = { name: "Demo User", email: "demo@example.com" },
    callbackUrl = undefined,
    allowedChannels = undefined,
    copy = {},
    onCheckout = undefined,
    onDirectSubmit = undefined,
  } = $props<{
    amount?: number;
    orderId?: string;
    customer?: PaymentCustomer;
    callbackUrl?: string;
    allowedChannels?: string[];
    copy?: Partial<CheckoutPageCopy>;
    onCheckout?: (input: DokuCheckoutInput) => Promise<DokuCheckoutResult>;
    onDirectSubmit?: (input: DokuDirectInput) => Promise<DokuDirectResult>;
  }>();

  let result = $state<{ channel: string; instructions: PaymentInstructions; expiresAt?: number } | null>(null);
  let strings = $derived({ ...DEFAULT_COPY, ...copy });
</script>

<main class="mx-auto flex max-w-3xl flex-col gap-6 p-6">
  <header>
    <h1 class="text-2xl font-semibold">{strings.heading}</h1>
    <p class="text-sm text-muted-foreground">{strings.subheading}</p>
  </header>

  {#if result}
    <DokuPaymentInstructions channel={result.channel} instructions={result.instructions} expiresAt={result.expiresAt} />
  {:else}
    <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
      <section class="flex flex-col gap-2">
        <h2 class="text-sm font-medium uppercase tracking-wide text-muted-foreground">{strings.quickTitle}</h2>
        <DokuCheckout {amount} {orderId} {customer} {callbackUrl} paymentMethods={allowedChannels} {onCheckout} />
      </section>
      <section class="flex flex-col gap-2">
        <h2 class="text-sm font-medium uppercase tracking-wide text-muted-foreground">{strings.directTitle}</h2>
        <DokuDirectForm
          {amount}
          {orderId}
          defaultCustomer={customer}
          {allowedChannels}
          onSubmit={onDirectSubmit}
          onSuccess={(next) => (result = next)}
        />
      </section>
    </div>
  {/if}
</main>
