// frontend/slices/markdown-svelte/components/MarkdownPage.svelte
<script lang="ts">
  import { newCommentId, openCount, type MdComment } from "../../markdown/lib/comments";
  import { normalizeMarkdownTabs, MARKDOWN_TAB_LABEL, type MarkdownTab } from "../../markdown/lib/page-core";
  import { parseMarkdown } from "../../markdown/lib/parse";
  import MarkdownReader from "./MarkdownReader.svelte";
  import WriteTab from "./WriteTab.svelte";
  import ReviewTab from "./ReviewTab.svelte";

  let {
    content,
    onContentChange,
    tabs = ["read"],
    comments,
    onAddComment,
    onResolveComment,
    commentAuthor,
    title,
    icon,
    className = "",
  }: {
    content: string;
    onContentChange?: (next: string) => void;
    tabs?: MarkdownTab[];
    comments?: MdComment[];
    onAddComment?: (comment: MdComment) => void;
    onResolveComment?: (id: string) => void;
    commentAuthor?: string;
    title?: string;
    icon?: string;
    className?: string;
  } = $props();

  const initialContent = () => content;
  const initialTab = () => normalizeMarkdownTabs(tabs)[0] ?? "read";
  let localContent = $state(initialContent());
  let localComments = $state<MdComment[]>([]);
  let activeTab = $state<MarkdownTab>(initialTab());
  let lastExternalContent = $state(initialContent());

  const tabList = $derived(normalizeMarkdownTabs(tabs));
  const markdown = $derived(onContentChange ? content : localContent);
  const allComments = $derived(comments ?? localComments);
  const nodes = $derived(parseMarkdown(markdown));
  const open = $derived(openCount(allComments));

  $effect(() => {
    if (content !== lastExternalContent) {
      lastExternalContent = content;
      if (!onContentChange) localContent = content;
    }
  });

  $effect(() => {
    if (!tabList.includes(activeTab)) activeTab = tabList[0] ?? "read";
  });

  function setMarkdown(next: string) {
    if (onContentChange) onContentChange(next);
    else localContent = next;
  }

  function addComment(anchor: number | null, text: string) {
    const comment: MdComment = {
      id: newCommentId(),
      anchor,
      text,
      author: commentAuthor,
      createdAt: Date.now(),
    };
    if (onAddComment) onAddComment(comment);
    else localComments = [...localComments, comment];
  }

  function resolveComment(id: string) {
    if (onResolveComment) onResolveComment(id);
    else localComments = localComments.map((comment) => comment.id === id ? { ...comment, resolved: true } : comment);
  }
</script>

<article class={`mx-auto w-full ${tabList.length === 1 ? "max-w-3xl" : "max-w-4xl"} px-4 py-6 ${className}`}>
  {#if title}
    <header class="mb-4 flex items-center gap-2">
      {#if icon}<span class="text-2xl leading-none">{icon}</span>{/if}
      <h1 class="text-3xl font-bold tracking-tight">{title}</h1>
    </header>
  {/if}

  {#if tabList.length > 1}
    <div class="mb-4 inline-flex rounded-md bg-muted p-1" role="tablist" aria-label="Markdown surfaces">
      {#each tabList as tab}
        <button
          type="button"
          role="tab"
          aria-selected={activeTab === tab}
          class={`rounded px-3 py-1.5 text-xs font-medium ${activeTab === tab ? "bg-background shadow-sm" : "text-muted-foreground"}`}
          onclick={() => (activeTab = tab)}
        >
          {MARKDOWN_TAB_LABEL[tab]}
          {#if tab === "review" && open > 0}<span class="ml-1 rounded-full bg-amber-500/20 px-1.5 text-[10px] font-semibold text-amber-700">{open}</span>{/if}
        </button>
      {/each}
    </div>
  {/if}

  {#if activeTab === "read"}
    <MarkdownReader nodes={nodes} maxWidth="none" className="px-0 py-0" />
  {:else if activeTab === "write"}
    <WriteTab value={markdown} onChange={setMarkdown} />
  {:else}
    <ReviewTab nodes={nodes} comments={allComments} onAdd={addComment} onResolve={resolveComment} />
  {/if}
</article>

// frontend/slices/markdown/components/MarkdownPage.tsx
"use client";

/** MarkdownPage — the markdown slice's page container with optional CRUD
 *  surfaces:
 *
 *    read   — rendered rich-text document (default, always available)
 *    write  — raw source editor + live preview
 *    review — rendered doc with block-anchored comments
 *
 *  `tabs` picks the surfaces; a single tab renders without tab chrome.
 *  Content and comments are controlled when callbacks are passed
 *  (`onContentChange`, `onAddComment`/`onResolveComment`) and fall back to
 *  internal state otherwise, so the page works standalone. Renders
 *  ```mermaid diagrams and ```chart charts in all surfaces. */

import * as React from "react";
import { cx } from "../lib/classnames";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { parseMarkdown } from "../lib/parse";
import { MARKDOWN_TAB_LABEL, normalizeMarkdownTabs, type MarkdownTab } from "../lib/page-core";
import { type MdComment, newCommentId, openCount } from "../lib/comments";
import { MarkdownReader } from "./MarkdownReader";
import { WriteTab } from "./WriteTab";
import { ReviewTab } from "./ReviewTab";

export type { MarkdownTab } from "../lib/page-core";

export interface MarkdownPageProps {
  /** Markdown source (controlled when `onContentChange` is set). */
  content: string;
  onContentChange?: (next: string) => void;
  /** Surfaces to expose. Default `["read"]`. */
  tabs?: MarkdownTab[];
  /** Review comments (controlled when `onAddComment` is set). */
  comments?: MdComment[];
  onAddComment?: (comment: MdComment) => void;
  onResolveComment?: (id: string) => void;
  /** Author stamped onto comments created in this session. */
  commentAuthor?: string;
  title?: string;
  icon?: React.ReactNode;
  className?: string;
}

export function MarkdownPage({
  content,
  onContentChange,
  tabs = ["read"],
  comments,
  onAddComment,
  onResolveComment,
  commentAuthor,
  title,
  icon,
  className,
}: MarkdownPageProps) {
  // Uncontrolled fallbacks — slice works standalone without any wiring.
  const [localContent, setLocalContent] = React.useState(content);
  const [localComments, setLocalComments] = React.useState<MdComment[]>([]);
  React.useEffect(() => { setLocalContent(content); }, [content]);

  const md = onContentChange ? content : localContent;
  const setMd = onContentChange ?? setLocalContent;
  const allComments = comments ?? localComments;

  const addComment = (anchor: number | null, text: string) => {
    const comment: MdComment = {
      id: newCommentId(), anchor, text, author: commentAuthor, createdAt: Date.now(),
    };
    if (onAddComment) onAddComment(comment);
    else setLocalComments((prev) => [...prev, comment]);
  };

  const resolveComment = (id: string) => {
    if (onResolveComment) onResolveComment(id);
    else setLocalComments((prev) => prev.map((c) => (c.id === id ? { ...c, resolved: true } : c)));
  };

  const nodes = React.useMemo(() => parseMarkdown(md), [md]);
  const open = openCount(allComments);
  const list = normalizeMarkdownTabs(tabs);

  const header = title && (
    <header className="mb-4 flex items-center gap-2">
      {icon && <span className="text-2xl leading-none">{icon}</span>}
      <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
    </header>
  );

  const surface = (tab: MarkdownTab) => {
    switch (tab) {
      case "read":
        return <MarkdownReader nodes={nodes} maxWidth="none" className="px-0 py-0" />;
      case "write":
        return <WriteTab value={md} onChange={setMd} />;
      case "review":
        return <ReviewTab nodes={nodes} comments={allComments} onAdd={addComment} onResolve={resolveComment} />;
    }
  };

  if (list.length === 1) {
    return (
      <article className={cx("mx-auto w-full max-w-3xl px-4 py-6", className)}>
        {header}
        {surface(list[0]!)}
      </article>
    );
  }

  return (
    <article className={cx("mx-auto w-full max-w-4xl px-4 py-6", className)}>
      {header}
      <Tabs defaultValue={list[0]}>
        <TabsList>
          {list.map((tab) => (
            <TabsTrigger key={tab} value={tab} className="text-xs">
              {MARKDOWN_TAB_LABEL[tab]}
              {tab === "review" && open > 0 && (
                <span className="ml-1 rounded-full bg-amber-500/20 px-1.5 text-[10px] font-semibold text-amber-700 dark:text-amber-400">{open}</span>
              )}
            </TabsTrigger>
          ))}
        </TabsList>
        {list.map((tab) => (
          <TabsContent key={tab} value={tab} className="mt-4">
            {surface(tab)}
          </TabsContent>
        ))}
      </Tabs>
    </article>
  );
}
