// frontend/slices/markdown-svelte/components/WriteTab.svelte
<script lang="ts">
  import { MARKDOWN_SNIPPETS } from "../../markdown/lib/snippets";
  import { parseMarkdown } from "../../markdown/lib/parse";
  import MarkdownNodes from "./MarkdownNodes.svelte";

  let { value, onChange }: { value: string; onChange: (next: string) => void } = $props();
  let textarea: HTMLTextAreaElement | undefined;
  const nodes = $derived(parseMarkdown(value));

  function insert(snippet: string) {
    const at = textarea?.selectionStart ?? value.length;
    const next = value.slice(0, at) + snippet + value.slice(at);
    onChange(next);
    setTimeout(() => {
      textarea?.focus();
      textarea?.setSelectionRange(at + snippet.length, at + snippet.length);
    }, 0);
  }
</script>

<div class="flex flex-col gap-2">
  <div class="flex flex-wrap gap-1">
    {#each MARKDOWN_SNIPPETS as item}
      <button class="h-7 rounded-md border px-2 text-xs hover:bg-muted" type="button" onclick={() => insert(item.snippet)}>{item.label}</button>
    {/each}
  </div>
  <div class="grid gap-3 lg:grid-cols-2">
    <textarea bind:this={textarea} value={value} oninput={(event) => onChange(event.currentTarget.value)} aria-label="Markdown source" spellcheck="false" class="min-h-[420px] resize-y rounded-md border bg-background p-3 font-mono text-xs leading-relaxed"></textarea>
    <div class="min-h-[420px] overflow-auto rounded-md border border-border bg-background px-4 py-2"><MarkdownNodes {nodes} /></div>
  </div>
</div>

// frontend/slices/markdown/components/WriteTab.tsx
"use client";

/** Write tab — raw markdown source editor with live preview. Controlled:
 *  `value` + `onChange`. Toolbar inserts snippets at the caret. The preview
 *  pane re-parses on every keystroke (parser is line-based and cheap). */

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { parseMarkdown } from "../lib/parse";
import { renderNodes } from "./MdNodeView";

import { MARKDOWN_SNIPPETS } from "../lib/snippets";


interface Props {
  value: string;
  onChange: (next: string) => void;
}

export function WriteTab({ value, onChange }: Props) {
  const ref = React.useRef<HTMLTextAreaElement>(null);
  const nodes = React.useMemo(() => parseMarkdown(value), [value]);

  const insert = (snippet: string) => {
    const el = ref.current;
    const at = el ? el.selectionStart : value.length;
    const next = value.slice(0, at) + snippet + value.slice(at);
    onChange(next);
    requestAnimationFrame(() => {
      el?.focus();
      el?.setSelectionRange(at + snippet.length, at + snippet.length);
    });
  };

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap gap-1">
        {MARKDOWN_SNIPPETS.map((s) => (
          <Button key={s.label} variant="outline" size="sm" type="button" className="h-7 px-2 text-xs" onClick={() => insert(s.snippet)}>
            {s.label}
          </Button>
        ))}
      </div>
      <div className="grid gap-3 lg:grid-cols-2">
        <Textarea
          ref={ref}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          aria-label="Markdown source"
          spellCheck={false}
          className="min-h-[420px] resize-y font-mono text-xs leading-relaxed"
        />
        <div className="min-h-[420px] overflow-auto rounded-md border border-border bg-background px-4 py-2">
          {renderNodes(nodes)}
        </div>
      </div>
    </div>
  );
}
