// frontend/slices/dashboard-shell/components/mobile-dock.tsx
"use client";

import Link from "next/link";
import { Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { isActive } from "../lib/nav";
import type { NavItem } from "../lib/types";

export interface MobileDockProps {
  items: NavItem[];
  pathname: string;
  /** Opens the thumbnail menu drawer — the mobile face of the sidebar. */
  onMenu?: () => void;
  /** Hide the trailing "Menu" button. */
  hideMenu?: boolean;
  className?: string;
}

/**
 * Bottom dock — the mobile face of the same nav the sidebar renders.
 * Pure CSS breakpoint (`md:hidden`): no JS media query, so no hydration flash
 * and no second source of truth for "am I mobile".
 */
export function MobileDock({ items, pathname, onMenu, hideMenu, className }: MobileDockProps) {
  const showMenu = !hideMenu && !!onMenu;
  if (!items.length && !showMenu) return null;

  return (
    <nav
      aria-label="Dashboard"
      className={cn(
        "pointer-events-none fixed inset-x-0 bottom-0 z-40 px-3 pt-3 md:hidden",
        "pb-[calc(env(safe-area-inset-bottom)+0.75rem)]",
        className,
      )}
    >
      <div className="pointer-events-auto mx-auto flex max-w-md items-center gap-1 rounded-xl border bg-background/95 p-2 shadow-lg backdrop-blur">
        {items.map((item) => (
          <DockButton key={item.id} item={item} active={isActive(pathname, item)} />
        ))}
        {showMenu ? (
          <DockButton
            item={{ id: "__menu", label: "Menu", icon: Menu, onSelect: onMenu }}
            active={false}
          />
        ) : null}
      </div>
    </nav>
  );
}

function DockButton({ item, active }: { item: NavItem; active: boolean }) {
  const Icon = item.icon;
  const body = (
    <>
      {Icon ? <Icon className="size-4" /> : null}
      <span className="truncate">{item.label}</span>
    </>
  );
  const className = cn(
    "flex h-auto min-w-0 flex-1 flex-col gap-1 rounded-xl px-2 py-2 text-[11px] text-muted-foreground",
    active && "bg-muted text-foreground",
  );

  if (item.href) {
    return (
      <Button asChild variant="ghost" className={className} aria-current={active ? "page" : undefined}>
        <Link href={item.href}>{body}</Link>
      </Button>
    );
  }

  return (
    <Button variant="ghost" className={className} onClick={item.onSelect}>
      {body}
    </Button>
  );
}

// frontend/slices/dashboard-shell-svelte/components/MobileDock.svelte
<script lang="ts">
  import { isActive } from "../../dashboard-shell/lib/nav";
  import type { NavItem } from "../types";

  interface Props {
    items: NavItem[];
    pathname: string;
    onMenu?: () => void;
    hideMenu?: boolean;
    className?: string;
  }

  let { items, pathname, onMenu, hideMenu = false, className = "" }: Props = $props();
  let showMenu = $derived(!hideMenu && !!onMenu);
</script>

{#snippet dockBody(item: NavItem)}
  {#if item.icon}
    {@render item.icon("size-4")}
  {:else}
    <span class="text-sm font-semibold">{item.label.slice(0, 1).toUpperCase()}</span>
  {/if}
  <span class="max-w-full truncate">{item.label}</span>
{/snippet}

{#if items.length || showMenu}
  <nav aria-label="Dashboard" class={`pointer-events-none fixed inset-x-0 bottom-0 z-40 px-3 pt-3 pb-[calc(env(safe-area-inset-bottom)+0.75rem)] md:hidden ${className}`}>
    <div class="pointer-events-auto mx-auto flex max-w-md items-center gap-1 rounded-xl border bg-background/95 p-2 shadow-lg backdrop-blur">
      {#each items as item (item.id)}
        {@const active = isActive(pathname, item)}
        {#if item.href}
          <a
            href={item.href}
            aria-current={active ? "page" : undefined}
            class={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[11px] ${active ? "bg-muted text-foreground" : "text-muted-foreground"}`}
          >
            {@render dockBody(item)}
          </a>
        {:else}
          <button
            type="button"
            onclick={() => item.onSelect?.()}
            class={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[11px] ${active ? "bg-muted text-foreground" : "text-muted-foreground"}`}
          >
            {@render dockBody(item)}
          </button>
        {/if}
      {/each}
      {#if showMenu}
        <button type="button" onclick={onMenu} class="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[11px] text-muted-foreground">
          <span aria-hidden="true" class="text-base">☰</span>
          <span>Menu</span>
        </button>
      {/if}
    </div>
  </nav>
{/if}
