// frontend/slices/markdown/components/MarkdownReader.tsx
/** MarkdownReader — read-only page container for markdown rich text.
 *
 *  The sibling read surface to the notion block editor: feed it a markdown
 *  string (e.g. produced by `blocksToMarkdown(notionBlocks)`) and it renders
 *  the same content as a clean document. Pure presentational — no editing, no
 *  store, no Convex. Pass `content` (markdown) or pre-parsed `nodes`. */

"use client";

import * as React from "react";
import { cx } from "../lib/classnames";
import { parseMarkdown, type MdNode } from "../lib/parse";
import { renderNodes } from "./MdNodeView";

const MAXW = {
  prose: "max-w-prose",
  "2xl": "max-w-2xl",
  "3xl": "max-w-3xl",
  none: "max-w-none",
} as const;

export interface MarkdownReaderProps {
  /** Markdown source. Ignored when `nodes` is provided. */
  content?: string;
  /** Pre-parsed nodes (skip parsing — e.g. shared parse result). */
  nodes?: MdNode[];
  /** Page title rendered above the body. */
  title?: string;
  /** Emoji or icon node shown before the title. */
  icon?: React.ReactNode;
  /** Content column width. Default `3xl`. */
  maxWidth?: keyof typeof MAXW;
  className?: string;
}

export function MarkdownReader({
  content = "",
  nodes,
  title,
  icon,
  maxWidth = "3xl",
  className,
}: MarkdownReaderProps) {
  const parsed = React.useMemo(() => nodes ?? parseMarkdown(content), [nodes, content]);
  return (
    <article className={cx("mx-auto w-full px-4 py-6", MAXW[maxWidth], className)}>
      {title && (
        <header className="mb-4 flex items-center gap-2">
          {icon && <span className="text-2xl leading-none">{icon}</span>}
          <h1 className="text-3xl font-bold tracking-tight">{title}</h1>
        </header>
      )}
      <div className="text-foreground">{renderNodes(parsed)}</div>
    </article>
  );
}

// frontend/slices/markdown-svelte/components/MarkdownReader.svelte
<script lang="ts">
  import { parseMarkdown, type MdNode } from "../../markdown/lib/parse";
  import MarkdownNodes from "./MarkdownNodes.svelte";

  type MaxWidth = "prose" | "2xl" | "3xl" | "none";
  let { content = "", nodes, title, icon, maxWidth = "3xl", className = "" }: {
    content?: string;
    nodes?: MdNode[];
    title?: string;
    icon?: string;
    maxWidth?: MaxWidth;
    className?: string;
  } = $props();

  const parsed = $derived(nodes ?? parseMarkdown(content));
  const maxWidthClass = $derived({ prose: "max-w-prose", "2xl": "max-w-2xl", "3xl": "max-w-3xl", none: "max-w-none" }[maxWidth]);
</script>

<article class={`mx-auto w-full px-4 py-6 ${maxWidthClass} ${className}`}>
  {#if title}
    <header class="mb-4 flex items-center gap-2">
      {#if icon}<span class="text-2xl leading-none">{icon}</span>{/if}
      <h1 class="text-3xl font-bold tracking-tight">{title}</h1>
    </header>
  {/if}
  <div class="text-foreground"><MarkdownNodes nodes={parsed} /></div>
</article>
